CPN: CPN::RemoteContextServer Class Reference
CPN::RemoteContextServer Class Reference abstract
the server for the remote context.
#include <RemoteContextServer.h>
Public Member Functions
RemoteContextServer ()
virtual ~RemoteContextServer ()
virtual void Terminate ()
bool IsTerminated () const
int DebugLevel () const
int DebugLevel (int level)
Protected Member Functions
void DispatchMessage (const std::string &sender, const Variant &msg)
Process the given message.
virtual void SendMessage (const std::string &recipient, const Variant &msg)=0
Send the given message to the given client.
virtual void BroadcastMessage (const Variant &msg)=0
Broadcast a message to all clients.
virtual void LogMessage (const std::string &msg)=0
Log a message.
void dbprintf (int level, const char *fmt,...)
Private Types
typedef std::map< Key_t, Variant > DataMap
typedef std::map< std::string,
Key_t > NameKeyMap
Private Member Functions
void SetupKernel (const std::string &sender, const Variant &msg)
void SignalKernelStart (const Variant &msg)
void SignalKernelEnd (const Variant &msg)
void GetKernelInfo (const std::string &sender, const Variant &msg)
void CreateNodeKey (const std::string &sender, const Variant &msg)
void SignalNodeStart (const Variant &msg)
void SignalNodeEnd (const Variant &msg)
void GetNodeInfo (const std::string &sender, const Variant &msg)
void GetNumNodeLive (const std::string &sender, const Variant &msg)
void GetCreateEndpointKey (const std::string &sender, const Variant &msg)
void GetEndpointInfo (const std::string &sender, const Variant &msg)
void ConnectEndpoints (const Variant &msg)
Key_t NewKey ()
void RouteKernelMessage (const Variant &msg)
Variant NewBroadcastMessage ()
Private Attributes
DataMap datamap
NameKeyMap kernelmap
NameKeyMap nodemap
int debuglevel
bool shutdown
unsigned numlivenodes
Key_t keycount
Detailed Description
the server for the remote context.
Implementors only need to override SendMessage, BroadcastMessage, and LogMessage. then call DispatchMessage for all messages from the clients.
Definition at line 114 of file RemoteContextServer.h.
Member Typedef Documentation
typedef std::map<Key_t, Variant> CPN::RemoteContextServer::DataMap private
Definition at line 170 of file RemoteContextServer.h.
typedef std::map<std::string, Key_t> CPN::RemoteContextServer::NameKeyMap private
Definition at line 172 of file RemoteContextServer.h.
Constructor & Destructor Documentation
CPN::RemoteContextServer::RemoteContextServer ()
Definition at line 32 of file RemoteContextServer.cc.
         : debuglevel(0), shutdown(false), numlivenodes(0), keycount(0)
     {
     }
CPN::RemoteContextServer::~RemoteContextServer () virtual
Definition at line 37 of file RemoteContextServer.cc.
{
     }
Member Function Documentation
virtual void CPN::RemoteContextServer::BroadcastMessage (const Variant & msg) protected pure virtual
Broadcast a message to all clients.
Parameters
msg the message to send to all clients
Implemented in CPN::RemoteContextDaemon.
Referenced by SignalKernelEnd(), SignalKernelStart(), SignalNodeEnd(), SignalNodeStart(), and Terminate().
void CPN::RemoteContextServer::ConnectEndpoints (const Variant & msg) private
Definition at line 331 of file RemoteContextServer.cc.
References datamap.
Referenced by DispatchMessage().
{
         Key_t wkey = msg["writerkey"].AsNumber<Key_t>();
         Key_t rkey = msg["readerkey"].AsNumber<Key_t>();
         std::string qname = msg["qname"].AsString();
         datamap[wkey]["readerkey"] = rkey;
         datamap[rkey]["writerkey"] = wkey;
         datamap[rkey]["qname"] = qname;
         datamap[wkey]["qname"] = qname;
     }
void CPN::RemoteContextServer::CreateNodeKey (const std::string & sender, const Variant & msg) private
Definition at line 197 of file RemoteContextServer.cc.
References datamap, dbprintf(), NewKey(), nodemap, and SendMessage().
Referenced by DispatchMessage().
{
         std::string nodename = msg["name"].AsString();
         Variant reply(Variant::MapType);
         reply["msgid"] = msg["msgid"];
         reply["msgtype"] = "reply";
         if (nodemap.find(nodename) != nodemap.end()) {
             reply["success"] = false;
         } else {
             Key_t nodekey = NewKey();
             Variant nodeinfo(Variant::MapType);
             nodeinfo["name"] = nodename;
             nodeinfo["key"] = nodekey;
             nodeinfo["kernelkey"] = msg["kernelkey"];
             nodeinfo["started"] = false;
             nodeinfo["dead"] = false;
             nodeinfo["type"] = "nodeinfo";
             nodeinfo["endpoints"] = Variant::MapType;
             dbprintf(2, "Node %s created\n", nodename.c_str());
             nodemap[nodename] = nodekey;
             datamap[nodekey] = nodeinfo;
             reply["success"] = true;
             reply["nodeinfo"] = nodeinfo.Copy();
         }
         SendMessage(sender, reply);
     }
void CPN::RemoteContextServer::dbprintf (int level, const char * fmt, ...) protected
Definition at line 40 of file RemoteContextServer.cc.
References debuglevel.
Referenced by CPN::RemoteContextDaemon::BroadcastMessage(), CPN::RemoteContextDaemon::Client::Client(), CreateNodeKey(), DispatchMessage(), CPN::RemoteContextDaemon::LogMessage(), CPN::RemoteContextDaemon::Run(), CPN::RemoteContextDaemon::SendMessage(), SetupKernel(), SignalKernelEnd(), SignalKernelStart(), SignalNodeEnd(), SignalNodeStart(), and CPN::RemoteContextDaemon::Terminate().
{
         if (debuglevel >= level) {
             va_list ap;
             va_start(ap, fmt);
             vprintf(fmt, ap);
             va_end(ap);
         }
     }
int CPN::RemoteContextServer::DebugLevel () const inline
Definition at line 126 of file RemoteContextServer.h.
References debuglevel.
 { return debuglevel; }
int CPN::RemoteContextServer::DebugLevel (int level) inline
Definition at line 127 of file RemoteContextServer.h.
References debuglevel.
 { return debuglevel = level; }
void CPN::RemoteContextServer::DispatchMessage (const std::string & sender, const Variant & msg) protected
Process the given message.
Parameters
sender a string id for the client
msg the message that the client sent
Definition at line 49 of file RemoteContextServer.cc.
References ASSERT, ConnectEndpoints(), CreateNodeKey(), dbprintf(), GetCreateEndpointKey(), GetEndpointInfo(), GetKernelInfo(), GetNodeInfo(), GetNumNodeLive(), IsTerminated(), LogMessage(), CPN::RCTXMT_CONNECT_ENDPOINTS, CPN::RCTXMT_CREATE_NODE, CPN::RCTXMT_CREATE_NODE_KEY, CPN::RCTXMT_CREATE_QUEUE, CPN::RCTXMT_CREATE_READER, CPN::RCTXMT_CREATE_WRITER, CPN::RCTXMT_GET_CREATE_READER_KEY, CPN::RCTXMT_GET_CREATE_WRITER_KEY, CPN::RCTXMT_GET_KERNEL_INFO, CPN::RCTXMT_GET_NODE_INFO, CPN::RCTXMT_GET_NUM_NODE_LIVE, CPN::RCTXMT_GET_READER_INFO, CPN::RCTXMT_GET_WRITER_INFO, CPN::RCTXMT_LOG, CPN::RCTXMT_SETUP_KERNEL, CPN::RCTXMT_SIGNAL_KERNEL_END, CPN::RCTXMT_SIGNAL_KERNEL_START, CPN::RCTXMT_SIGNAL_NODE_END, CPN::RCTXMT_SIGNAL_NODE_START, CPN::RCTXMT_TERMINATE, RouteKernelMessage(), SetupKernel(), SignalKernelEnd(), SignalKernelStart(), SignalNodeEnd(), SignalNodeStart(), and Terminate().
{
         dbprintf(4, "msg:%s:%s\n", sender.c_str(), libvariant::SerializeJSON(msg).c_str());
         if (!msg.IsMap()) { return; }
         if (IsTerminated()) {
             return;
         }
         RCTXMT_t type = msg["type"].AsNumber<RCTXMT_t>();
         switch (type) {
         case RCTXMT_SETUP_KERNEL:
             SetupKernel(sender, msg);
             break;
         case RCTXMT_SIGNAL_KERNEL_START:
             SignalKernelStart(msg);
             break;
         case RCTXMT_SIGNAL_KERNEL_END:
             SignalKernelEnd(msg);
             break;
         case RCTXMT_GET_KERNEL_INFO:
             GetKernelInfo(sender, msg);
             break;
         case RCTXMT_CREATE_WRITER:
         case RCTXMT_CREATE_READER:
         case RCTXMT_CREATE_QUEUE:
         case RCTXMT_CREATE_NODE:
             RouteKernelMessage(msg);
             break;
         case RCTXMT_CREATE_NODE_KEY:
             CreateNodeKey(sender, msg);
             break;
         case RCTXMT_SIGNAL_NODE_START:
             SignalNodeStart(msg);
             break;
         case RCTXMT_SIGNAL_NODE_END:
             SignalNodeEnd(msg);
             break;
         case RCTXMT_GET_NODE_INFO:
             GetNodeInfo(sender, msg);
             break;
         case RCTXMT_GET_NUM_NODE_LIVE:
             GetNumNodeLive(sender, msg);
             break;
         case RCTXMT_GET_CREATE_READER_KEY:
             GetCreateEndpointKey(sender, msg);
             break;
         case RCTXMT_GET_READER_INFO:
             GetEndpointInfo(sender, msg);
             break;
         case RCTXMT_GET_CREATE_WRITER_KEY:
             GetCreateEndpointKey(sender, msg);
             break;
         case RCTXMT_GET_WRITER_INFO:
             GetEndpointInfo(sender, msg);
             break;
         case RCTXMT_CONNECT_ENDPOINTS:
             ConnectEndpoints(msg);
             break;
         case RCTXMT_TERMINATE:
             Terminate();
             break;
         case RCTXMT_LOG:
             LogMessage(sender + ":" + msg["msg"].AsString());
             break;
         default:
             ASSERT(false);
         }
     }
void CPN::RemoteContextServer::GetCreateEndpointKey (const std::string & sender, const Variant & msg) private
Definition at line 281 of file RemoteContextServer.cc.
References ASSERT, datamap, NewKey(), and SendMessage().
Referenced by DispatchMessage().
{
         std::string name = msg["name"].AsString();
         Variant reply;
         reply["msgid"] = msg["msgid"];
         reply["msgtype"] = "reply";
         reply["success"] = false;
         Key_t nodekey = msg["nodekey"].AsNumber<Key_t>();
         DataMap::iterator nodeentry = datamap.find(nodekey);
         if (nodeentry != datamap.end()) {
             Variant nodeinfo = nodeentry->second;
             Variant epinfo;
             Key_t epkey;
             if (nodeinfo["endpoints"].Contains(name)) {
                 epkey = nodeinfo["endpoints"][name].AsNumber<Key_t>();
                 epinfo = datamap[epkey];
                 ASSERT(epinfo["type"].AsString() == "endpointinfo");
             } else {
                 epkey = NewKey();
                 nodeinfo["endpoints"][name] = epkey;
                 epinfo = Variant(Variant::MapType);
                 epinfo["key"] = epkey;
                 epinfo["name"] = name;
                 epinfo["nodekey"] = nodekey;
                 epinfo["kernelkey"] = nodeinfo["kernelkey"];
                 epinfo["live"] = true;
                 epinfo["type"] = "endpointinfo";
                 datamap[epkey] = epinfo;
             }
             reply["endpointinfo"] = epinfo.Copy();
             reply["success"] = true;
         }
         SendMessage(sender, reply);
     }
void CPN::RemoteContextServer::GetEndpointInfo (const std::string & sender, const Variant & msg) private
Definition at line 315 of file RemoteContextServer.cc.
References ASSERT, datamap, and SendMessage().
Referenced by DispatchMessage().
{
         Key_t epkey = msg["key"].AsNumber<Key_t>();
         Variant reply;
         reply["msgid"] = msg["msgid"];
         reply["msgtype"] = "reply";
         reply["success"] = false;
         DataMap::iterator entry = datamap.find(epkey);
         if (entry != datamap.end()) {
             reply["success"] = true;
             reply["endpointinfo"] = entry->second.Copy();
             ASSERT(reply["endpointinfo"]["type"].AsString() == "endpointinfo");
         }
         SendMessage(sender, reply);
     }
void CPN::RemoteContextServer::GetKernelInfo (const std::string & sender, const Variant & msg) private
Definition at line 172 of file RemoteContextServer.cc.
References ASSERT, datamap, kernelmap, and SendMessage().
Referenced by DispatchMessage().
{
         Key_t kernelkey;
         Variant reply(Variant::MapType);
         reply["msgtype"] = "reply";
         reply["msgid"] = msg["msgid"];
         reply["success"] = false;
         if (msg.Contains("name")) {
             NameKeyMap::iterator entry = kernelmap.find(msg["name"].AsString());
             if (entry == kernelmap.end()) {
                 SendMessage(sender, reply);
                 return;
             }
             kernelkey = entry->second;
         } else {
             kernelkey = msg["key"].AsNumber<Key_t>();
         }
         DataMap::iterator entry = datamap.find(kernelkey);
         if (entry != datamap.end()) {
             ASSERT(entry->second["type"].AsString() == "kernelinfo");
             reply["success"] = true;
             reply["kernelinfo"] = entry->second.Copy();
         }
         SendMessage(sender, reply);
     }
void CPN::RemoteContextServer::GetNodeInfo (const std::string & sender, const Variant & msg) private
Definition at line 247 of file RemoteContextServer.cc.
References ASSERT, datamap, nodemap, and SendMessage().
Referenced by DispatchMessage().
{
         Key_t nodekey;
         Variant reply(Variant::MapType);
         reply["msgtype"] = "reply";
         reply["msgid"] = msg["msgid"];
         reply["success"] = false;
         if (msg.Contains("name")) {
             NameKeyMap::iterator entry = nodemap.find(msg["name"].AsString());
             if (entry == nodemap.end()) {
                 SendMessage(sender, reply);
                 return;
             }
             nodekey = entry->second;
         } else {
             nodekey = msg["key"].AsNumber<Key_t>();
         }
         DataMap::iterator entry = datamap.find(nodekey);
         if (entry != datamap.end()) {
             reply["nodeinfo"] = entry->second.Copy();
             ASSERT(reply["nodeinfo"]["type"].AsString() == "nodeinfo");
             reply["success"] = true;
         }
         SendMessage(sender, reply);
     }
void CPN::RemoteContextServer::GetNumNodeLive (const std::string & sender, const Variant & msg) private
Definition at line 272 of file RemoteContextServer.cc.
References numlivenodes, and SendMessage().
Referenced by DispatchMessage().
{
         Variant reply(Variant::MapType);
         reply["msgid"] = msg["msgid"];
         reply["msgtype"] = "reply";
         reply["numlivenodes"] = numlivenodes;
         reply["success"] = true;
         SendMessage(sender, reply);
     }
bool CPN::RemoteContextServer::IsTerminated () const inline
Returns
whether or not the context is in the shutdown state.
Definition at line 125 of file RemoteContextServer.h.
References shutdown.
Referenced by CPN::RemoteContextDaemon::BroadcastMessage(), DispatchMessage(), CPN::RemoteContextDaemon::Run(), CPN::RemoteContextDaemon::SendMessage(), and CPN::RemoteContextDaemon::Terminate().
 { return shutdown; }
virtual void CPN::RemoteContextServer::LogMessage (const std::string & msg) protected pure virtual
Log a message.
Parameters
msg the message to be logged
Implemented in CPN::RemoteContextDaemon.
Referenced by DispatchMessage().
Variant CPN::RemoteContextServer::NewBroadcastMessage () private
Definition at line 352 of file RemoteContextServer.cc.
References numlivenodes.
Referenced by SignalKernelEnd(), SignalKernelStart(), SignalNodeEnd(), and SignalNodeStart().
{
         Variant msg;
         msg["msgtype"] = "broadcast";
         msg["numlivenodes"] = numlivenodes;
         return msg;
     }
Key_t CPN::RemoteContextServer::NewKey () private
Definition at line 341 of file RemoteContextServer.cc.
References keycount.
Referenced by CreateNodeKey(), GetCreateEndpointKey(), and SetupKernel().
{
         // 0 is reserved
         return ++keycount;
     }
void CPN::RemoteContextServer::RouteKernelMessage (const Variant & msg) private
Definition at line 346 of file RemoteContextServer.cc.
References datamap, and SendMessage().
Referenced by DispatchMessage().
{
         Key_t kernelkey = msg["kernelkey"].AsNumber<Key_t>();
         Variant kernelinfo = datamap[kernelkey];
         SendMessage(kernelinfo["client"].AsString(), msg);
     }
virtual void CPN::RemoteContextServer::SendMessage (const std::string & recipient, const Variant & msg) protected pure virtual
Send the given message to the given client.
Parameters
recipient the id (previously used in DispatchMessage sender)
msg the message to be sent to the client
Implemented in CPN::RemoteContextDaemon.
Referenced by CreateNodeKey(), GetCreateEndpointKey(), GetEndpointInfo(), GetKernelInfo(), GetNodeInfo(), GetNumNodeLive(), RouteKernelMessage(), and SetupKernel().
void CPN::RemoteContextServer::SetupKernel (const std::string & sender, const Variant & msg) private
Definition at line 123 of file RemoteContextServer.cc.
References datamap, dbprintf(), kernelmap, NewKey(), and SendMessage().
Referenced by DispatchMessage().
{
         std::string name = msg["name"].AsString();
         Variant reply(Variant::MapType);
         reply["msgid"] = msg["msgid"];
         reply["msgtype"] = "reply";
         if (kernelmap.find(name) != kernelmap.end()) {
             reply["success"] = false;
             return;
         } else {
             Variant kernelinfo(Variant::MapType);
             Key_t kernelkey = NewKey();
             kernelinfo["key"] = kernelkey;
             kernelinfo["name"] = name;
             kernelinfo["hostname"] = msg["hostname"];
             kernelinfo["servname"] = msg["servname"];
             kernelinfo["live"] = false;
             kernelinfo["type"] = "kernelinfo";
             kernelinfo["client"] = sender;
             datamap.insert(std::make_pair(kernelkey, kernelinfo));
             kernelmap.insert(std::make_pair(name, kernelkey));
             dbprintf(2, "Kernel %s created\n", name.c_str());
             reply["success"] = true;
             reply["kernelinfo"] = kernelinfo.Copy();
         }
         SendMessage(sender, reply);
     }
void CPN::RemoteContextServer::SignalKernelEnd (const Variant & msg) private
Definition at line 161 of file RemoteContextServer.cc.
References ASSERT, BroadcastMessage(), datamap, dbprintf(), and NewBroadcastMessage().
Referenced by DispatchMessage().
{
         Key_t kernelkey = msg["key"].AsNumber<Key_t>();
         Variant kernelinfo = datamap[kernelkey];
         ASSERT(kernelinfo["type"].AsString() == "kernelinfo");
         kernelinfo["live"] = false;
         dbprintf(2, "Kernel %s stopped\n", kernelinfo["name"].AsString().c_str());
         Variant notice = NewBroadcastMessage();
         notice["kernelinfo"] = kernelinfo.Copy();
         BroadcastMessage(notice);
     }
void CPN::RemoteContextServer::SignalKernelStart (const Variant & msg) private
Definition at line 150 of file RemoteContextServer.cc.
References ASSERT, BroadcastMessage(), datamap, dbprintf(), and NewBroadcastMessage().
Referenced by DispatchMessage().
{
         Key_t kernelkey = msg["key"].AsNumber<Key_t>();
         Variant kernelinfo = datamap[kernelkey];
         ASSERT(kernelinfo["type"].AsString() == "kernelinfo");
         kernelinfo["live"] = true;
         dbprintf(2, "Kernel %s started\n", kernelinfo["name"].AsString().c_str());
         Variant notice = NewBroadcastMessage();
         notice["kernelinfo"] = kernelinfo.Copy();
         BroadcastMessage(notice);
     }
void CPN::RemoteContextServer::SignalNodeEnd (const Variant & msg) private
Definition at line 235 of file RemoteContextServer.cc.
References ASSERT, BroadcastMessage(), datamap, dbprintf(), NewBroadcastMessage(), and numlivenodes.
Referenced by DispatchMessage().
{
         --numlivenodes;
         Key_t nodekey = msg["key"].AsNumber<Key_t>();
         Variant nodeinfo = datamap[nodekey];
         ASSERT(nodeinfo["type"].AsString() == "nodeinfo");
         nodeinfo["dead"] = true;
         dbprintf(2, "Node %s stopped\n", nodeinfo["name"].AsString().c_str());
         Variant notice = NewBroadcastMessage();
         notice["nodeinfo"] = nodeinfo.Copy();
         BroadcastMessage(notice);
     }
void CPN::RemoteContextServer::SignalNodeStart (const Variant & msg) private
Definition at line 223 of file RemoteContextServer.cc.
References ASSERT, BroadcastMessage(), datamap, dbprintf(), NewBroadcastMessage(), and numlivenodes.
Referenced by DispatchMessage().
{
         ++numlivenodes;
         Key_t nodekey = msg["key"].AsNumber<Key_t>();
         Variant nodeinfo = datamap[nodekey];
         ASSERT(nodeinfo["type"].AsString() == "nodeinfo");
         nodeinfo["started"] = true;
         dbprintf(2, "Node %s started\n", nodeinfo["name"].AsString().c_str());
         Variant notice = NewBroadcastMessage();
         notice["nodeinfo"] = nodeinfo.Copy();
         BroadcastMessage(notice);
     }
void CPN::RemoteContextServer::Terminate () virtual
Cause the context to go into the shutdown state.
Reimplemented in CPN::RemoteContextDaemon.
Definition at line 116 of file RemoteContextServer.cc.
References BroadcastMessage(), CPN::RCTXMT_TERMINATE, and shutdown.
Referenced by DispatchMessage(), and CPN::RemoteContextDaemon::Terminate().
{
         Variant msg(Variant::MapType);
         msg["type"] = RCTXMT_TERMINATE;
         BroadcastMessage(msg);
         shutdown = true;
     }
Member Data Documentation
DataMap CPN::RemoteContextServer::datamap private
Definition at line 171 of file RemoteContextServer.h.
Referenced by ConnectEndpoints(), CreateNodeKey(), GetCreateEndpointKey(), GetEndpointInfo(), GetKernelInfo(), GetNodeInfo(), RouteKernelMessage(), SetupKernel(), SignalKernelEnd(), SignalKernelStart(), SignalNodeEnd(), and SignalNodeStart().
int CPN::RemoteContextServer::debuglevel private
Definition at line 176 of file RemoteContextServer.h.
Referenced by dbprintf(), and DebugLevel().
NameKeyMap CPN::RemoteContextServer::kernelmap private
Definition at line 173 of file RemoteContextServer.h.
Referenced by GetKernelInfo(), and SetupKernel().
Key_t CPN::RemoteContextServer::keycount private
Definition at line 180 of file RemoteContextServer.h.
Referenced by NewKey().
NameKeyMap CPN::RemoteContextServer::nodemap private
Definition at line 174 of file RemoteContextServer.h.
Referenced by CreateNodeKey(), and GetNodeInfo().
unsigned CPN::RemoteContextServer::numlivenodes private
Definition at line 178 of file RemoteContextServer.h.
Referenced by GetNumNodeLive(), NewBroadcastMessage(), SignalNodeEnd(), and SignalNodeStart().
bool CPN::RemoteContextServer::shutdown private
Definition at line 177 of file RemoteContextServer.h.
Referenced by IsTerminated(), and Terminate().
The documentation for this class was generated from the following files:
include/cpn/remote_context/RemoteContextServer.h
lib/RemoteContextServer.cc