CPN: CPN::KernelBase Class Reference
CPN::KernelBase Class Reference abstract
#include <KernelBase.h>
Public Member Functions
virtual ~KernelBase ()
virtual void RemoteCreateWriter (SimpleQueueAttr attr)
virtual void RemoteCreateReader (SimpleQueueAttr attr)
virtual void RemoteCreateQueue (SimpleQueueAttr attr)
virtual void RemoteCreateNode (NodeAttr attr)
virtual void NotifyTerminate ()
virtual bool IsTerminated ()=0
virtual void CheckTerminated ()=0
virtual shared_ptr< Context > GetContext () const =0
virtual bool UseD4R ()=0
virtual bool GrowQueueMaxThreshold ()=0
virtual bool SwallowBrokenQueueExceptions ()=0
virtual unsigned CalculateGrowSize (unsigned currentsize, unsigned request)=0
Detailed Description
Base class for the kernel. This class contains all the methods that the context needs to call. This class is primiarly used so that the unit tests can provide a subclass to test the context functionality.
Definition at line 39 of file KernelBase.h.
Constructor & Destructor Documentation
CPN::KernelBase::~KernelBase () virtual
Definition at line 28 of file KernelBase.cc.
 {}
Member Function Documentation
virtual unsigned CPN::KernelBase::CalculateGrowSize (unsigned currentsize, unsigned request) pure virtual
Implemented in CPN::Kernel.
Referenced by CPN::QueueBase::Detect().
virtual void CPN::KernelBase::CheckTerminated () pure virtual
Implemented in CPN::Kernel.
Referenced by CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::QueueBase::ReadBlocked(), and CPN::QueueBase::WriteBlocked().
virtual shared_ptr<Context> CPN::KernelBase::GetContext () const pure virtual
Implemented in CPN::Kernel.
virtual bool CPN::KernelBase::GrowQueueMaxThreshold () pure virtual
Implemented in CPN::Kernel.
Referenced by CPN::QueueBase::GetRawDequeuePtr(), and CPN::QueueBase::GetRawEnqueuePtr().
virtual bool CPN::KernelBase::IsTerminated () pure virtual
Implemented in CPN::Kernel.
Referenced by CPN::RemoteQueue::FileThreadEntryPoint(), and CPN::RemoteQueue::InternalCheckStatus().
void CPN::KernelBase::NotifyTerminate () virtual
Reimplemented in CPN::Kernel.
Definition at line 42 of file KernelBase.cc.
References ASSERT.
{
         ASSERT(false, "Unexpected message");
     }
void CPN::KernelBase::RemoteCreateNode (NodeAttr attr) virtual
Reimplemented in CPN::Kernel.
Definition at line 39 of file KernelBase.cc.
References ASSERT.
Referenced by CPN::RemoteContextClient::DispatchMessage(), and CPN::LocalContext::SendCreateNode().
{
         ASSERT(false, "Unexpected message");
     }
void CPN::KernelBase::RemoteCreateQueue (SimpleQueueAttr attr) virtual
Reimplemented in CPN::Kernel.
Definition at line 36 of file KernelBase.cc.
References ASSERT.
Referenced by CPN::RemoteContextClient::DispatchMessage(), and CPN::LocalContext::SendCreateQueue().
{
         ASSERT(false, "Unexpected message");
     }
void CPN::KernelBase::RemoteCreateReader (SimpleQueueAttr attr) virtual
Reimplemented in CPN::Kernel.
Definition at line 33 of file KernelBase.cc.
References ASSERT.
Referenced by CPN::RemoteContextClient::DispatchMessage(), and CPN::LocalContext::SendCreateReader().
{
         ASSERT(false, "Unexpected message");
     }
void CPN::KernelBase::RemoteCreateWriter (SimpleQueueAttr attr) virtual
Reimplemented in CPN::Kernel.
Definition at line 30 of file KernelBase.cc.
References ASSERT.
Referenced by CPN::RemoteContextClient::DispatchMessage(), and CPN::LocalContext::SendCreateWriter().
{
         ASSERT(false, "Unexpected message");
     }
virtual bool CPN::KernelBase::SwallowBrokenQueueExceptions () pure virtual
Implemented in CPN::Kernel.
virtual bool CPN::KernelBase::UseD4R () pure virtual
Implemented in CPN::Kernel.
The documentation for this class was generated from the following files:
include/cpn/bits/KernelBase.h
lib/KernelBase.cc