CPN: CPN::SimpleQueueAttr Class Reference
CPN::SimpleQueueAttr Class Reference
This is a simplified internal representation of the queue attributes needed to create a queue. This is for internal use only.
#include <QueueAttr.h>
Public Member Functions
SimpleQueueAttr ()
SimpleQueueAttr (const QueueAttr &attr)
SimpleQueueAttr & SetAlpha (double a)
SimpleQueueAttr & SetMaxWriteThreshold (unsigned mwt)
SimpleQueueAttr & SetHint (std::string hint)
SimpleQueueAttr & SetDatatype (const std::string &type)
template<typename type >
SimpleQueueAttr & SetDatatype ()
SimpleQueueAttr & SetLength (unsigned length)
SimpleQueueAttr & SetMaxThreshold (unsigned maxthresh)
SimpleQueueAttr & SetNumChannels (unsigned numchans)
SimpleQueueAttr & SetReaderNodeKey (Key_t k)
SimpleQueueAttr & SetWriterNodeKey (Key_t k)
SimpleQueueAttr & SetReaderKey (Key_t k)
SimpleQueueAttr & SetWriterKey (Key_t k)
Key_t GetWriterNodeKey () const
Key_t GetReaderNodeKey () const
Key_t GetWriterKey () const
Key_t GetReaderKey () const
unsigned GetLength () const
unsigned GetMaxThreshold () const
unsigned GetNumChannels () const
std::string GetHint () const
const std::string & GetDatatype () const
double GetAlpha () const
unsigned GetMaxWriteThreshold () const
Private Attributes
std::string queuehint
std::string datatype
unsigned queueLength
unsigned maxThreshold
unsigned numChannels
double alpha
Key_t readerkey
Key_t writerkey
Key_t readernodekey
Key_t writernodekey
unsigned maxwritethreshold
Detailed Description
This is a simplified internal representation of the queue attributes needed to create a queue. This is for internal use only.
Definition at line 237 of file QueueAttr.h.
Constructor & Destructor Documentation
CPN::SimpleQueueAttr::SimpleQueueAttr () inline
Definition at line 239 of file QueueAttr.h.
             : queuehint(),
             queueLength(0), maxThreshold(0),
             numChannels(0), alpha(0.5),
             maxwritethreshold(0)
         {}
CPN::SimpleQueueAttr::SimpleQueueAttr (const QueueAttr & attr) inline
Definition at line 245 of file QueueAttr.h.
             : queuehint(attr.GetHint()),
             datatype(attr.GetDatatype()),
             queueLength(attr.GetLength()),
             maxThreshold(attr.GetMaxThreshold()),
             numChannels(attr.GetNumChannels()),
             alpha(attr.GetAlpha()),
             readerkey(attr.GetReaderKey()),
             writerkey(attr.GetWriterKey()),
             readernodekey(attr.GetReaderNodeKey()),
             writernodekey(attr.GetWriterNodeKey()),
             maxwritethreshold(attr.GetMaxWriteThreshold())
         {}
Member Function Documentation
double CPN::SimpleQueueAttr::GetAlpha () const inline
Definition at line 330 of file QueueAttr.h.
References alpha.
Referenced by CPN::RemoteContextClient::SendQueueMsg().
 { return alpha; }
const std::string& CPN::SimpleQueueAttr::GetDatatype () const inline
Definition at line 329 of file QueueAttr.h.
References datatype.
Referenced by CPN::RemoteContextClient::SendQueueMsg().
 { return datatype; }
std::string CPN::SimpleQueueAttr::GetHint () const inline
Definition at line 328 of file QueueAttr.h.
References queuehint.
Referenced by CPN::Kernel::CreateLocalQueue(), CPN::Kernel::CreateReaderEndpoint(), CPN::Kernel::CreateWriterEndpoint(), and CPN::RemoteContextClient::SendQueueMsg().
 { return queuehint; }
unsigned CPN::SimpleQueueAttr::GetLength () const inline
Definition at line 325 of file QueueAttr.h.
References queueLength.
Referenced by CPN::RemoteContextClient::SendQueueMsg(), and CPN::ThresholdQueue::ThresholdQueue().
 { return queueLength; }
unsigned CPN::SimpleQueueAttr::GetMaxThreshold () const inline
Definition at line 326 of file QueueAttr.h.
References maxThreshold.
Referenced by CPN::RemoteContextClient::SendQueueMsg(), and CPN::ThresholdQueue::ThresholdQueue().
 { return maxThreshold; }
unsigned CPN::SimpleQueueAttr::GetMaxWriteThreshold () const inline
Definition at line 331 of file QueueAttr.h.
References maxwritethreshold.
Referenced by CPN::RemoteContextClient::SendQueueMsg().
 { return maxwritethreshold; }
unsigned CPN::SimpleQueueAttr::GetNumChannels () const inline
Definition at line 327 of file QueueAttr.h.
References numChannels.
Referenced by CPN::RemoteContextClient::SendQueueMsg(), and CPN::ThresholdQueue::ThresholdQueue().
 { return numChannels; }
Key_t CPN::SimpleQueueAttr::GetReaderKey () const inline
Definition at line 324 of file QueueAttr.h.
References readerkey.
Referenced by CPN::Kernel::CreateQueue(), and CPN::RemoteContextClient::SendQueueMsg().
 { return readerkey; }
Key_t CPN::SimpleQueueAttr::GetReaderNodeKey () const inline
Definition at line 322 of file QueueAttr.h.
References readernodekey.
Referenced by CPN::Kernel::CreateLocalQueue(), CPN::Kernel::CreateQueue(), CPN::Kernel::CreateReaderEndpoint(), and CPN::RemoteContextClient::SendQueueMsg().
 { return readernodekey; }
Key_t CPN::SimpleQueueAttr::GetWriterKey () const inline
Definition at line 323 of file QueueAttr.h.
References writerkey.
Referenced by CPN::Kernel::CreateQueue(), and CPN::RemoteContextClient::SendQueueMsg().
 { return writerkey; }
Key_t CPN::SimpleQueueAttr::GetWriterNodeKey () const inline
Definition at line 321 of file QueueAttr.h.
References writernodekey.
Referenced by CPN::Kernel::CreateLocalQueue(), CPN::Kernel::CreateQueue(), CPN::Kernel::CreateWriterEndpoint(), and CPN::RemoteContextClient::SendQueueMsg().
 { return writernodekey; }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetAlpha (double a) inline
Definition at line 259 of file QueueAttr.h.
References alpha.
Referenced by CPN::MsgToQueueAttr().
{
             alpha = a;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetDatatype (const std::string & type) inline
Definition at line 274 of file QueueAttr.h.
References datatype.
Referenced by CPN::MsgToQueueAttr().
{
             datatype = type;
             return *this;
         }
template<typename type > SimpleQueueAttr& CPN::SimpleQueueAttr::SetDatatype () inline
Definition at line 280 of file QueueAttr.h.
References datatype.
{
             datatype = TypeName<type>();
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetHint (std::string hint) inline
Definition at line 269 of file QueueAttr.h.
References queuehint.
Referenced by CPN::MsgToQueueAttr().
{
             queuehint = hint;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetLength (unsigned length) inline
Definition at line 285 of file QueueAttr.h.
References queueLength.
Referenced by CPN::MsgToQueueAttr().
{
             queueLength = length;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetMaxThreshold (unsigned maxthresh) inline
Definition at line 290 of file QueueAttr.h.
References maxThreshold.
Referenced by CPN::MsgToQueueAttr().
{
             maxThreshold = maxthresh;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetMaxWriteThreshold (unsigned mwt) inline
Definition at line 264 of file QueueAttr.h.
References maxwritethreshold.
Referenced by CPN::MsgToQueueAttr().
{
             maxwritethreshold = mwt;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetNumChannels (unsigned numchans) inline
Definition at line 295 of file QueueAttr.h.
References numChannels.
Referenced by CPN::MsgToQueueAttr().
{
             numChannels = numchans;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetReaderKey (Key_t k) inline
Definition at line 310 of file QueueAttr.h.
References readerkey.
Referenced by CPN::Kernel::CreateQueue(), and CPN::MsgToQueueAttr().
{
             readerkey = k;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetReaderNodeKey (Key_t k) inline
Definition at line 300 of file QueueAttr.h.
References readernodekey.
Referenced by CPN::Kernel::CreateQueue(), and CPN::MsgToQueueAttr().
{
             readernodekey = k;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetWriterKey (Key_t k) inline
Definition at line 315 of file QueueAttr.h.
References writerkey.
Referenced by CPN::Kernel::CreateQueue(), and CPN::MsgToQueueAttr().
{
             writerkey = k;
             return *this;
         }
SimpleQueueAttr& CPN::SimpleQueueAttr::SetWriterNodeKey (Key_t k) inline
Definition at line 305 of file QueueAttr.h.
References writernodekey.
Referenced by CPN::Kernel::CreateQueue(), and CPN::MsgToQueueAttr().
{
             writernodekey = k;
             return *this;
         }
Member Data Documentation
double CPN::SimpleQueueAttr::alpha private
Definition at line 338 of file QueueAttr.h.
Referenced by GetAlpha(), and SetAlpha().
std::string CPN::SimpleQueueAttr::datatype private
Definition at line 334 of file QueueAttr.h.
Referenced by GetDatatype(), and SetDatatype().
unsigned CPN::SimpleQueueAttr::maxThreshold private
Definition at line 336 of file QueueAttr.h.
Referenced by GetMaxThreshold(), and SetMaxThreshold().
unsigned CPN::SimpleQueueAttr::maxwritethreshold private
Definition at line 343 of file QueueAttr.h.
Referenced by GetMaxWriteThreshold(), and SetMaxWriteThreshold().
unsigned CPN::SimpleQueueAttr::numChannels private
Definition at line 337 of file QueueAttr.h.
Referenced by GetNumChannels(), and SetNumChannels().
std::string CPN::SimpleQueueAttr::queuehint private
Definition at line 333 of file QueueAttr.h.
Referenced by GetHint(), and SetHint().
unsigned CPN::SimpleQueueAttr::queueLength private
Definition at line 335 of file QueueAttr.h.
Referenced by GetLength(), and SetLength().
Key_t CPN::SimpleQueueAttr::readerkey private
Definition at line 339 of file QueueAttr.h.
Referenced by GetReaderKey(), and SetReaderKey().
Key_t CPN::SimpleQueueAttr::readernodekey private
Definition at line 341 of file QueueAttr.h.
Referenced by GetReaderNodeKey(), and SetReaderNodeKey().
Key_t CPN::SimpleQueueAttr::writerkey private
Definition at line 340 of file QueueAttr.h.
Referenced by GetWriterKey(), and SetWriterKey().
Key_t CPN::SimpleQueueAttr::writernodekey private
Definition at line 342 of file QueueAttr.h.
Referenced by GetWriterNodeKey(), and SetWriterNodeKey().
The documentation for this class was generated from the following file:
include/cpn/QueueAttr.h