CPN: ThresholdQueueBase Class Reference
ThresholdQueueBase Class Reference
#include <ThresholdQueueBase.h>
Public Types
typedef unsigned long ulong
Public Member Functions
ThresholdQueueBase (ulong elemSize, ulong queueLen, ulong maxThresh, ulong numChans=1)
ThresholdQueueBase (ulong elemSize, const ThresholdQueueAttr &attr)
~ThresholdQueueBase (void)
void Reset (void)
void * GetRawEnqueuePtr (ulong enqueueThresh, ulong chan=0) const
void Enqueue (ulong count)
const void * GetRawDequeuePtr (ulong dequeueThresh, ulong chan=0) const
void Dequeue (ulong count)
ulong Count (void) const
ulong Freespace (void) const
bool Empty (void) const
bool Full (void) const
ulong QueueLength (void) const
ulong MaxThreshold (void) const
ulong NumChannels (void) const
ulong ChannelStride (void) const
ulong ElementsEnqueued (void) const
ulong ElementsDequeued (void) const
void Grow (ulong queueLen, ulong maxThresh)
Protected Member Functions
void AllocateBuf (ulong queueLen, ulong maxThresh, ulong numChans, bool useMBS)
Protected Attributes
ulong elementSize
ulong head
ulong tail
ulong queueLength
ulong maxThreshold
ulong numChannels
ulong channelStride
ulong chanOffset
ulong baseOffset
ulong elementsEnqueued
ulong elementsDequeued
void * base
MirrorBufferSet * mbs
Detailed Description
Definition at line 86 of file ThresholdQueueBase.h.
Member Typedef Documentation
typedef unsigned long ThresholdQueueBase::ulong
Definition at line 90 of file ThresholdQueueBase.h.
Constructor & Destructor Documentation
ThresholdQueueBase::ThresholdQueueBase (ulong elemSize, ulong queueLen, ulong maxThresh, ulong numChans = 1)
Definition at line 20 of file ThresholdQueueBase.cc.
References AllocateBuf(), maxThreshold, numChannels, queueLength, and Reset().
 :   elementSize(elemSize),
     queueLength(queueLen),
     maxThreshold(maxThresh),
     numChannels(numChans),
     chanOffset(0), baseOffset(0),
     base(0), mbs(0)
 {
     if (maxThreshold<1)
         maxThreshold = 1;
     if (maxThreshold>queueLength)
         queueLength = maxThreshold;
     Reset();
     bool useMBS = 1;
     AllocateBuf(queueLength, maxThreshold, numChannels, useMBS);
 }
ThresholdQueueBase::ThresholdQueueBase (ulong elemSize, const ThresholdQueueAttr & attr)
Definition at line 42 of file ThresholdQueueBase.cc.
References AllocateBuf(), ThresholdQueueAttr::baseOffset, baseOffset, ThresholdQueueAttr::chanOffset, chanOffset, elementSize, maxThreshold, numChannels, MirrorBufferSet::PageSize(), queueLength, Reset(), and ThresholdQueueAttr::useMBS.
 :   elementSize(elemSize),
     queueLength(attr.queueLength),
     maxThreshold(attr.maxThreshold),
     numChannels(attr.numChannels),
     chanOffset(0), baseOffset(0),
     base(0), mbs(0)
 {
     if (maxThreshold<1)
         maxThreshold = 1;
     if (maxThreshold>queueLength)
         queueLength = maxThreshold;
     Reset();
     bool useMBS = attr.useMBS;
     if (useMBS) {
         // there is no reason for an offset bigger than the page size
         baseOffset = attr.baseOffset % MirrorBufferSet::PageSize();
         baseOffset = baseOffset / elementSize;
         chanOffset = attr.chanOffset  / elementSize;
     }
     AllocateBuf(queueLength, maxThreshold, numChannels, useMBS);
 }
ThresholdQueueBase::~ThresholdQueueBase (void)
Definition at line 120 of file ThresholdQueueBase.cc.
References base, and mbs.
 {
     if (mbs) {
         delete mbs;
         mbs = 0;
     } else {
         free(base);
     }
     base = 0;
 }
Member Function Documentation
void ThresholdQueueBase::AllocateBuf (ulong queueLen, ulong maxThresh, ulong numChans, bool useMBS) protected
Definition at line 71 of file ThresholdQueueBase.cc.
References base, baseOffset, MirrorBufferSet::BufferSize(), channelStride, chanOffset, elementSize, maxThreshold, mbs, MINIMUM_ALIGNMENT, MirrorBufferSet::MirrorSize(), numChannels, queueLength, Reset(), and MirrorBufferSet::Supported().
Referenced by Grow(), and ThresholdQueueBase().
 {
     if (maxThresh<1)        maxThresh = 1;
     if (maxThresh>queueLen) queueLen = maxThresh;
     numChannels = numChans;
     if ( useMBS && MirrorBufferSet::Supported() ) {
         ulong bufSz = queueLen * elementSize;
         ulong mirSz = maxThresh-1 + baseOffset + (numChannels-1)*chanOffset;
         mirSz *= elementSize;
         mbs = new MirrorBufferSet(bufSz, mirSz, numChannels);
         // MirrorBufferSet may have just resized everything...
         queueLength  = mbs->BufferSize() / elementSize;
         maxThreshold = mbs->MirrorSize() / elementSize + 1;
         channelStride = queueLength + maxThreshold-1 + chanOffset;
         maxThreshold -= baseOffset + (numChannels-1)*chanOffset;
         base = (char*)((void*)(*mbs)) + baseOffset;
         // Corner case of queueLength == maxThreshold
         if (maxThreshold > queueLength) { maxThreshold = queueLength; }
     } else {
         queueLength = queueLen;
         maxThreshold = maxThresh;
         channelStride = queueLength + maxThreshold - 1;
         ulong mod = channelStride%MINIMUM_ALIGNMENT;
         if (mod != 0) {
             channelStride += MINIMUM_ALIGNMENT - mod;
         }
         base = malloc(channelStride * numChannels * elementSize);
     }
     Reset();
 }
ulong ThresholdQueueBase::ChannelStride (void) const inline
Definition at line 114 of file ThresholdQueueBase.h.
References channelStride.
Referenced by CPN::ThresholdQueue::UnlockedDequeueChannelStride(), and CPN::ThresholdQueue::UnlockedEnqueueChannelStride().
 { return channelStride; }
ThresholdQueueBase::ulong ThresholdQueueBase::Count (void) const
Definition at line 217 of file ThresholdQueueBase.cc.
References head, queueLength, and tail.
Referenced by Empty(), CPN::RemoteQueue::EnqueuePacket(), Freespace(), GetRawDequeuePtr(), CPN::ThresholdQueue::TQImpl::Grow(), Grow(), CPN::RemoteQueue::InternalCheckStatus(), CPN::ThresholdQueue::InternalEnqueue(), CPN::RemoteQueue::ReadBlockPacket(), CPN::RemoteQueue::SendDequeuePacket(), CPN::RemoteQueue::SendEnqueuePacket(), CPN::ThresholdQueue::UnlockedCount(), CPN::RemoteQueue::UnlockedCount(), and CPN::RemoteQueue::WriteBlockPacket().
 {
     register ulong count = (2*queueLength - head + tail);
     while (count>=queueLength) count -= queueLength;
     if (count) return count;
     return (head==tail) ? 0 : queueLength;
 }
void ThresholdQueueBase::Dequeue (ulong count)
Definition at line 205 of file ThresholdQueueBase.cc.
References elementsDequeued, head, and queueLength.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), Grow(), CPN::ThresholdQueue::InternalDequeue(), and CPN::ThresholdQueue::InternalEnqueue().
 {
     register ulong newHead = head+count;
     while (newHead>=2*queueLength) newHead -= 2*queueLength;
     head = newHead;
     elementsDequeued += count;
 }
ulong ThresholdQueueBase::ElementsDequeued (void) const inline
Definition at line 118 of file ThresholdQueueBase.h.
References elementsDequeued.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), Grow(), and CPN::ThresholdQueue::UnlockedNumDequeued().
 { return elementsDequeued; }
ulong ThresholdQueueBase::ElementsEnqueued (void) const inline
Definition at line 117 of file ThresholdQueueBase.h.
References elementsEnqueued.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), Grow(), and CPN::ThresholdQueue::UnlockedNumEnqueued().
 { return elementsEnqueued; }
bool ThresholdQueueBase::Empty (void) const inline
Definition at line 107 of file ThresholdQueueBase.h.
References Count().
Referenced by CPN::RemoteQueue::InternalCheckStatus(), CPN::ThresholdQueue::UnlockedEmpty(), and CPN::RemoteQueue::UnlockedEmpty().
 { return !Count(); }
void ThresholdQueueBase::Enqueue (ulong count)
Definition at line 162 of file ThresholdQueueBase.cc.
References base, channelStride, elementsEnqueued, elementSize, maxThreshold, mbs, numChannels, queueLength, and tail.
Referenced by Grow(), and CPN::ThresholdQueue::InternalEnqueue().
 {
     if (!mbs) { // the mbs maintains circularity
         // we must mirror by ourselves
         register ulong idx = tail;
         while (idx>=queueLength) idx -= queueLength;
         // elems to copy from queue area to mirror area
         register ulong countUp = 0;
         if (idx<maxThreshold-1) countUp = maxThreshold-1-idx;   // to mirror's lower edge
         if (idx+count<maxThreshold-1) countUp = count;
         // elems to copy from mirror area to queue area
         register ulong countDn = 0;
         if (idx+count>queueLength) countDn = idx+count-queueLength;
         if (countUp || countDn)
             for (ulong chan=0; chan<numChannels; chan++) {
                 char* chanBase = (char*)base + (chan*channelStride) * elementSize;
                 // move data in the queue (below the threshold) to the mirror area
                 char* dst = chanBase + (idx + queueLength) * elementSize;
                 char* src = chanBase + idx * elementSize;
                 memcpy(dst,src,countUp*elementSize);
                 // move data from the mirror area to the queue (below the threshold)
                 src = chanBase + queueLength * elementSize;
                 memcpy(chanBase,src,countDn*elementSize);
             }
     }
     // update the tail pointer
     register ulong newTail = tail+count;
     while (newTail>=2*queueLength) newTail -= 2*queueLength;
     tail = newTail;
     elementsEnqueued += count;
 }
ThresholdQueueBase::ulong ThresholdQueueBase::Freespace (void) const
Definition at line 229 of file ThresholdQueueBase.cc.
References Count(), and queueLength.
Referenced by CPN::RemoteQueue::EnqueuePacket(), Full(), GetRawEnqueuePtr(), CPN::RemoteQueue::InternalCheckStatus(), and CPN::ThresholdQueue::UnlockedFreespace().
 {
     return queueLength - Count();
 }
bool ThresholdQueueBase::Full (void) const inline
Definition at line 108 of file ThresholdQueueBase.h.
References Freespace().
Referenced by CPN::ThresholdQueue::UnlockedFull().
 { return !Freespace(); }
const void * ThresholdQueueBase::GetRawDequeuePtr (ulong dequeueThresh, ulong chan = 0) const
Definition at line 148 of file ThresholdQueueBase.cc.
References base, channelStride, Count(), elementSize, head, MaxThreshold(), and queueLength.
Referenced by ThresholdQueue< T >::GetDequeuePtr(), CPN::ThresholdQueue::TQImpl::Grow(), Grow(), CPN::ThresholdQueue::InternalEnqueue(), and CPN::ThresholdQueue::InternalGetRawDequeuePtr().
 {
     if (thresh>Count() || thresh>MaxThreshold()) return 0;
 //  if (chan>=numChannels) return 0;
 //  assert(chan<numChannels);
     register ulong idx = head;
     while (idx>=queueLength) idx -= queueLength;
     return (char*) base + (chan*channelStride + idx) * elementSize;
 }
void * ThresholdQueueBase::GetRawEnqueuePtr (ulong enqueueThresh, ulong chan = 0) const
Definition at line 134 of file ThresholdQueueBase.cc.
References base, channelStride, elementSize, Freespace(), MaxThreshold(), queueLength, and tail.
Referenced by ThresholdQueue< T >::GetEnqueuePtr(), Grow(), CPN::ThresholdQueue::InternalEnqueue(), and CPN::ThresholdQueue::InternalGetRawEnqueuePtr().
 {
     if (thresh>Freespace() || thresh>MaxThreshold()) return 0;
 //  if (chan>=numChannels) return 0;
 //  assert(chan<numChannels);
     register ulong idx = tail;
     while (idx>=queueLength) idx -= queueLength;
     return (char*) base + (chan*channelStride + idx) * elementSize;
 }
void ThresholdQueueBase::Grow (ulong queueLen, ulong maxThresh)
Definition at line 242 of file ThresholdQueueBase.cc.
References AllocateBuf(), Count(), Dequeue(), ElementsDequeued(), elementsDequeued, ElementsEnqueued(), elementsEnqueued, elementSize, Enqueue(), GetRawDequeuePtr(), GetRawEnqueuePtr(), MaxThreshold(), mbs, numChannels, and QueueLength().
 {
     fprintf(stderr, "ThresholdQueueBase::Grow(%lu,%lu)\n", queueLen, maxThresh);
     // handle the default parameter case
     if (!maxThresh) maxThresh = MaxThreshold();
     // ignore the do-nothing case
     if (queueLen <= QueueLength() && maxThresh <= MaxThreshold()) return;
     // we don't do any shrinking
     if (maxThresh <= MaxThreshold()) maxThresh = MaxThreshold();
     if (queueLen <= QueueLength()) queueLen = QueueLength();
     // keep our old info around
     ThresholdQueueBase  oldQueue(*this);    // just duplicate the pointers
     // allocate a new buffer (or MirrorBufferSet)
     AllocateBuf(queueLen,maxThresh,numChannels,mbs?1:0);
     // growth should not affect this member
     elementsDequeued = oldQueue.ElementsDequeued();
     // copy all in oldQueue to our new buffer with existing mechanisms
     ulong count;
     while ((count = oldQueue.Count()) != 0) {
         if (count>oldQueue.MaxThreshold())
             count = oldQueue.MaxThreshold();
         for (ulong chan=0; chan<numChannels; chan++) {
             const void* src = oldQueue.GetRawDequeuePtr(count,chan);
             void* dst = GetRawEnqueuePtr(count,chan);
             assert(src && dst);
             memcpy(dst,src,count*elementSize);
         }
         Enqueue(count);
         oldQueue.Dequeue(count);
     }
     // growth should not affect this member
     elementsEnqueued = oldQueue.ElementsEnqueued();
     // when oldQueue gets destructed, it will deallocate the old buffers
 }
ulong ThresholdQueueBase::MaxThreshold (void) const inline
Definition at line 111 of file ThresholdQueueBase.h.
References maxThreshold.
Referenced by CPN::RemoteQueue::EnqueuePacket(), GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::ThresholdQueue::TQImpl::Grow(), Grow(), CPN::RemoteQueue::GrowPacket(), CPN::ThresholdQueue::InternalEnqueue(), CPN::RemoteQueue::SendEnqueuePacket(), CPN::RemoteQueue::SendGrowPacket(), CPN::RemoteQueue::UnlockedGrow(), and CPN::ThresholdQueue::UnlockedMaxThreshold().
 { return maxThreshold; }
ulong ThresholdQueueBase::NumChannels (void) const inline
Definition at line 113 of file ThresholdQueueBase.h.
References numChannels.
Referenced by CPN::RemoteQueue::EnqueuePacket(), CPN::ThresholdQueue::InternalEnqueue(), CPN::RemoteQueue::SendEnqueuePacket(), and CPN::ThresholdQueue::UnlockedNumChannels().
 { return numChannels; }
ulong ThresholdQueueBase::QueueLength (void) const inline
Definition at line 110 of file ThresholdQueueBase.h.
References queueLength.
Referenced by CPN::RemoteQueue::EnqueuePacket(), Grow(), and CPN::ThresholdQueue::UnlockedQueueLength().
 { return queueLength; }
void ThresholdQueueBase::Reset (void)
Definition at line 108 of file ThresholdQueueBase.cc.
References elementsDequeued, elementsEnqueued, head, and tail.
Referenced by AllocateBuf(), CPN::ThresholdQueue::InternalReset(), CPN::RemoteQueue::ResetPacket(), and ThresholdQueueBase().
 {
     elementsEnqueued = 0;
     elementsDequeued = 0;
     head = 0;
     tail = 0;
 }
Member Data Documentation
void* ThresholdQueueBase::base protected
Definition at line 129 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), Enqueue(), GetRawDequeuePtr(), GetRawEnqueuePtr(), and ~ThresholdQueueBase().
ulong ThresholdQueueBase::baseOffset protected
Definition at line 127 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), and ThresholdQueueBase().
ulong ThresholdQueueBase::channelStride protected
Definition at line 126 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), ChannelStride(), Enqueue(), GetRawDequeuePtr(), and GetRawEnqueuePtr().
ulong ThresholdQueueBase::chanOffset protected
Definition at line 127 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), and ThresholdQueueBase().
ulong ThresholdQueueBase::elementsDequeued protected
Definition at line 128 of file ThresholdQueueBase.h.
Referenced by Dequeue(), ElementsDequeued(), Grow(), and Reset().
ulong ThresholdQueueBase::elementsEnqueued protected
Definition at line 128 of file ThresholdQueueBase.h.
Referenced by ElementsEnqueued(), Enqueue(), Grow(), and Reset().
ulong ThresholdQueueBase::elementSize protected
Definition at line 123 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), Enqueue(), GetRawDequeuePtr(), GetRawEnqueuePtr(), Grow(), and ThresholdQueueBase().
ulong ThresholdQueueBase::head protected
Definition at line 124 of file ThresholdQueueBase.h.
Referenced by Count(), Dequeue(), GetRawDequeuePtr(), CPN::ThresholdQueue::TQImpl::Grow(), and Reset().
ulong ThresholdQueueBase::maxThreshold protected
Definition at line 125 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), Enqueue(), MaxThreshold(), and ThresholdQueueBase().
MirrorBufferSet* ThresholdQueueBase::mbs protected
Definition at line 130 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), Enqueue(), Grow(), and ~ThresholdQueueBase().
ulong ThresholdQueueBase::numChannels protected
Definition at line 126 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), Enqueue(), Grow(), NumChannels(), and ThresholdQueueBase().
ulong ThresholdQueueBase::queueLength protected
Definition at line 125 of file ThresholdQueueBase.h.
Referenced by AllocateBuf(), Count(), Dequeue(), Enqueue(), Freespace(), GetRawDequeuePtr(), GetRawEnqueuePtr(), QueueLength(), and ThresholdQueueBase().
ulong ThresholdQueueBase::tail protected
Definition at line 124 of file ThresholdQueueBase.h.
Referenced by Count(), Enqueue(), GetRawEnqueuePtr(), CPN::ThresholdQueue::TQImpl::Grow(), and Reset().
The documentation for this class was generated from the following files:
lib/ThresholdQueueBase.h
lib/ThresholdQueueBase.cc