CPN: ErrnoException Class Reference
ErrnoException Class Reference
#include <ErrnoException.h>
Public Member Functions
ErrnoException () throw ()
ErrnoException (int err) throw ()
ErrnoException (const char *msg, int err) throw ()
virtual ~ErrnoException () throw ()
virtual const char * what () const throw ()
int Error () const
std::string GetStackTrace () const
Protected Attributes
std::string stacktrace
Private Member Functions
void Fill () throw ()
Private Attributes
int error
std::string errorstring
Detailed Description
A generic exception that encapsulates the errno value.
Note that this dynamically allocates memory so is unsutable for out of memory errors.
Definition at line 37 of file ErrnoException.h.
Constructor & Destructor Documentation
ErrnoException::ErrnoException () throw ()
Definition at line 31 of file ErrnoException.cc.
References errorstring, Fill(), and Exception::GetStackTrace().
     : Exception(3), error(errno)
 {
     Fill();
     errorstring += "\nBacktrace:\n" + GetStackTrace();
 }
ErrnoException::ErrnoException (int err) throw ()
Definition at line 38 of file ErrnoException.cc.
     : Exception(3), error(err)
 {
     Fill();
     errorstring += "\nBacktrace:\n" + GetStackTrace();
 }
ErrnoException::ErrnoException (const char * msg, int err) throw ()
Definition at line 45 of file ErrnoException.cc.
     : Exception(3), error(err)
 {
     Fill();
     errorstring += ": ";
     errorstring +=  msg;
     errorstring += "\nBacktrace:\n" + GetStackTrace();
 }
ErrnoException::~ErrnoException () throw () virtual
Definition at line 54 of file ErrnoException.cc.
{
 }
Member Function Documentation
int ErrnoException::Error (void) const inline
Definition at line 44 of file ErrnoException.h.
References error.
Referenced by CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::HandleError(), CPN::ConnectionServer::Poll(), CPN::RemoteContextDaemon::Client::Read(), and CPN::RemoteContextDaemon::Client::Send().
 { return error; }
void ErrnoException::Fill () throw () private
Definition at line 61 of file ErrnoException.cc.
References error, errorstring, and UNKNOWN_ERROR.
Referenced by ErrnoException().
{
     std::vector<char> errstr(256, '\0');
     do {
 #if defined(__APPLE__)
         // if __APPLE__ strerror_r is declared to return an int
         int err = strerror_r(error, &errstr[0], errstr.size());
         if (err == 0) {
             errorstring = &errstr[0];
             break;
         } else {
             if (errno == ERANGE) {
                 errstr.resize(2*errstr.size(), '\0');
             } else {
                 errorstring = UNKNOWN_ERROR;
                 break;
             }
         }
 #else
         char *str = strerror_r(error, &errstr[0], errstr.size());
         // Wierdness with different versions of strerror... From the man page:
         //
         //  The strerror() and strerror_r() functions return the appropriate
         //  error description string, or an "Unknown error nnn" message if the
         //  error number is unknown.
         //
         //  The XSI-compliant strerror_r() function returns 0 on success; on
         //  error, -1 is returned and errno is set to indicate the error.
         //
         // So str can be ether an error code OR a pointer to the error
         // string...  wierdness.
         if (str == (char*)-1) {
             if (errno == ERANGE) {
                 errstr.resize(2*errstr.size(), '\0');
             } else {
                 errorstring = UNKNOWN_ERROR;
                 break;
             }
         } else if (str == 0) {
             errorstring = &errstr[0];
             break;
         } else {
             errorstring = str;
             break;
         }
 #endif
     } while (true);
 }
std::string Exception::GetStackTrace () const inline inherited
Returns
the stack trace.
Definition at line 40 of file Exception.h.
References Exception::stacktrace.
Referenced by ErrnoException().
 { return stacktrace; }
const char * ErrnoException::what () const throw () virtual
Definition at line 57 of file ErrnoException.cc.
References errorstring.
Referenced by CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::HandleError(), CPN::ConnectionServer::Poll(), CPN::RemoteContextDaemon::Client::Read(), CPN::RemoteContextDaemon::Client::Send(), CPN::RemoteQueue::SendEndOfReadPacket(), and CPN::RemoteQueue::SendEndOfWritePacket().
{
     return errorstring.c_str();
 }
Member Data Documentation
int ErrnoException::error private
Definition at line 47 of file ErrnoException.h.
Referenced by Error(), and Fill().
std::string ErrnoException::errorstring private
Definition at line 48 of file ErrnoException.h.
Referenced by ErrnoException(), Fill(), and what().
std::string Exception::stacktrace protected inherited
Definition at line 42 of file Exception.h.
Referenced by Exception::GetStackTrace().
The documentation for this class was generated from the following files:
include/cpn/utils/ErrnoException.h
lib/utils/ErrnoException.cc