CPN: SocketAddress Class Reference
SocketAddress Class Reference
An abstraction of a socket address with convenience methods.
#include <SocketAddress.h>
Classes
union address_
Public Types
enum Type_t { IPV4, IPV6, LOCAL }
Public Member Functions
SocketAddress ()
SocketAddress (addrinfo *info)
SocketAddress (addrinfo *info, unsigned portnum)
SocketAddress (sockaddr *addr, socklen_t len)
~SocketAddress ()
std::string GetHostName (bool numerichost=true) const
std::string GetServName () const
unsigned GetServ () const
Type_t GetType () const
sockaddr * GetAddr ()
socklen_t & GetLen ()
sa_family_t & Family ()
sa_family_t Family () const
void SetFromSockName (int fd)
Fill this SocketAddress with data from this side of the connection represented by fd.
void SetFromPeerName (int fd)
Fill this SocketAddress with data from the other side of the connection represented by fd.
Static Public Member Functions
static SockAddrList CreateIPFromServ (const char *servname)
Return a list of valid socket addresses for the given service name All CreateIP functions create IP addresses.
static SockAddrList CreateIPFromServ (const std::string &servname)
static SockAddrList CreateIPFromHost (const char *hostname)
static SockAddrList CreateIPFromHost (const std::string &hostname)
static SockAddrList CreateIP (unsigned serv)
Return a list of valid socket address for the given service number or port number.
static SockAddrList CreateIP (const char *hostname, const char *servname)
static SockAddrList CreateIP (const std::string &hostname, const std::string &servname)
static SockAddrList CreateIP (const char *hostname, unsigned serv)
static SockAddrList CreateIP (const std::string &hostname, unsigned serv)
static SockAddrList CreateIP (const std::string &hostname)
Static Private Member Functions
static SockAddrList Lookup (const char *const hostname, const char *const port, int family, unsigned portnum)
Private Attributes
socklen_t length
union SocketAddress::address_ address
Detailed Description
An abstraction of a socket address with convenience methods.
Definition at line 42 of file SocketAddress.h.
Member Enumeration Documentation
enum SocketAddress::Type_t
Enumerator
IPV4
IPV6
LOCAL
Definition at line 45 of file SocketAddress.h.
                 {
         IPV4,
         IPV6,
         LOCAL
     };
Constructor & Destructor Documentation
SocketAddress::SocketAddress ()
Definition at line 33 of file SocketAddress.cc.
References address.
Referenced by Lookup().
     : length(0)
 {
     memset(&address, 0, sizeof(address));
 }
SocketAddress::SocketAddress (addrinfo * info)
Definition at line 174 of file SocketAddress.cc.
References address, and length.
{
     length = info->ai_addrlen;
     memcpy(&address, info->ai_addr, length);
 }
SocketAddress::SocketAddress (addrinfo * info, unsigned portnum)
Definition at line 179 of file SocketAddress.cc.
References address, Family(), SocketAddress::address_::in, SocketAddress::address_::in6, and length.
{
     length = info->ai_addrlen;
     memcpy(&address, info->ai_addr, length);
     uint16_t port = (uint16_t)portnum;
     port = htons(port);
     switch (Family()) {
     case AF_INET:
         address.in.sin_port = port;
         break;
     case AF_INET6:
         address.in6.sin6_port = port;
         break;
     default:
         break;
     }
 }
SocketAddress::SocketAddress (sockaddr * addr, socklen_t len)
Create a SocketAddress from the underlying sockaddr and length
Parameters
addr pointer tot he address structure
len the length of the address structure
Definition at line 196 of file SocketAddress.cc.
References address, and length.
{
     memcpy(&address, addr, len);
     length = len;
 }
SocketAddress::~SocketAddress () inline
Definition at line 94 of file SocketAddress.h.
 {}
Member Function Documentation
SockAddrList SocketAddress::CreateIP (unsigned serv) static
Return a list of valid socket address for the given service number or port number.
Definition at line 103 of file SocketAddress.cc.
References address, Family(), SocketAddress::address_::in, and length.
Referenced by CPN::ConnectionServer::ConnectWriter(), CPN::Kernel::Kernel(), and CPN::VariantCPNLoader::LoadContext().
{
     SocketAddress addr;
     addr.Family() = AF_INET;
     addr.address.in.sin_port = htons(serv);
     addr.address.in.sin_addr.s_addr = INADDR_ANY;
     addr.length = sizeof(sockaddr_in);
     SockAddrList list;
     list.push_back(addr);
     return list;
 }
SockAddrList SocketAddress::CreateIP (const char * hostname, const char * servname) static
Parameters
hostname The hostname to lookup
servname the service name to lookup, may be a number string for the port
Returns
a list of valid addresses to connect to the given host/port
Definition at line 114 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(hostname, servname, AF_UNSPEC, 0);
 }
SockAddrList SocketAddress::CreateIP (const std::string & hostname, const std::string & servname) static
Definition at line 118 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(hostname.c_str(), servname.c_str(), AF_UNSPEC, 0);
 }
SockAddrList SocketAddress::CreateIP (const char * hostname, unsigned serv) static
Parameters
hostname the hostname to lookup
serv the port number
Returns
a list of valid address to connect to the given host/port
Definition at line 122 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(hostname, 0, AF_UNSPEC, serv);
 }
SockAddrList SocketAddress::CreateIP (const std::string & hostname, unsigned serv) static
Definition at line 126 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(hostname.c_str(), 0, AF_UNSPEC, serv);
 }
SockAddrList SocketAddress::CreateIP (const std::string & hostname) static
Create socket addresses from hostname:port, [hostname]:port type strings as described in RFC 2732.
Parameters
hostname
Definition at line 130 of file SocketAddress.cc.
References Lookup().
{
     std::string host;
     std::string port;
     std::string::const_iterator it, e;
     e = hostname.end();
     it = hostname.begin();
     bool in_address = false;
     bool at_port = false;
     while (it != e) {
         if (in_address) {
             if (*it == ']') {
                 in_address = false;
             } else {
                 host.push_back(*it);
             }
         }
         if (at_port) {
             port.push_back(*it);
         } else {
             switch (*it) {
             case '[':
                 in_address = true;
                 break;
             case ':':
                 at_port = true;
                 break;
             default:
                 host.push_back(*it);
                 break;
             }
         }
         ++it;
     }
     const char *h = 0;
     const char *p = 0;
     if (!host.empty()) {
         h = host.c_str();
     }
     if (!port.empty()) {
         p = port.c_str();
     }
     return Lookup(h, p, AF_UNSPEC, 0);
 }
SockAddrList SocketAddress::CreateIPFromHost (const char * hostname) static
Definition at line 95 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(hostname, 0, AF_UNSPEC, 0);
 }
SockAddrList SocketAddress::CreateIPFromHost (const std::string & hostname) static
Definition at line 99 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(hostname.c_str(), 0, AF_UNSPEC, 0);
 }
SockAddrList SocketAddress::CreateIPFromServ (const char * servname) static
Return a list of valid socket addresses for the given service name All CreateIP functions create IP addresses.
Returns
a list of SocketAddresses
Definition at line 87 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(0, servname, AF_UNSPEC, 0);
 }
SockAddrList SocketAddress::CreateIPFromServ (const std::string & servname) static
Definition at line 91 of file SocketAddress.cc.
References Lookup().
{
     return Lookup(0, servname.c_str(), AF_UNSPEC, 0);
 }
sa_family_t& SocketAddress::Family () inline
Definition at line 115 of file SocketAddress.h.
References address, and SocketAddress::address_::storage.
Referenced by SocketHandle::Connect(), CreateIP(), GetServ(), GetType(), ServerSocketHandle::Listen(), and SocketAddress().
 { return address.storage.ss_family; }
sa_family_t SocketAddress::Family () const inline
Definition at line 116 of file SocketAddress.h.
References address, and SocketAddress::address_::storage.
 { return address.storage.ss_family; }
sockaddr* SocketAddress::GetAddr () inline
Definition at line 113 of file SocketAddress.h.
References SocketAddress::address_::addr, and address.
Referenced by ServerSocketHandle::Accept(), SocketHandle::Connect(), ServerSocketHandle::Listen(), SetFromPeerName(), and SetFromSockName().
 { return &address.addr; }
std::string SocketAddress::GetHostName (bool numerichost = true) const
Parameters
numerichost true to force no resolution of host names and just return the number
Returns
a string representation of the host name
Definition at line 201 of file SocketAddress.cc.
References SocketAddress::address_::addr, address, and length.
Referenced by CPN::RemoteContextDaemon::Client::Client(), CPN::Kernel::Kernel(), and CPN::RemoteContextDaemon::Run().
{
     std::vector<char> hostname(NI_MAXHOST, '\0');
     bool loop = true;
     std::ostringstream oss;
     while (loop) {
         int flags = NI_NUMERICSERV;
         if (numerichost) { flags |= NI_NUMERICHOST; }
         int lookupstatus = getnameinfo(&address.addr, length,
                     &hostname[0], hostname.size(),
                     0, 0,
                     flags);
         switch (lookupstatus) {
         case 0:
             oss << &hostname[0];
             loop = false;
             break;
         case EAI_AGAIN:
             break;
 #if !defined(__APPLE__)
         case EAI_OVERFLOW:
             hostname.resize(hostname.size()*2, '\0');
             break;
 #endif
         case EAI_BADFLAGS:
         case EAI_FAIL:
         case EAI_FAMILY:
         case EAI_MEMORY:
         case EAI_NONAME:
         case EAI_SYSTEM:
         default:
             throw ErrnoException(gai_strerror(lookupstatus), lookupstatus);
         }
     }
     return oss.str();
 }
socklen_t& SocketAddress::GetLen () inline
Definition at line 114 of file SocketAddress.h.
References length.
Referenced by ServerSocketHandle::Accept(), SocketHandle::Connect(), ServerSocketHandle::Listen(), SetFromPeerName(), and SetFromSockName().
 { return length; }
unsigned SocketAddress::GetServ () const
Returns
the service (port) number
Definition at line 271 of file SocketAddress.cc.
References address, Family(), SocketAddress::address_::in, and SocketAddress::address_::in6.
{
     uint16_t retval = 0;
     switch (Family()) {
     case AF_INET:
         retval = address.in.sin_port;
         break;
     case AF_INET6:
         retval = address.in6.sin6_port;
         break;
     default:
         break;
     }
     return (unsigned)ntohs(retval);
 }
std::string SocketAddress::GetServName () const
Returns
the service (port) name or number as a string.
Definition at line 237 of file SocketAddress.cc.
References SocketAddress::address_::addr, address, and length.
Referenced by CPN::RemoteContextDaemon::Client::Client(), CPN::Kernel::Kernel(), and CPN::RemoteContextDaemon::Run().
{
     std::vector<char> servname(NI_MAXSERV, '\0');
     bool loop = true;
     std::ostringstream oss;
     while (loop) {
         int lookupstatus = getnameinfo(&address.addr, length,
                     0, 0,
                     &servname[0], servname.size(),
                     NI_NUMERICSERV);
         switch (lookupstatus) {
         case 0:
             oss << &servname[0];
             loop = false;
             break;
         case EAI_AGAIN:
             break;
 #if !defined(__APPLE__)
         case EAI_OVERFLOW:
             servname.resize(servname.size()*2, '\0');
             break;
 #endif
         case EAI_BADFLAGS:
         case EAI_FAIL:
         case EAI_FAMILY:
         case EAI_MEMORY:
         case EAI_NONAME:
         case EAI_SYSTEM:
         default:
             throw ErrnoException(gai_strerror(lookupstatus), lookupstatus);
         }
     }
     return oss.str();
 }
SocketAddress::Type_t SocketAddress::GetType () const
Definition at line 286 of file SocketAddress.cc.
References ASSERT, Family(), IPV4, IPV6, and LOCAL.
{
     Type_t type;
     switch (Family()) {
     case AF_INET:
         type = IPV4;
         break;
     case AF_INET6:
         type = IPV6;
         break;
     case AF_UNIX:
         type = LOCAL;
         break;
     default:
         ASSERT(false, "Unknown address type.");
     }
     return type;
 }
SockAddrList SocketAddress::Lookup (const char *const hostname, const char *const port, int family, unsigned portnum) static private
Definition at line 39 of file SocketAddress.cc.
References SocketAddress().
Referenced by CreateIP(), CreateIPFromHost(), and CreateIPFromServ().
{
     addrinfo hints = {0};
     // Get only supported types.
     hints.ai_flags = AI_ADDRCONFIG;
     hints.ai_family = family;
     hints.ai_socktype = SOCK_STREAM;
     if (0 == hostname || *hostname == '\0') {
         hints.ai_flags |= AI_PASSIVE;
     }
     addrinfo *res = 0;
     int lookupstatus = 0;
     do {
         lookupstatus = getaddrinfo(hostname, port, &hints, &res);
         switch (lookupstatus) {
             case EAI_AGAIN:
                 // try again
             case EAI_MEMORY:
                 // our of memory, try again?
             case 0:
                 // Success.
                 break;
             case EAI_ADDRFAMILY:
             case EAI_BADFLAGS:
             case EAI_FAIL:
             case EAI_FAMILY:
             case EAI_NODATA:
             case EAI_NONAME:
             case EAI_SERVICE:
             case EAI_SOCKTYPE:
             case EAI_SYSTEM:
             default:
                 throw ErrnoException(gai_strerror(lookupstatus), lookupstatus);
         }
     } while (lookupstatus != 0);
     SockAddrList results;
     for (addrinfo *rp = res; rp != 0; rp = rp->ai_next) {
         if (port) {
             results.push_back(SocketAddress(rp));
         } else {
             results.push_back(SocketAddress(rp, portnum));
         }
     }
     freeaddrinfo(res);
     return results;
 }
void SocketAddress::SetFromPeerName (int fd)
Fill this SocketAddress with data from the other side of the connection represented by fd.
Parameters
fd the socket to use
Definition at line 311 of file SocketAddress.cc.
References GetAddr(), and GetLen().
Referenced by CPN::RemoteContextDaemon::Client::Client().
{
     GetLen() = sizeof(sockaddr_storage);
     if (getpeername(fd, GetAddr(), &GetLen()) != 0) {
         throw ErrnoException();
     }
 }
void SocketAddress::SetFromSockName (int fd)
Fill this SocketAddress with data from this side of the connection represented by fd.
Parameters
fd the socket to use
Definition at line 304 of file SocketAddress.cc.
References GetAddr(), and GetLen().
Referenced by CPN::ConnectionServer::GetAddress(), and CPN::RemoteContextDaemon::Run().
{
     GetLen() = sizeof(sockaddr_storage);
     if (getsockname(fd, GetAddr(), &GetLen()) != 0) {
         throw ErrnoException();
     }
 }
Member Data Documentation
union SocketAddress::address_ SocketAddress::address private
Referenced by CreateIP(), Family(), GetAddr(), GetHostName(), GetServ(), GetServName(), and SocketAddress().
socklen_t SocketAddress::length private
Definition at line 135 of file SocketAddress.h.
Referenced by CreateIP(), GetHostName(), GetLen(), GetServName(), and SocketAddress().
The documentation for this class was generated from the following files:
include/cpn/io/SocketAddress.h
lib/io/SocketAddress.cc