CPN: CPN::PacketEncoder Class Reference
CPN::PacketEncoder Class Reference abstract
#include <PacketEncoder.h>
Public Member Functions
PacketEncoder ()
virtual ~PacketEncoder ()
template<typename Queue_t >
void SendEnqueue (const Packet &packet, Queue_t &queue)
void SendPacket (const Packet &packet)
void SendPacket (const Packet &packet, void *data)
Protected Member Functions
virtual void WriteBytes (const iovec *iov, unsigned iovcnt)=0
Detailed Description
Take the various message types that can be sent over the wire and encode them into byte representation.
Definition at line 38 of file PacketEncoder.h.
Constructor & Destructor Documentation
CPN::PacketEncoder::PacketEncoder ()
Definition at line 28 of file PacketEncoder.cc.
 {}
CPN::PacketEncoder::~PacketEncoder () virtual
Definition at line 30 of file PacketEncoder.cc.
 {}
Member Function Documentation
template<typename Queue_t > void CPN::PacketEncoder::SendEnqueue (const Packet & packet, Queue_t & queue) inline
Definition at line 44 of file PacketEncoder.h.
References ASSERT, CPN::Packet::Count(), CPN::Packet::header, CPN::PACKET_ENQUEUE, and CPN::Packet::Type().
{
             ASSERT(packet.Type() == PACKET_ENQUEUE);
             std::vector<iovec> iovs;
             // Must use const_cast here because iovec.iov_base isn't const... :(
             iovec header = { const_cast<PacketHeader*>(&packet.header), sizeof(packet.header) };
             iovs.push_back(header);
             for (unsigned i = 0; i < queue.NumChannels(); ++i) {
                 iovec iov;
                 iov.iov_base = const_cast<void*>(queue.GetRawDequeuePtr(packet.Count(), i));
                 ASSERT(iov.iov_base);
                 iov.iov_len = packet.Count();
                 iovs.push_back(iov);
             }
             WriteBytes(&iovs[0], iovs.size());
             queue.Dequeue(packet.Count());
         }
void CPN::PacketEncoder::SendPacket (const Packet & packet)
Definition at line 32 of file PacketEncoder.cc.
References CPN::Packet::header, and WriteBytes().
Referenced by CPN::RemoteQueue::SendD4RTagPacket(), CPN::RemoteQueue::SendDequeuePacket(), CPN::RemoteQueue::SendEndOfReadPacket(), CPN::RemoteQueue::SendEndOfWritePacket(), CPN::RemoteQueue::SendFlushPacket(), CPN::RemoteQueue::SendGrowPacket(), CPN::RemoteQueue::SendReadBlockPacket(), CPN::RemoteQueue::SendResetPacket(), and CPN::RemoteQueue::SendWriteBlockPacket().
{
         iovec iov;
         iov.iov_base = const_cast<PacketHeader*>(&packet.header);
         iov.iov_len = sizeof(packet.header);
         WriteBytes(&iov, 1);
     }
void CPN::PacketEncoder::SendPacket (const Packet & packet, void * data)
Definition at line 39 of file PacketEncoder.cc.
References ASSERT, CPN::Packet::DataLength(), CPN::Packet::header, and WriteBytes().
{
         ASSERT(data);
         iovec iov[2];
         iov[0].iov_base = const_cast<PacketHeader*>(&packet.header);
         iov[0].iov_len = sizeof(packet.header);
         iov[1].iov_base = data;
         iov[1].iov_len = packet.DataLength();
         WriteBytes(&iov[0], 2);
     }
virtual void CPN::PacketEncoder::WriteBytes (const iovec * iov, unsigned iovcnt) protected pure virtual
Implemented in CPN::RemoteQueue.
Referenced by SendPacket().
The documentation for this class was generated from the following files:
lib/PacketEncoder.h
lib/PacketEncoder.cc