CPN: CPN::ThresholdQueue Class Reference
CPN::ThresholdQueue Class Reference
A version of the ThresholdQueue that provides the CPN Queue interface This queue implementation creates a memory mapped object which has as a minimum size the machine page size. So there is an effective minimum queue size. Any queue size less than the page size will be expanded to the page size.
#include <CPNThresholdQueue.h>
Classes
class TQImpl
Public Member Functions
ThresholdQueue (KernelBase *k, const SimpleQueueAttr &attr, bool usembs)
ThresholdQueue (KernelBase *k, const SimpleQueueAttr &attr, unsigned length, bool usembs)
~ThresholdQueue ()
const void * GetRawDequeuePtr (unsigned thresh, unsigned chan)
void Dequeue (unsigned count)
bool RawDequeue (void *data, unsigned count, unsigned numChans, unsigned chanStride)
bool RawDequeue (void *data, unsigned count)
void * GetRawEnqueuePtr (unsigned thresh, unsigned chan)
void Enqueue (unsigned count)
void RawEnqueue (const void *data, unsigned count, unsigned numChans, unsigned chanStride)
void RawEnqueue (const void *data, unsigned count)
void Reset ()
void Flush ()
bool Flushed () const
unsigned NumChannels () const
unsigned Count () const
bool Empty () const
unsigned Freespace () const
bool Full () const
unsigned MaxThreshold () const
unsigned QueueLength () const
unsigned EnqueueChannelStride () const
unsigned DequeueChannelStride () const
void Grow (unsigned queueLen, unsigned maxThresh)
Key_t GetWriterKey () const
Key_t GetReaderKey () const
const std::string & GetDatatype () const
void ShutdownReader ()
Called by the QueueReader when no more data will be read.
void ShutdownWriter ()
Called by the QueueWriter when no more data will be written.
void NotifyTerminate ()
Used to tell any waiting threads that the network is terminating.
void Lock () const
void Unlock () const
unsigned ReadRequest ()
For unit tests.
unsigned WriteRequest ()
For unit tests.
bool IsReaderShutdown ()
bool IsWriterShutdown ()
virtual void LogState ()
For debugging ONLY!! Otherwise non deterministic output.
unsigned NumEnqueued () const
unsigned NumDequeued () const
void SetReaderNode (shared_ptr< Node > n)
void SetWriterNode (shared_ptr< Node > n)
void SignalReaderTagChanged ()
void SignalWriterTagChanged ()
Protected Member Functions
virtual void * InternalGetRawEnqueuePtr (unsigned thresh, unsigned chan)
virtual void InternalEnqueue (unsigned count)
virtual const void * InternalGetRawDequeuePtr (unsigned thresh, unsigned chan)
virtual void InternalDequeue (unsigned count)
virtual void InternalReset ()
virtual unsigned UnlockedNumChannels () const
virtual unsigned UnlockedMaxThreshold () const
virtual unsigned UnlockedQueueLength () const
virtual unsigned UnlockedFreespace () const
virtual bool UnlockedFull () const
virtual unsigned UnlockedCount () const
virtual bool UnlockedEmpty () const
virtual unsigned UnlockedEnqueueChannelStride () const
virtual unsigned UnlockedDequeueChannelStride () const
unsigned UnlockedNumEnqueued () const
unsigned UnlockedNumDequeued () const
virtual void UnlockedGrow (unsigned queueLen, unsigned maxThresh)
virtual void WaitForData ()
virtual bool ReadBlocked ()
void NotifyData ()
virtual void WaitForFreespace ()
virtual bool WriteBlocked ()
void NotifyFreespace ()
virtual void Wait ()
virtual void Signal ()
virtual void Detect ()
virtual void InternalFlush ()
virtual void UnlockedShutdownReader ()
virtual void UnlockedShutdownWriter ()
void ReadBlock ()
void WriteBlock (unsigned qsize)
virtual void UnlockedSignalReaderTagChanged ()
virtual void UnlockedSignalWriterTagChanged ()
Protected Attributes
TQImpl * queue
TQImpl * oldqueue
bool enqueueUseOld
bool dequeueUseOld
const Key_t readerkey
const Key_t writerkey
bool readshutdown
bool writeshutdown
unsigned prepad
unsigned postpad
unsigned readrequest
unsigned writerequest
unsigned enqueuethresh
unsigned dequeuethresh
bool indequeue
bool inenqueue
bool flushed
KernelBase * kernel
bool useD4R
Logger logger
PthreadMutex lock
PthreadCondition cond
std::string datatype
shared_ptr< Node > reader
shared_ptr< Node > writer
bool readtagchanged
bool writetagchanged
bool incomm
Detailed Description
A version of the ThresholdQueue that provides the CPN Queue interface This queue implementation creates a memory mapped object which has as a minimum size the machine page size. So there is an effective minimum queue size. Any queue size less than the page size will be expanded to the page size.
See Also
QueueBase and ThresholdQueueBase
Definition at line 45 of file CPNThresholdQueue.h.
Constructor & Destructor Documentation
ThresholdQueue< T >::ThresholdQueue (KernelBase * k, const SimpleQueueAttr & attr, bool usembs)
Definition at line 32 of file CPNThresholdQueue.cc.
References CPN::SimpleQueueAttr::GetLength(), CPN::SimpleQueueAttr::GetMaxThreshold(), CPN::SimpleQueueAttr::GetNumChannels(), and queue.
         : QueueBase(k, attr), queue(0), oldqueue(0), enqueueUseOld(false), dequeueUseOld(false)
     {
         ThresholdQueueAttr qattr(attr.GetLength(), attr.GetMaxThreshold(),
                 attr.GetNumChannels(), usembs);
         queue = new TQImpl(qattr);
     }
ThresholdQueue< T >::ThresholdQueue (KernelBase * k, const SimpleQueueAttr & attr, unsigned length, bool usembs)
Definition at line 40 of file CPNThresholdQueue.cc.
References CPN::SimpleQueueAttr::GetMaxThreshold(), CPN::SimpleQueueAttr::GetNumChannels(), and queue.
         : QueueBase(k, attr), queue(0), oldqueue(0), enqueueUseOld(false), dequeueUseOld(false)
     {
         ThresholdQueueAttr qattr(length, attr.GetMaxThreshold(),
                 attr.GetNumChannels(), usembs);
         queue = new TQImpl(qattr);
     }
ThresholdQueue< T >::~ThresholdQueue ()
Definition at line 50 of file CPNThresholdQueue.cc.
References oldqueue, and queue.
{
         delete queue;
         queue = 0;
         delete oldqueue;
         oldqueue = 0;
     }
Member Function Documentation
unsigned CPN::QueueBase::Count () const inherited
Returns
the number of bytes in the queue.
Definition at line 205 of file QueueBase.cc.
References CPN::QueueBase::UnlockedCount().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedCount();
     }
void CPN::QueueBase::Dequeue (unsigned count) inherited
This function is used to remove elements from the queue. count elements will be removed from the queue when this function is called.
Parameters
count the number of bytes to remove from the queue
Definition at line 92 of file QueueBase.cc.
References CPN::QueueBase::dequeuethresh, CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::indequeue, CPN::QueueBase::InternalDequeue(), CPN::QueueBase::NotifyFreespace(), CPN::QueueBase::readerkey, and CPN::QueueBase::readshutdown.
Referenced by CPN::QueueBase::RawDequeue().
{
         if (!GetRawDequeuePtr(count, 0)) { throw BrokenQueueException(readerkey); }
         AutoLock<QueueBase> al(*this);
         dequeuethresh = 0;
         indequeue = false;
         if (readshutdown) { throw BrokenQueueException(readerkey); }
         InternalDequeue(count);
         NotifyFreespace();
     }
unsigned CPN::QueueBase::DequeueChannelStride () const inherited
Returns
The current dequeue channel stride. This value is only guaranteed to be consistent inbetween a call to GetDequeuePtr and Dequeue.
Definition at line 240 of file QueueBase.cc.
References CPN::QueueBase::UnlockedDequeueChannelStride().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedDequeueChannelStride();
     }
void CPN::QueueBase::Detect () protected virtual inherited
Called by the D4R algorithm when it has detected an artificial deadlock and this queue should be changed.
Implements D4R::QueueBase.
Definition at line 373 of file QueueBase.cc.
References CPN::KernelBase::CalculateGrowSize(), Logger::Debug(), CPN::QueueBase::kernel, CPN::QueueBase::logger, CPN::QueueBase::UnlockedCount(), CPN::QueueBase::UnlockedGrow(), CPN::QueueBase::UnlockedMaxThreshold(), CPN::QueueBase::UnlockedQueueLength(), and CPN::QueueBase::writerequest.
{
         unsigned size = kernel->CalculateGrowSize(UnlockedCount(), writerequest);
         logger.Debug("Detect: Grow(%u, %u)", size, writerequest);
         UnlockedGrow(size, writerequest);
         logger.Debug("New size: (%u, %u)", UnlockedQueueLength(), UnlockedMaxThreshold());
     }
bool CPN::QueueBase::Empty () const inherited
Returns
true if the queue is empty
Definition at line 210 of file QueueBase.cc.
References CPN::QueueBase::UnlockedEmpty().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedEmpty();
     }
void CPN::QueueBase::Enqueue (unsigned count) inherited
This function is used to release the buffer obtained with GetRawEnqueuePtr. The count specifies the number of entries that we want to be placed in the buffer.
Note
A call to this function without an accompanying call to GetRawEnqueuePtr is undefined.
Parameters
count the number of bytes to be placed in the buffer
Invariant
count <= thresh from GetRawEnqueuePtr
Definition at line 160 of file QueueBase.cc.
References CPN::QueueBase::enqueuethresh, CPN::QueueBase::inenqueue, CPN::QueueBase::InternalEnqueue(), CPN::QueueBase::NotifyData(), CPN::QueueBase::writerkey, and CPN::QueueBase::writeshutdown.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), and CPN::QueueBase::RawEnqueue().
{
         AutoLock<QueueBase> al(*this);
         enqueuethresh = 0;
         inenqueue = false;
         if (writeshutdown) { throw BrokenQueueException(writerkey); }
         InternalEnqueue(count);
         NotifyData();
     }
unsigned CPN::QueueBase::EnqueueChannelStride () const inherited
Returns
The current enqueue channel stride. This value is only guaranteed to be consistent inbetween a call to GetEnqueuePtr and Enqueue.
Definition at line 235 of file QueueBase.cc.
References CPN::QueueBase::UnlockedEnqueueChannelStride().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedEnqueueChannelStride();
     }
void CPN::QueueBase::Flush () inherited
Definition at line 186 of file QueueBase.cc.
References CPN::QueueBase::InternalFlush().
{
         AutoLock<const QueueBase> al(*this);
         InternalFlush();
     }
bool CPN::QueueBase::Flushed () const inherited
Definition at line 191 of file QueueBase.cc.
References CPN::QueueBase::flushed.
{
         AutoLock<const QueueBase> al(*this);
         return flushed;
     }
unsigned CPN::QueueBase::Freespace () const inherited
Returns
the number of bytes we can add to the queue without blocking.
Definition at line 215 of file QueueBase.cc.
References CPN::QueueBase::UnlockedFreespace().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedFreespace();
     }
bool CPN::QueueBase::Full () const inherited
Returns
true if the queue is full, false otherwise
Definition at line 220 of file QueueBase.cc.
References CPN::QueueBase::UnlockedFull().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedFull();
     }
const std::string& CPN::QueueBase::GetDatatype () const inline inherited
Returns
the datatype name associated with this queue
Definition at line 213 of file QueueBase.h.
 { return datatype; }
const void * CPN::QueueBase::GetRawDequeuePtr (unsigned thresh, unsigned chan) inherited
Get a pointer to a buffer containing elements.
Note
access to the memory locations pointed to by the returned pointer after Dequeue has been called is undefined.
Parameters
thresh the number of bytes to get
chan the channel to use
Returns
A void* to a block of memory containing thresh bytes or 0 if there are not thresh bytes available.
Definition at line 63 of file QueueBase.cc.
References ASSERT, CPN::KernelBase::CheckTerminated(), CPN::QueueBase::dequeuethresh, CPN::QueueBase::flushed, CPN::KernelBase::GrowQueueMaxThreshold(), CPN::QueueBase::indequeue, CPN::QueueBase::InternalGetRawDequeuePtr(), CPN::QueueBase::kernel, CPN::QueueBase::readerkey, CPN::QueueBase::readrequest, CPN::QueueBase::readshutdown, CPN::QueueBase::Signal(), CPN::QueueBase::UnlockedGrow(), CPN::QueueBase::UnlockedMaxThreshold(), CPN::QueueBase::WaitForData(), CPN::QueueBase::WriteBlocked(), CPN::QueueBase::writerequest, and CPN::QueueBase::writeshutdown.
Referenced by CPN::QueueBase::Dequeue(), and CPN::QueueBase::RawDequeue().
{
         kernel->CheckTerminated();
         AutoLock<QueueBase> al(*this);
         if (indequeue) { ASSERT(dequeuethresh >= thresh); }
         else { dequeuethresh = thresh; }
         while (true) {
             const void *ptr = InternalGetRawDequeuePtr(thresh, chan);
             if (ptr ||
                     (writeshutdown && !(thresh > UnlockedMaxThreshold() && kernel->GrowQueueMaxThreshold()))
                     || flushed) {
                 if (ptr) { indequeue = true; }
                 return ptr;
             }
             if (readshutdown) { throw BrokenQueueException(readerkey); }
             if (thresh > UnlockedMaxThreshold() && kernel->GrowQueueMaxThreshold()) {
                 //printf("Grow(%u, %u)\n", 2*thresh, thresh);
                 UnlockedGrow(2*thresh, thresh);
                 Signal();
             } else if (WriteBlocked() && kernel->GrowQueueMaxThreshold()) {
                 UnlockedGrow(writerequest + thresh, thresh);
                 Signal();
             } else {
                 readrequest = thresh;
                 WaitForData();
                 readrequest = 0;
             }
         }
     }
void * CPN::QueueBase::GetRawEnqueuePtr (unsigned thresh, unsigned chan) inherited
Return a pointer to a buffer of memory that contains thresh entries that we can write into.
Note
A call to this function without an accompanying call to Enqueue is undefined.
An access to the memory locations defined by the return value is undefined after a call to Enqueue.
Parameters
thresh the number bytes we need in the returned buffer.
chan the channel to use
Returns
void* to the memory buffer, 0 if not enough space available
Definition at line 121 of file QueueBase.cc.
References ASSERT, CPN::KernelBase::CheckTerminated(), CPN::QueueBase::enqueuethresh, CPN::QueueBase::flushed, CPN::KernelBase::GrowQueueMaxThreshold(), CPN::QueueBase::inenqueue, CPN::QueueBase::InternalGetRawEnqueuePtr(), CPN::QueueBase::kernel, CPN::QueueBase::ReadBlocked(), CPN::QueueBase::readrequest, CPN::QueueBase::readshutdown, CPN::QueueBase::Signal(), CPN::QueueBase::UnlockedGrow(), CPN::QueueBase::UnlockedMaxThreshold(), CPN::QueueBase::useD4R, CPN::QueueBase::Wait(), CPN::QueueBase::WaitForFreespace(), D4R::QueueBase::WriteBlock(), CPN::QueueBase::writerequest, CPN::QueueBase::writerkey, and CPN::QueueBase::writeshutdown.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), and CPN::QueueBase::RawEnqueue().
{
         kernel->CheckTerminated();
         AutoLock<QueueBase> al(*this);
         // Only the enqueuer may call flush and reset will clear all state as if we
         // had not done anything yet, so block here
         while (flushed) {
             if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
             if (useD4R) {
                 WriteBlock(-1);
             } else {
                 Wait();
             }
         }
         if (inenqueue) { ASSERT(enqueuethresh >= thresh); }
         else { enqueuethresh = thresh; }
         bool grown = false;
         while (true) {
             void *ptr = InternalGetRawEnqueuePtr(thresh, chan);
             if (ptr) {
                 inenqueue = true;
                 return ptr;
             }
             if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
             if (thresh > UnlockedMaxThreshold() && kernel->GrowQueueMaxThreshold()) {
                 //printf("Grow(%u, %u)\n", 2*thresh, thresh);
                 UnlockedGrow(2*thresh, thresh);
                 Signal();
             } else if (!grown && ReadBlocked() && kernel->GrowQueueMaxThreshold()) {
                 UnlockedGrow(readrequest + thresh, thresh);
                 Signal();
                 grown = true;
             } else {
                 writerequest = thresh;
                 WaitForFreespace();
                 writerequest = 0;
             }
         }
     }
Key_t CPN::QueueBase::GetReaderKey () const inline inherited
Returns
the reader key associated with this queue
Definition at line 211 of file QueueBase.h.
 { return readerkey; }
Key_t CPN::QueueBase::GetWriterKey () const inline inherited
Returns
the writer key associated with this queue
Definition at line 209 of file QueueBase.h.
 { return writerkey; }
void CPN::QueueBase::Grow (unsigned queueLen, unsigned maxThresh) inherited
Ensure that this queue has at least queueLen bytes of space and can support at least maxThresh as the maxThreshold the new queue length will be max(queueLen, QueueLength()) and the new max threshold will be max(maxThresh, MaxThreshold())
Note
that the caller must guarantee that both an enqueue and dequeue are not both outstanding. Otherwise this will fail.
Parameters
queueLen the next queue length
maxThresh the next max threshold
Definition at line 245 of file QueueBase.cc.
References CPN::QueueBase::UnlockedGrow().
{
         AutoLock<QueueBase> al(*this);
         UnlockedGrow(queueLen, maxThresh);
     }
void ThresholdQueue< T >::InternalDequeue (unsigned count) protected virtual
Implements CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 140 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::Dequeue(), dequeueUseOld, oldqueue, and queue.
Referenced by CPN::RemoteQueue::InternalDequeue(), and CPN::RemoteQueue::SendEnqueuePacket().
{
         if (dequeueUseOld) {
             dequeueUseOld = false;
             delete oldqueue;
             oldqueue = 0;
         }
         queue->Dequeue(count);
     }
void ThresholdQueue< T >::InternalEnqueue (unsigned count) protected virtual
Implements CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 69 of file CPNThresholdQueue.cc.
References ASSERT, ThresholdQueueBase::Count(), ThresholdQueueBase::Dequeue(), ThresholdQueueBase::Enqueue(), enqueueUseOld, ThresholdQueueBase::GetRawDequeuePtr(), ThresholdQueueBase::GetRawEnqueuePtr(), ThresholdQueueBase::MaxThreshold(), ThresholdQueueBase::NumChannels(), oldqueue, and queue.
Referenced by CPN::RemoteQueue::EnqueuePacket(), and CPN::RemoteQueue::InternalEnqueue().
{
         if (enqueueUseOld) {
             oldqueue->Dequeue(oldqueue->Count());
             oldqueue->Enqueue(count);
             unsigned count;
             while ( (count = oldqueue->Count()) != 0 ) {
                 if (count > oldqueue->MaxThreshold()) {
                     count = oldqueue->MaxThreshold();
                 }
                 for (unsigned chan = 0; chan < queue->NumChannels(); chan++) {
                     const void* src = oldqueue->GetRawDequeuePtr(count, chan);
                     void* dst = queue->GetRawEnqueuePtr(count, chan);
                     ASSERT(src && dst);
                     memcpy(dst,src,count);
                 }
                 queue->Enqueue(count);
                 oldqueue->Dequeue(count);
             }
             enqueueUseOld = false;
             delete oldqueue;
             oldqueue = 0;
         } else {
             queue->Enqueue(count);
         }
     }
void CPN::QueueBase::InternalFlush () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 265 of file QueueBase.cc.
References PthreadCondition::Broadcast(), CPN::QueueBase::cond, CPN::QueueBase::flushed, CPN::QueueBase::InternalEnqueue(), CPN::QueueBase::InternalGetRawEnqueuePtr(), CPN::QueueBase::postpad, CPN::QueueBase::readshutdown, CPN::QueueBase::UnlockedEnqueueChannelStride(), CPN::QueueBase::UnlockedNumChannels(), CPN::QueueBase::WaitForFreespace(), CPN::QueueBase::writerequest, CPN::QueueBase::writerkey, and CPN::QueueBase::writeshutdown.
Referenced by CPN::QueueBase::Flush(), and CPN::RemoteQueue::InternalFlush().
{
         if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
         if (postpad > 0) {
             while (true) {
                 void *ptr = InternalGetRawEnqueuePtr(postpad, 0);
                 if (ptr) {
                     unsigned num_chans = UnlockedNumChannels();
                     unsigned chanstride = UnlockedEnqueueChannelStride();
                     for (unsigned chan = 0; chan < num_chans; ++chan) {
                         memset((char*)ptr + chanstride*chan, 0, postpad);
                     }
                     InternalEnqueue(postpad);
                 } else {
                     if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
                     writerequest = postpad;
                     WaitForFreespace();
                     writerequest = 0;
                 }
             }
         }
         flushed = true;
         cond.Broadcast();
     }
const void * ThresholdQueue< T >::InternalGetRawDequeuePtr (unsigned thresh, unsigned chan) protected virtual
Implements CPN::QueueBase.
Definition at line 126 of file CPNThresholdQueue.cc.
References ASSERT, dequeueUseOld, ThresholdQueueBase::GetRawDequeuePtr(), CPN::QueueBase::indequeue, oldqueue, and queue.
Referenced by CPN::RemoteQueue::SendEnqueuePacket().
{
         const void *ret = 0;
         if (dequeueUseOld) {
             // The ONLY reason this code path should be followed is if the node made a getdequeueptr
             // then called getdequeueptr again before dequeue when a grow happens inbetween
             ASSERT(indequeue);
             ret = oldqueue->GetRawDequeuePtr(thresh, chan);
             ASSERT(ret);
         } else {
             ret = queue->GetRawDequeuePtr(thresh, chan);
         }
         return ret;
     }
void * ThresholdQueue< T >::InternalGetRawEnqueuePtr (unsigned thresh, unsigned chan) protected virtual
Implements CPN::QueueBase.
Definition at line 57 of file CPNThresholdQueue.cc.
References ASSERT, enqueueUseOld, ThresholdQueueBase::GetRawEnqueuePtr(), CPN::QueueBase::inenqueue, oldqueue, and queue.
Referenced by CPN::RemoteQueue::EnqueuePacket().
{
         void *ret = 0;
         if (enqueueUseOld) {
             ASSERT(inenqueue);
             ret = oldqueue->GetRawEnqueuePtr(thresh, chan);
             ASSERT(ret);
         } else {
             ret = queue->GetRawEnqueuePtr(thresh, chan);
         }
         return ret;
     }
void ThresholdQueue< T >::InternalReset () protected virtual
Reimplemented from CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 173 of file CPNThresholdQueue.cc.
References dequeueUseOld, enqueueUseOld, CPN::QueueBase::InternalReset(), oldqueue, queue, and ThresholdQueueBase::Reset().
Referenced by CPN::RemoteQueue::InternalReset().
{
         if (dequeueUseOld || enqueueUseOld) {
             dequeueUseOld = false;
             enqueueUseOld = false;
             delete oldqueue;
             oldqueue = 0;
         }
         queue->Reset();
         QueueBase::InternalReset();
     }
bool CPN::QueueBase::IsReaderShutdown () inherited
Definition at line 390 of file QueueBase.cc.
References CPN::QueueBase::readshutdown.
{
         AutoLock<QueueBase> al(*this);
         return readshutdown;
     }
bool CPN::QueueBase::IsWriterShutdown () inherited
Definition at line 395 of file QueueBase.cc.
References CPN::QueueBase::writeshutdown.
{
         AutoLock<QueueBase> al(*this);
         return writeshutdown;
     }
void CPN::QueueBase::Lock () const inline virtual inherited
These functions are to access the lock for the queue.
Implements D4R::QueueBase.
Definition at line 221 of file QueueBase.h.
References lock, and PthreadMutex::Lock().
 { lock.Lock(); }
void CPN::QueueBase::LogState () virtual inherited
For debugging ONLY!! Otherwise non deterministic output.
Reimplemented in CPN::RemoteQueue.
Definition at line 400 of file QueueBase.cc.
References CPN::QueueBase::dequeuethresh, CPN::QueueBase::enqueuethresh, Logger::Error(), CPN::QueueBase::flushed, CPN::QueueBase::indequeue, CPN::QueueBase::inenqueue, CPN::QueueBase::logger, CPN::QueueBase::readerkey, CPN::QueueBase::readrequest, CPN::QueueBase::readshutdown, CPN::QueueBase::UnlockedCount(), CPN::QueueBase::UnlockedFreespace(), CPN::QueueBase::UnlockedMaxThreshold(), CPN::QueueBase::UnlockedNumDequeued(), CPN::QueueBase::UnlockedNumEnqueued(), CPN::QueueBase::UnlockedQueueLength(), CPN::QueueBase::writerequest, CPN::QueueBase::writerkey, and CPN::QueueBase::writeshutdown.
Referenced by CPN::RemoteQueue::LogState().
{
         logger.Error("Printing state (w:%llu r:%llu)", readerkey, writerkey);
         logger.Error("size: %u, maxthresh: %u count: %u free: %u, flushed: %d",
                 UnlockedQueueLength(), UnlockedMaxThreshold(), UnlockedCount(), UnlockedFreespace(),
                 (int)flushed);
         logger.Error("readrequest: %u, writerequest: %u numenqueued: %u, numdequeued: %u",
                 readrequest, writerequest, UnlockedNumEnqueued(), UnlockedNumDequeued());
         if (indequeue) {
             logger.Error("Indequeue (thresh: %u)", dequeuethresh);
         }
         if (inenqueue) {
             logger.Error("Inenqueue (thresh: %u)", enqueuethresh);
         }
         if (readshutdown) {
             logger.Error("Reader shutdown");
         }
         if (writeshutdown) {
             logger.Error("Writer shutdown");
         }
     }
unsigned CPN::QueueBase::MaxThreshold () const inherited
Returns
the maximum threshold this queue supports in bytes
Definition at line 225 of file QueueBase.cc.
References CPN::QueueBase::UnlockedMaxThreshold().
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), and UnlockedGrow().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedMaxThreshold();
     }
void CPN::QueueBase::NotifyData () protected inherited
Definition at line 341 of file QueueBase.cc.
References PthreadCondition::Broadcast(), CPN::QueueBase::cond, CPN::QueueBase::readrequest, and CPN::QueueBase::UnlockedCount().
Referenced by CPN::QueueBase::Enqueue(), and CPN::RemoteQueue::EnqueuePacket().
{
         if (UnlockedCount() >= readrequest) {
             cond.Broadcast();
         }
     }
void CPN::QueueBase::NotifyFreespace () protected inherited
Definition at line 362 of file QueueBase.cc.
References PthreadCondition::Broadcast(), CPN::QueueBase::cond, CPN::QueueBase::UnlockedFreespace(), and CPN::QueueBase::writerequest.
Referenced by CPN::QueueBase::Dequeue(), and CPN::RemoteQueue::SendEnqueuePacket().
{
         if (UnlockedFreespace() >= writerequest) {
             cond.Broadcast();
         }
     }
void CPN::QueueBase::NotifyTerminate () inherited
Used to tell any waiting threads that the network is terminating.
Definition at line 368 of file QueueBase.cc.
References PthreadCondition::Broadcast(), and CPN::QueueBase::cond.
{
         AutoLock<QueueBase> al(*this);
         cond.Broadcast();
     }
unsigned CPN::QueueBase::NumChannels () const inherited
Returns
the number of channels supported by this queue.
Definition at line 200 of file QueueBase.cc.
References CPN::QueueBase::UnlockedNumChannels().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedNumChannels();
     }
unsigned CPN::QueueBase::NumDequeued () const inherited
Definition at line 321 of file QueueBase.cc.
References CPN::QueueBase::UnlockedNumDequeued().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedNumDequeued();
     }
unsigned CPN::QueueBase::NumEnqueued () const inherited
Definition at line 316 of file QueueBase.cc.
References CPN::QueueBase::UnlockedNumEnqueued().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedNumEnqueued();
     }
unsigned CPN::QueueBase::QueueLength () const inherited
Returns
the maximum number of bytes that can be put in this queue.
Definition at line 230 of file QueueBase.cc.
References CPN::QueueBase::UnlockedQueueLength().
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), CPN::RemoteQueue::GrowPacket(), UnlockedGrow(), and CPN::RemoteQueue::UnlockedGrow().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedQueueLength();
     }
bool CPN::QueueBase::RawDequeue (void * data, unsigned count, unsigned numChans, unsigned chanStride) inherited
Dequeue data from the queue directly into the memory pointed to by data. This function shall be equivalent to a call to GetRawDequeuePtr then a memcpy and then a call to Dequeue.
Parameters
data poiner to memory to dequeue to
count the number of bytes to copy into data
numChans the number of channels to write to
chanStride the distance in bytes between the beginning of the channels in data.
Returns
true on success false on failure
Definition at line 102 of file QueueBase.cc.
References ASSERT, CPN::QueueBase::Dequeue(), and CPN::QueueBase::GetRawDequeuePtr().
Referenced by CPN::QueueBase::RawDequeue().
{
         const void *src = GetRawDequeuePtr(count, 0);
         char *dest = (char*)data;
         if (!src) { return false; }
         memcpy(dest, src, count);
         for (unsigned chan = 1; chan < numChans; ++chan) {
             src = GetRawDequeuePtr(count, chan);
             ASSERT(src);
             dest += chanStride;
             memcpy(dest, src, count);
         }
         Dequeue(count);
         return true;
     }
bool CPN::QueueBase::RawDequeue (void * data, unsigned count) inherited
A version of RawDequeue to use when there is only 1 channel.
Parameters
data the data to enqueue
count the number of bytes to enqueue
Returns
true on success false if we have reached the end of the queue
Definition at line 117 of file QueueBase.cc.
References CPN::QueueBase::RawDequeue().
{
         return RawDequeue(data, count, 1, 0);
     }
void CPN::QueueBase::RawEnqueue (const void * data, unsigned count, unsigned numChans, unsigned chanStride) inherited
This function shall be equivalent to a call to GetRqwEnqueuePtr and a memcpy and then a call to Enqueue
The underlying implementatin may implement ether the GetRawEnqueuePtr and Enqueue or RawEnqueue and then implement the other in terms of the one implemented.
Parameters
data pointer to the memory to enqueue
count the number of bytes to enqueue
numChans the number of channels to write to
chanStride the distance in bytes between the beginning of the channels in data.
Definition at line 169 of file QueueBase.cc.
References CPN::QueueBase::Enqueue(), and CPN::QueueBase::GetRawEnqueuePtr().
Referenced by CPN::QueueBase::RawEnqueue().
{
         void *dest = GetRawEnqueuePtr(count, 0);
         const char *src = (char*)data;
         memcpy(dest, src, count);
         for (unsigned chan = 1; chan < numChans; ++chan) {
             dest = GetRawEnqueuePtr(count, chan);
             src += chanStride;
             memcpy(dest, src, count);
         }
         Enqueue(count);
     }
void CPN::QueueBase::RawEnqueue (const void * data, unsigned count) inherited
A version of RawEnqueue to use when there is only 1 channel.
Parameters
data pointer to the memory to enqueue
count the number of bytes to enqueue
Definition at line 196 of file QueueBase.cc.
References CPN::QueueBase::RawEnqueue().
{
         return RawEnqueue(data, count, 1, 0);
     }
void D4R::QueueBase::ReadBlock () protected inherited
reader ===> writer ReadBlock requires that you already hold the lock and if it is reentrant then a single unlock will release the lock.
Exceptions
D4R::DeadlockException
Definition at line 71 of file D4RQueue.cc.
References D4R::QueueBase::incomm, D4R::QueueBase::ReadBlocked(), D4R::QueueBase::reader, D4R::QueueBase::Signal(), D4R::QueueBase::Wait(), D4R::QueueBase::writer, and D4R::QueueBase::writetagchanged.
Referenced by CPN::QueueBase::WaitForData().
{
         if (!writer) {
             while (ReadBlocked() && !writer) {
                 Wait();
             }
         }
         if (!ReadBlocked()) { return; }
         writetagchanged = false;
         try {
             while (incomm) { Wait(); }
             ScopeSetter<bool> ss(incomm, true);
             AutoUnlock<QueueBase> au(*this);
             reader->Block(writer->GetPublicTag(), -1);
         } catch (...) { Signal(); throw; }
         Signal();
         while (ReadBlocked()) {
             if (writetagchanged) {
                 writetagchanged = false;
                 bool detect;
                 try {
                     while (incomm) { Wait(); }
                     ScopeSetter<bool> ss(incomm, true);
                     AutoUnlock<QueueBase> au(*this);
                     detect = reader->Transmit(writer->GetPublicTag());
                 } catch (...) { Signal(); throw; }
                 Signal();
                 if (detect) {
                     throw DeadlockException("True deadlock detected");
                 }
             } else {
                 Wait();
             }
         }
     }
bool CPN::QueueBase::ReadBlocked () protected virtual inherited
Returns
true if we are blocked
Implements D4R::QueueBase.
Definition at line 336 of file QueueBase.cc.
References CPN::KernelBase::CheckTerminated(), CPN::QueueBase::flushed, CPN::QueueBase::kernel, CPN::QueueBase::readrequest, CPN::QueueBase::readshutdown, CPN::QueueBase::UnlockedCount(), and CPN::QueueBase::writeshutdown.
Referenced by CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::WaitForData(), and CPN::QueueBase::WaitForData().
{
         kernel->CheckTerminated();
         return UnlockedCount() < readrequest && !(readshutdown || writeshutdown) && !flushed;
     }
unsigned CPN::QueueBase::ReadRequest () inherited
For unit tests.
Definition at line 380 of file QueueBase.cc.
References CPN::QueueBase::readrequest.
{
         AutoLock<QueueBase> al(*this);
         return readrequest;
     }
void CPN::QueueBase::Reset () inherited
Definition at line 181 of file QueueBase.cc.
References CPN::QueueBase::InternalReset().
{
         AutoLock<const QueueBase> al(*this);
         InternalReset();
     }
void D4R::QueueBase::SetReaderNode (shared_ptr< Node > n) inherited
Set the node which is reading from this queue
Parameters
n the node
Definition at line 59 of file D4RQueue.cc.
References D4R::QueueBase::reader, and D4R::QueueBase::Signal().
Referenced by CPN::RemoteQueue::RemoteQueue().
{
         AutoLock<QueueBase> al(*this);
         reader = n;
         Signal();
     }
void D4R::QueueBase::SetWriterNode (shared_ptr< Node > n) inherited
Set the node which is writing to this queue.
Parameters
n the node
Definition at line 65 of file D4RQueue.cc.
References D4R::QueueBase::Signal(), and D4R::QueueBase::writer.
Referenced by CPN::RemoteQueue::RemoteQueue().
{
         AutoLock<QueueBase> al(*this);
         writer = n;
         Signal();
     }
void CPN::QueueBase::ShutdownReader () inherited
Called by the QueueReader when no more data will be read.
Definition at line 250 of file QueueBase.cc.
References CPN::QueueBase::UnlockedShutdownReader().
Referenced by CPN::RemoteQueue::FileThreadEntryPoint().
{
         AutoLock<QueueBase> al(*this);
         UnlockedShutdownReader();
     }
void CPN::QueueBase::ShutdownWriter () inherited
Called by the QueueWriter when no more data will be written.
Definition at line 260 of file QueueBase.cc.
References CPN::QueueBase::UnlockedShutdownWriter().
Referenced by CPN::RemoteQueue::FileThreadEntryPoint().
{
         AutoLock<QueueBase> al(*this);
         UnlockedShutdownWriter();
     }
virtual void CPN::QueueBase::Signal () inline protected virtual inherited
Signal that Wait should return
Implements D4R::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 247 of file QueueBase.h.
Referenced by CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::Signal(), CPN::QueueBase::UnlockedShutdownReader(), and CPN::QueueBase::UnlockedShutdownWriter().
 { cond.Broadcast(); }
void D4R::QueueBase::SignalReaderTagChanged () inherited
These functions are called by the D4R::Node when thier tag changes.
Definition at line 139 of file D4RQueue.cc.
References D4R::QueueBase::UnlockedSignalReaderTagChanged().
{
         AutoLock<QueueBase> al(*this);
         UnlockedSignalReaderTagChanged();
     }
void D4R::QueueBase::SignalWriterTagChanged () inherited
Definition at line 150 of file D4RQueue.cc.
References D4R::QueueBase::UnlockedSignalWriterTagChanged().
{
         AutoLock<QueueBase> al(*this);
         UnlockedSignalWriterTagChanged();
     }
void CPN::QueueBase::Unlock (void) const inline virtual inherited
Implements D4R::QueueBase.
Definition at line 222 of file QueueBase.h.
References lock, and PthreadMutex::Unlock().
 { lock.Unlock(); }
unsigned ThresholdQueue< T >::UnlockedCount () const protected virtual
Implements CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 149 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::Count(), and queue.
{
         return queue->Count();
     }
unsigned ThresholdQueue< T >::UnlockedDequeueChannelStride () const protected virtual
Implements CPN::QueueBase.
Definition at line 110 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::ChannelStride(), dequeueUseOld, oldqueue, and queue.
{
         if (dequeueUseOld) {
             return oldqueue->ChannelStride();
         } else {
             return queue->ChannelStride();
         }
     }
bool ThresholdQueue< T >::UnlockedEmpty () const protected virtual
Implements CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 153 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::Empty(), and queue.
{
         return queue->Empty();
     }
unsigned ThresholdQueue< T >::UnlockedEnqueueChannelStride () const protected virtual
Implements CPN::QueueBase.
Definition at line 102 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::ChannelStride(), enqueueUseOld, oldqueue, and queue.
{
         if (enqueueUseOld) {
             return oldqueue->ChannelStride();
         } else {
             return queue->ChannelStride();
         }
     }
unsigned ThresholdQueue< T >::UnlockedFreespace () const protected virtual
Implements CPN::QueueBase.
Definition at line 118 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::Freespace(), and queue.
Referenced by CPN::RemoteQueue::GetState().
{
         return queue->Freespace();
     }
bool ThresholdQueue< T >::UnlockedFull () const protected virtual
Implements CPN::QueueBase.
Definition at line 122 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::Full(), and queue.
{
         return queue->Full();
     }
void ThresholdQueue< T >::UnlockedGrow (unsigned queueLen, unsigned maxThresh) protected virtual
Implements CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 184 of file CPNThresholdQueue.cc.
References ASSERT, dequeueUseOld, enqueueUseOld, CPN::ThresholdQueue::TQImpl::Grow(), CPN::QueueBase::indequeue, CPN::QueueBase::inenqueue, CPN::QueueBase::MaxThreshold(), oldqueue, queue, and CPN::QueueBase::QueueLength().
Referenced by CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteQueue::GrowPacket(), and CPN::RemoteQueue::UnlockedGrow().
{
         if (queueLen <= queue->QueueLength() && maxThresh <= queue->MaxThreshold()) return;
         ASSERT(!(inenqueue && indequeue), "Unhandled grow case of having an outstanding dequeue and enqueue");
         if (oldqueue) {
             // If the old queue is still around we have to still be in the same state
             ASSERT(enqueueUseOld == inenqueue);
             ASSERT(dequeueUseOld == indequeue);
             queue->Grow(queueLen, maxThresh, false);
         } else if (!inenqueue && !indequeue) {
             queue->Grow(queueLen, maxThresh, false);
         } else {
             enqueueUseOld = inenqueue;
             dequeueUseOld = indequeue;
             // this should make a duplicate
             oldqueue = queue->Grow(queueLen, maxThresh, true);
             if (!oldqueue) {
                 enqueueUseOld = false;
                 enqueueUseOld = false;
             }
         }
     }
unsigned ThresholdQueue< T >::UnlockedMaxThreshold () const protected virtual
Implements CPN::QueueBase.
Definition at line 157 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::MaxThreshold(), and queue.
Referenced by CPN::RemoteQueue::GetState(), and CPN::RemoteQueue::UnlockedGrow().
{
         return queue->MaxThreshold();
     }
unsigned ThresholdQueue< T >::UnlockedNumChannels () const protected virtual
Implements CPN::QueueBase.
Definition at line 98 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::NumChannels(), and queue.
{
         return queue->NumChannels();
     }
unsigned ThresholdQueue< T >::UnlockedNumDequeued () const protected virtual
Implements CPN::QueueBase.
Definition at line 169 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::ElementsDequeued(), and queue.
Referenced by CPN::RemoteQueue::GetState().
{
         return queue->ElementsDequeued();
     }
unsigned ThresholdQueue< T >::UnlockedNumEnqueued () const protected virtual
Implements CPN::QueueBase.
Definition at line 165 of file CPNThresholdQueue.cc.
References ThresholdQueueBase::ElementsEnqueued(), and queue.
Referenced by CPN::RemoteQueue::GetState().
{
         return queue->ElementsEnqueued();
     }
unsigned ThresholdQueue< T >::UnlockedQueueLength () const protected virtual
Implements CPN::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 161 of file CPNThresholdQueue.cc.
References queue, and ThresholdQueueBase::QueueLength().
{
         return queue->QueueLength();
     }
void CPN::QueueBase::UnlockedShutdownReader () protected virtual inherited
Definition at line 255 of file QueueBase.cc.
References CPN::QueueBase::readshutdown, and CPN::QueueBase::Signal().
Referenced by CPN::RemoteQueue::EndOfReadPacket(), CPN::RemoteQueue::InternalCheckStatus(), and CPN::QueueBase::ShutdownReader().
{
         readshutdown = true;
         Signal();
     }
void CPN::QueueBase::UnlockedShutdownWriter () protected virtual inherited
Definition at line 311 of file QueueBase.cc.
References CPN::QueueBase::Signal(), and CPN::QueueBase::writeshutdown.
Referenced by CPN::RemoteQueue::EndOfWritePacket(), CPN::RemoteQueue::InternalCheckStatus(), and CPN::QueueBase::ShutdownWriter().
{
         writeshutdown = true;
         Signal();
     }
void D4R::QueueBase::UnlockedSignalReaderTagChanged () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 144 of file D4RQueue.cc.
References DEBUG, D4R::QueueBase::reader, D4R::QueueBase::readtagchanged, D4R::QueueBase::Signal(), and D4R::QueueBase::writer.
Referenced by CPN::RemoteQueue::D4RTagPacket(), D4R::QueueBase::SignalReaderTagChanged(), and CPN::RemoteQueue::UnlockedSignalReaderTagChanged().
{
         DEBUG("%s: (%llu -> %llu)\n", __PRETTY_FUNCTION__, (writer ? writer->GetPrivateTag().Key() : 0), (reader ? reader->GetPrivateTag().Key() : 0));
         readtagchanged = true;
         Signal();
     }
void D4R::QueueBase::UnlockedSignalWriterTagChanged () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 155 of file D4RQueue.cc.
References DEBUG, D4R::QueueBase::reader, D4R::QueueBase::Signal(), D4R::QueueBase::writer, and D4R::QueueBase::writetagchanged.
Referenced by CPN::RemoteQueue::D4RTagPacket(), D4R::QueueBase::SignalWriterTagChanged(), and CPN::RemoteQueue::UnlockedSignalWriterTagChanged().
{
         DEBUG("%s: (%llu -> %llu)\n", __PRETTY_FUNCTION__, (writer ? writer->GetPrivateTag().Key() : 0), (reader ? reader->GetPrivateTag().Key() : 0));
         writetagchanged = true;
         Signal();
     }
virtual void CPN::QueueBase::Wait () inline protected virtual inherited
Wait untill Signal is called. Must be holding the lock to call.
Implements D4R::QueueBase.
Definition at line 246 of file QueueBase.h.
References lock.
Referenced by CPN::RemoteQueue::ActionThreadEntryPoint(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::WaitForData(), and CPN::RemoteQueue::WaitForFreespace().
 { cond.Wait(lock); }
void CPN::QueueBase::WaitForData () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 326 of file QueueBase.cc.
References CPN::QueueBase::cond, CPN::QueueBase::lock, D4R::QueueBase::ReadBlock(), CPN::QueueBase::ReadBlocked(), CPN::QueueBase::useD4R, and PthreadCondition::Wait().
Referenced by CPN::QueueBase::GetRawDequeuePtr(), and CPN::RemoteQueue::WaitForData().
{
         if (useD4R) {
             ReadBlock();
         } else {
             while (ReadBlocked()) {
                 cond.Wait(lock);
             }
         }
     }
void CPN::QueueBase::WaitForFreespace () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 347 of file QueueBase.cc.
References CPN::QueueBase::cond, CPN::QueueBase::lock, CPN::QueueBase::UnlockedQueueLength(), CPN::QueueBase::useD4R, PthreadCondition::Wait(), D4R::QueueBase::WriteBlock(), and CPN::QueueBase::WriteBlocked().
Referenced by CPN::QueueBase::GetRawEnqueuePtr(), CPN::QueueBase::InternalFlush(), and CPN::RemoteQueue::WaitForFreespace().
{
         if (useD4R) {
             WriteBlock(UnlockedQueueLength());
         } else {
             while (WriteBlocked()) {
                 cond.Wait(lock);
             }
         }
     }
void D4R::QueueBase::WriteBlock (unsigned qsize) protected inherited
writer ===> reader WriteBlock requires that you already hold the lock and if it is reentrant then a single unlock will release the lock.
Definition at line 106 of file D4RQueue.cc.
References D4R::QueueBase::Detect(), D4R::QueueBase::incomm, D4R::QueueBase::reader, D4R::QueueBase::readtagchanged, D4R::QueueBase::Signal(), D4R::QueueBase::Wait(), D4R::QueueBase::WriteBlocked(), and D4R::QueueBase::writer.
Referenced by CPN::QueueBase::GetRawEnqueuePtr(), and CPN::QueueBase::WaitForFreespace().
{
         if (!reader) {
             while (WriteBlocked() && !reader) {
                 Wait();
             }
         }
         if (!WriteBlocked()) { return; }
         readtagchanged = false;
         try {
             while (incomm) { Wait(); }
             ScopeSetter<bool> ss(incomm, true);
             AutoUnlock<QueueBase> au(*this);
             writer->Block(reader->GetPublicTag(), qsize);
         } catch (...) { Signal(); throw; }
         Signal();
         while (WriteBlocked()) {
             if (readtagchanged) {
                 readtagchanged = false;
                 bool detect;
                 try {
                     while (incomm) { Wait(); }
                     ScopeSetter<bool> ss(incomm, true);
                     AutoUnlock<QueueBase> au(*this);
                     detect = writer->Transmit(reader->GetPublicTag());
                 } catch (...) { Signal(); throw; }
                 Signal();
                 if (detect) { Detect(); }
             } else {
                 Wait();
             }
         }
     }
bool CPN::QueueBase::WriteBlocked () protected virtual inherited
Returns
true if we are blocked.
Implements D4R::QueueBase.
Definition at line 357 of file QueueBase.cc.
References CPN::KernelBase::CheckTerminated(), CPN::QueueBase::flushed, CPN::QueueBase::kernel, CPN::QueueBase::readshutdown, CPN::QueueBase::UnlockedFreespace(), CPN::QueueBase::writerequest, and CPN::QueueBase::writeshutdown.
Referenced by CPN::QueueBase::GetRawDequeuePtr(), CPN::RemoteQueue::WaitForFreespace(), and CPN::QueueBase::WaitForFreespace().
{
         kernel->CheckTerminated();
         return (UnlockedFreespace() < writerequest || flushed) && !(readshutdown || writeshutdown);
     }
unsigned CPN::QueueBase::WriteRequest () inherited
For unit tests.
Definition at line 385 of file QueueBase.cc.
References CPN::QueueBase::writerequest.
{
         AutoLock<QueueBase> al(*this);
         return writerequest;
     }
Member Data Documentation
PthreadCondition CPN::QueueBase::cond protected inherited
Definition at line 290 of file QueueBase.h.
Referenced by CPN::QueueBase::InternalFlush(), CPN::QueueBase::InternalReset(), CPN::QueueBase::NotifyData(), CPN::QueueBase::NotifyFreespace(), CPN::QueueBase::NotifyTerminate(), CPN::QueueBase::WaitForData(), and CPN::QueueBase::WaitForFreespace().
std::string CPN::QueueBase::datatype protected inherited
Definition at line 291 of file QueueBase.h.
unsigned CPN::QueueBase::dequeuethresh protected inherited
Definition at line 282 of file QueueBase.h.
Referenced by CPN::QueueBase::Dequeue(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), and CPN::RemoteQueue::ResetPacket().
bool CPN::ThresholdQueue::dequeueUseOld protected
Definition at line 90 of file CPNThresholdQueue.h.
Referenced by InternalDequeue(), InternalGetRawDequeuePtr(), InternalReset(), CPN::RemoteQueue::ResetPacket(), UnlockedDequeueChannelStride(), and UnlockedGrow().
unsigned CPN::QueueBase::enqueuethresh protected inherited
Definition at line 281 of file QueueBase.h.
Referenced by CPN::QueueBase::Enqueue(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), and CPN::RemoteQueue::ResetPacket().
bool CPN::ThresholdQueue::enqueueUseOld protected
Definition at line 89 of file CPNThresholdQueue.h.
Referenced by InternalEnqueue(), InternalGetRawEnqueuePtr(), InternalReset(), CPN::RemoteQueue::ResetPacket(), UnlockedEnqueueChannelStride(), and UnlockedGrow().
bool CPN::QueueBase::flushed protected inherited
Definition at line 285 of file QueueBase.h.
Referenced by CPN::QueueBase::Flushed(), CPN::RemoteQueue::FlushPacket(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::QueueBase::InternalFlush(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), CPN::QueueBase::ReadBlocked(), CPN::RemoteQueue::ResetPacket(), and CPN::QueueBase::WriteBlocked().
bool D4R::QueueBase::incomm protected inherited
Definition at line 126 of file D4RQueue.h.
Referenced by D4R::QueueBase::ReadBlock(), and D4R::QueueBase::WriteBlock().
bool CPN::QueueBase::indequeue protected inherited
Definition at line 283 of file QueueBase.h.
Referenced by CPN::QueueBase::Dequeue(), CPN::QueueBase::GetRawDequeuePtr(), InternalGetRawDequeuePtr(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendEnqueuePacket(), and UnlockedGrow().
bool CPN::QueueBase::inenqueue protected inherited
Definition at line 284 of file QueueBase.h.
Referenced by CPN::QueueBase::Enqueue(), CPN::RemoteQueue::EnqueuePacket(), CPN::QueueBase::GetRawEnqueuePtr(), InternalGetRawEnqueuePtr(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), CPN::RemoteQueue::ResetPacket(), and UnlockedGrow().
KernelBase* CPN::QueueBase::kernel protected inherited
Definition at line 286 of file QueueBase.h.
Referenced by CPN::QueueBase::Detect(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::InternalCheckStatus(), CPN::QueueBase::ReadBlocked(), and CPN::QueueBase::WriteBlocked().
PthreadMutex CPN::QueueBase::lock mutable protected inherited
Definition at line 289 of file QueueBase.h.
Referenced by CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::UnlockedGrow(), CPN::QueueBase::WaitForData(), and CPN::QueueBase::WaitForFreespace().
Logger CPN::QueueBase::logger protected inherited
Definition at line 288 of file QueueBase.h.
Referenced by CPN::RemoteQueue::D4RTagPacket(), CPN::RemoteQueue::DequeuePacket(), CPN::QueueBase::Detect(), CPN::RemoteQueue::EndOfReadPacket(), CPN::RemoteQueue::EndOfWritePacket(), CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::FlushPacket(), CPN::RemoteQueue::GrowPacket(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteQueue::InternalDequeue(), CPN::RemoteQueue::InternalEnqueue(), CPN::RemoteQueue::LogState(), CPN::QueueBase::LogState(), CPN::QueueBase::QueueBase(), CPN::RemoteQueue::Read(), CPN::RemoteQueue::ReadBlockPacket(), CPN::RemoteQueue::RemoteQueue(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendD4RTagPacket(), CPN::RemoteQueue::SendDequeuePacket(), CPN::RemoteQueue::SendEndOfReadPacket(), CPN::RemoteQueue::SendEndOfWritePacket(), CPN::RemoteQueue::SendEnqueuePacket(), CPN::RemoteQueue::SendFlushPacket(), CPN::RemoteQueue::SendGrowPacket(), CPN::RemoteQueue::SendReadBlockPacket(), CPN::RemoteQueue::SendResetPacket(), CPN::RemoteQueue::SendWriteBlockPacket(), CPN::RemoteQueue::UnlockedGrow(), CPN::RemoteQueue::UnlockedShutdown(), CPN::RemoteQueue::UnlockedSignalReaderTagChanged(), CPN::RemoteQueue::UnlockedSignalWriterTagChanged(), CPN::RemoteQueue::WaitForData(), CPN::RemoteQueue::WaitForFreespace(), CPN::RemoteQueue::WriteBlockPacket(), and CPN::RemoteQueue::~RemoteQueue().
TQImpl* CPN::ThresholdQueue::oldqueue protected
Definition at line 88 of file CPNThresholdQueue.h.
Referenced by InternalDequeue(), InternalEnqueue(), InternalGetRawDequeuePtr(), InternalGetRawEnqueuePtr(), InternalReset(), CPN::RemoteQueue::ResetPacket(), UnlockedDequeueChannelStride(), UnlockedEnqueueChannelStride(), UnlockedGrow(), and ~ThresholdQueue().
unsigned CPN::QueueBase::postpad protected inherited
Definition at line 278 of file QueueBase.h.
Referenced by CPN::QueueBase::InternalFlush().
unsigned CPN::QueueBase::prepad protected inherited
Definition at line 277 of file QueueBase.h.
Referenced by CPN::QueueBase::InternalReset().
TQImpl* CPN::ThresholdQueue::queue protected
Definition at line 87 of file CPNThresholdQueue.h.
Referenced by CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteQueue::GrowPacket(), CPN::RemoteQueue::InternalCheckStatus(), InternalDequeue(), InternalEnqueue(), InternalGetRawDequeuePtr(), InternalGetRawEnqueuePtr(), InternalReset(), CPN::RemoteQueue::ReadBlockPacket(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendDequeuePacket(), CPN::RemoteQueue::SendEnqueuePacket(), CPN::RemoteQueue::SendGrowPacket(), ThresholdQueue(), UnlockedCount(), CPN::RemoteQueue::UnlockedCount(), UnlockedDequeueChannelStride(), UnlockedEmpty(), CPN::RemoteQueue::UnlockedEmpty(), UnlockedEnqueueChannelStride(), UnlockedFreespace(), UnlockedFull(), UnlockedGrow(), CPN::RemoteQueue::UnlockedGrow(), UnlockedMaxThreshold(), UnlockedNumChannels(), UnlockedNumDequeued(), UnlockedNumEnqueued(), UnlockedQueueLength(), CPN::RemoteQueue::WriteBlockPacket(), and ~ThresholdQueue().
shared_ptr<Node> D4R::QueueBase::reader protected inherited
Definition at line 122 of file D4RQueue.h.
Referenced by CPN::RemoteQueue::InternalCheckStatus(), D4R::QueueBase::ReadBlock(), CPN::RemoteQueue::SendD4RTagPacket(), D4R::QueueBase::SetReaderNode(), D4R::QueueBase::UnlockedSignalReaderTagChanged(), D4R::QueueBase::UnlockedSignalWriterTagChanged(), and D4R::QueueBase::WriteBlock().
const Key_t CPN::QueueBase::readerkey protected inherited
Definition at line 273 of file QueueBase.h.
Referenced by CPN::QueueBase::Dequeue(), CPN::RemoteQueue::GetKey(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::LogState(), CPN::QueueBase::QueueBase(), and CPN::RemoteQueue::RemoteQueue().
unsigned CPN::QueueBase::readrequest protected inherited
Definition at line 279 of file QueueBase.h.
Referenced by CPN::RemoteQueue::DequeuePacket(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::InternalCheckStatus(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), CPN::QueueBase::NotifyData(), CPN::QueueBase::ReadBlocked(), CPN::RemoteQueue::ReadBlockPacket(), CPN::QueueBase::ReadRequest(), CPN::RemoteQueue::ResetPacket(), and CPN::RemoteQueue::SendReadBlockPacket().
bool CPN::QueueBase::readshutdown protected inherited
Definition at line 275 of file QueueBase.h.
Referenced by CPN::QueueBase::Dequeue(), CPN::RemoteQueue::DequeuePacket(), CPN::RemoteQueue::EndOfReadPacket(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), CPN::QueueBase::InternalFlush(), CPN::QueueBase::IsReaderShutdown(), CPN::QueueBase::LogState(), CPN::QueueBase::ReadBlocked(), CPN::RemoteQueue::ReadBlockPacket(), CPN::QueueBase::UnlockedShutdownReader(), and CPN::QueueBase::WriteBlocked().
bool D4R::QueueBase::readtagchanged protected inherited
Definition at line 124 of file D4RQueue.h.
Referenced by D4R::QueueBase::UnlockedSignalReaderTagChanged(), and D4R::QueueBase::WriteBlock().
bool CPN::QueueBase::useD4R protected inherited
Definition at line 287 of file QueueBase.h.
Referenced by CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::ReadBlockPacket(), CPN::QueueBase::WaitForData(), CPN::QueueBase::WaitForFreespace(), and CPN::RemoteQueue::WriteBlockPacket().
shared_ptr<Node> D4R::QueueBase::writer protected inherited
Definition at line 123 of file D4RQueue.h.
Referenced by CPN::RemoteQueue::InternalCheckStatus(), D4R::QueueBase::ReadBlock(), CPN::RemoteQueue::SendD4RTagPacket(), D4R::QueueBase::SetWriterNode(), D4R::QueueBase::UnlockedSignalReaderTagChanged(), D4R::QueueBase::UnlockedSignalWriterTagChanged(), and D4R::QueueBase::WriteBlock().
unsigned CPN::QueueBase::writerequest protected inherited
Definition at line 280 of file QueueBase.h.
Referenced by CPN::QueueBase::Detect(), CPN::RemoteQueue::EnqueuePacket(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::InternalCheckStatus(), CPN::QueueBase::InternalFlush(), CPN::QueueBase::InternalReset(), CPN::QueueBase::LogState(), CPN::QueueBase::NotifyFreespace(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendWriteBlockPacket(), CPN::QueueBase::WriteBlocked(), CPN::RemoteQueue::WriteBlockPacket(), and CPN::QueueBase::WriteRequest().
const Key_t CPN::QueueBase::writerkey protected inherited
Definition at line 274 of file QueueBase.h.
Referenced by CPN::QueueBase::Enqueue(), CPN::RemoteQueue::GetKey(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::QueueBase::InternalFlush(), CPN::QueueBase::LogState(), CPN::QueueBase::QueueBase(), and CPN::RemoteQueue::RemoteQueue().
bool CPN::QueueBase::writeshutdown protected inherited
Definition at line 276 of file QueueBase.h.
Referenced by CPN::RemoteQueue::EndOfWritePacket(), CPN::QueueBase::Enqueue(), CPN::RemoteQueue::EnqueuePacket(), CPN::QueueBase::GetRawDequeuePtr(), CPN::QueueBase::GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), CPN::QueueBase::InternalFlush(), CPN::QueueBase::IsWriterShutdown(), CPN::QueueBase::LogState(), CPN::QueueBase::ReadBlocked(), CPN::QueueBase::UnlockedShutdownWriter(), CPN::QueueBase::WriteBlocked(), and CPN::RemoteQueue::WriteBlockPacket().
bool D4R::QueueBase::writetagchanged protected inherited
Definition at line 125 of file D4RQueue.h.
Referenced by D4R::QueueBase::ReadBlock(), and D4R::QueueBase::UnlockedSignalWriterTagChanged().
The documentation for this class was generated from the following files:
lib/CPNThresholdQueue.h
lib/CPNThresholdQueue.cc