CPN: ServerSocketHandle Class Reference
ServerSocketHandle Class Reference
#include <ServerSocketHandle.h>
Public Types
typedef AutoLock< PthreadMutex > ALock
Public Member Functions
ServerSocketHandle ()
ServerSocketHandle (int nfd)
ServerSocketHandle (const SocketAddress &addr, int queuelength=256)
ServerSocketHandle (const SockAddrList &addrs, int queuelength=256)
void Listen (const SocketAddress &addr, int queuelength=256)
void Listen (const SockAddrList &addrs, int queuelength=256)
int Accept (SocketAddress &addr)
int Accept ()
void SetReuseAddr (bool reuse=true)
Turn on reuse of the address. Only takes effect if set before Listen.
bool GetReuseAddr ()
int Poll (double timeout)
bool Readable (bool r)
Set that the file is currently readable or not.
bool Readable () const
Gives the current readability status of the file.
bool Writeable (bool w)
Set that this file is currently writeable or not.
bool Writeable () const
Gives the current writability status of the file.
int FD () const
int FD (int filed)
Set the current file descriptor.
bool Eof () const
bool Eof (bool e)
Set/reset the end of file condition.
bool Good () const
Convenience method for testing if the file this FileHandle has is open and not at end of file.
bool Closed () const
void SetBlocking (bool blocking)
Manipulate how the current file handles blocking.
bool IsBlocking () const
Test if the current file is in blocking or non blocking mode.
void Reset ()
Clear all internal state including the file descriptor! WARNING does not close the file!
void Close ()
Close the file and reset the internal state.
unsigned Read (void *ptr, unsigned len)
Read data from the file descriptor.
unsigned Readv (const iovec *iov, int iovcnt)
scatter gather io version of Read
unsigned Write (const void *ptr, unsigned len)
Write data to the file descriptor.
unsigned Writev (const iovec *iov, int iovcnt)
scatter gather io version of Write
void Flush ()
Tell the OS to flush any buffers it has. May not be supported for all file types.
Static Public Member Functions
static int Poll (IteratorRef< FileHandle * > begin, IteratorRef< FileHandle * > end, double timeout)
poll a list of FileHandles for any activity and call the appropriate On method.
static void SetBlocking (int fd, bool blocking)
a convenience method that allows one to set the same blocking parameters for a file descriptor without setting it inside a FileHandle.
static bool IsBlocking (int fd)
Test the given file descriptor if it is in blocking mode.
Protected Member Functions
virtual void OnReadable ()
Called by Poll when it detects that the file is readable.
virtual void OnWriteable ()
Called by Poll when it detects that the file is writeable.
Protected Attributes
PthreadMutex file_lock
int fd
bool readable
bool writeable
bool eof
Private Member Functions
bool Listen (const SocketAddress &addr, int queuelength, int &error)
int Accept (SocketAddress *addr)
Private Attributes
bool reuse_addr
Detailed Description
Provides functionality for a server socket in a FileHandle
Definition at line 33 of file ServerSocketHandle.h.
Member Typedef Documentation
typedef AutoLock<PthreadMutex> FileHandle::ALock inherited
Definition at line 43 of file FileHandle.h.
Constructor & Destructor Documentation
ServerSocketHandle::ServerSocketHandle () inline
Definition at line 36 of file ServerSocketHandle.h.
 : reuse_addr(false) {}
ServerSocketHandle::ServerSocketHandle (int nfd) inline
Definition at line 37 of file ServerSocketHandle.h.
 : FileHandle(nfd), reuse_addr(false) {}
ServerSocketHandle::ServerSocketHandle (const SocketAddress & addr, int queuelength = 256) inline
Definition at line 38 of file ServerSocketHandle.h.
References Listen().
                                                                          : reuse_addr(false)
     { Listen(addr, queuelength); }
ServerSocketHandle::ServerSocketHandle (const SockAddrList & addrs, int queuelength = 256) inline
Definition at line 40 of file ServerSocketHandle.h.
References Listen().
                                                                          : reuse_addr(false)
     { Listen(addrs, queuelength); }
Member Function Documentation
int ServerSocketHandle::Accept (SocketAddress & addr)
Accept an incoming connection.
Parameters
addr a SocketAddress object to fill with the address of the connecting peer.
Returns
-1 if no connection >=0 on success
Exceptions
ErrnoException for errors
Definition at line 46 of file ServerSocketHandle.cc.
References Accept().
Referenced by CPN::ConnectionServer::Poll().
{
     return Accept(&addr);
 }
int ServerSocketHandle::Accept ()
Accept an incoming connection
Definition at line 50 of file ServerSocketHandle.cc.
Referenced by Accept(), and CPN::RemoteContextDaemon::Read().
{
     return Accept(0);
 }
int ServerSocketHandle::Accept (SocketAddress * addr) private
Definition at line 53 of file ServerSocketHandle.cc.
References FileHandle::FD(), SocketAddress::GetAddr(), SocketAddress::GetLen(), and FileHandle::Readable().
{
     bool loop = true;
     int nfd = -1;
     while (loop) {
         if (addr) {
             addr->GetLen() = sizeof(sockaddr_storage);
             nfd = accept(FD(), addr->GetAddr(), &addr->GetLen());
         } else {
             nfd = accept(FD(), 0, 0);
         }
         if (nfd < 0) {
             int error = errno;
             switch (error) {
             case EAGAIN:
             //case EWOULDBLOCK: // Duplicate
                 Readable(false);
             case ECONNABORTED:
             case EINTR:
             case ENETDOWN:
             case EPROTO:
             case ENOPROTOOPT:
             case EHOSTDOWN:
             //case ENONET:
             case EHOSTUNREACH:
             case ENETUNREACH:
             case ENOBUFS:
             case ENOMEM:
             case EPERM:
             case EPIPE:
             case ETIMEDOUT:
                 nfd = -1;
                 loop = false;
                 break;
             case EOPNOTSUPP:
             case EBADF:
             case EINVAL:
             case ENFILE:
             case EMFILE:
             case ENOTSOCK:
             case EFAULT:
             default:
                 throw ErrnoException(error);
             }
         } else {
             loop = false;
         }
     }
     return nfd;
 }
void FileHandle::Close () inherited
Close the file and reset the internal state.
Definition at line 146 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::readable, and FileHandle::writeable.
Referenced by CPN::ConnectionServer::Close(), CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), and CPN::RemoteContextDaemon::Terminate().
{
     ALock al(file_lock);
     if (fd != -1) {
         if (close(fd) != 0) {
             throw ErrnoException();
         }
         fd = -1;
     }
     readable = false;
     writeable = false;
     eof = false;
 }
bool FileHandle::Closed () const inline inherited
Returns
false if this FileHandle has an open file
Definition at line 128 of file FileHandle.h.
References FileHandle::fd, and FileHandle::file_lock.
Referenced by SocketHandle::Connect(), CPN::ConnectionServer::ConnectReader(), CPN::ConnectionServer::ConnectWriter(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteQueue::LogState(), CPN::ConnectionServer::LogState(), CPN::RemoteContextDaemon::Run(), CPN::RemoteContextDaemon::Client::Send(), and CPN::RemoteContext::SendMessage().
 { ALock al(file_lock); return fd == -1; }
bool FileHandle::Eof () const inline inherited
Returns
the current end of file condition
Definition at line 115 of file FileHandle.h.
References FileHandle::eof, and FileHandle::file_lock.
Referenced by CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteContextDaemon::Client::Read(), and CPN::RemoteQueue::Read().
 { ALock al(file_lock); return eof; }
bool FileHandle::Eof (bool e) inline inherited
Set/reset the end of file condition.
Parameters
e the new end of file condition
Returns
the new end of file condition
Definition at line 120 of file FileHandle.h.
References FileHandle::eof, and FileHandle::file_lock.
 { ALock al(file_lock); return eof = e; }
int FileHandle::FD () const inline inherited
Returns
the current set file descriptor
Definition at line 106 of file FileHandle.h.
References FileHandle::fd, and FileHandle::file_lock.
Referenced by Accept(), CPN::RemoteContextDaemon::Client::Client(), SocketHandle::Connect(), CPN::ConnectionServer::ConnectWriter(), SocketHandle::CreatePair(), CPN::RemoteQueue::FileThreadEntryPoint(), FileHandle::Flush(), CPN::ConnectionServer::GetAddress(), SocketHandle::GetKeepAlive(), SocketHandle::GetLingerTimeout(), SocketHandle::GetNoDelay(), SocketHandle::GetPendingError(), SocketHandle::GetReceiveBufferSize(), SocketHandle::GetReceiveTimeout(), SocketHandle::GetSendBufferSize(), SocketHandle::GetSendTimeout(), FileHandle::IsBlocking(), Listen(), FileHandle::Poll(), CPN::RemoteContextDaemon::Run(), FileHandle::SetBlocking(), SocketHandle::SetKeepAlive(), SocketHandle::SetLingerTimeout(), SocketHandle::SetNoDelay(), SocketHandle::SetReceiveBufferSize(), SocketHandle::SetReceiveTimeout(), SocketHandle::SetSendBufferSize(), SocketHandle::SetSendTimeout(), SocketHandle::ShutdownRead(), SocketHandle::ShutdownWrite(), and WakeupHandle::WakeupHandle().
 { ALock al(file_lock); return fd; }
int FileHandle::FD (int filed) inline inherited
Set the current file descriptor.
Parameters
filed the new file descriptor
Returns
the new file descriptor
Definition at line 111 of file FileHandle.h.
References FileHandle::fd, and FileHandle::file_lock.
 { ALock al(file_lock); return fd = filed; }
void FileHandle::Flush () inherited
Tell the OS to flush any buffers it has. May not be supported for all file types.
Definition at line 293 of file FileHandle.cc.
References FileHandle::FD().
{
     if (fsync(FD()) != 0) {
         throw ErrnoException();
     }
 }
bool ServerSocketHandle::GetReuseAddr () inline
Definition at line 71 of file ServerSocketHandle.h.
References reuse_addr.
 { return reuse_addr; }
bool FileHandle::Good () const inline inherited
Convenience method for testing if the file this FileHandle has is open and not at end of file.
Returns
true if open and not at end of file otherwise false
Definition at line 125 of file FileHandle.h.
References FileHandle::eof, FileHandle::fd, and FileHandle::file_lock.
Referenced by CPN::RemoteContext::EntryPoint(), and CPN::RemoteContextDaemon::Client::Read().
 { ALock al(file_lock); return !(eof || fd == -1); }
bool FileHandle::IsBlocking () const inherited
Test if the current file is in blocking or non blocking mode.
Returns
true if blocking or false if non blocking
Definition at line 128 of file FileHandle.cc.
References FileHandle::FD().
{
     return IsBlocking(FD());
 }
bool FileHandle::IsBlocking (int fd) static inherited
Test the given file descriptor if it is in blocking mode.
Parameters
fd the file descriptor to test
Returns
true if blocking or false if non blocking
Definition at line 132 of file FileHandle.cc.
{
     int flags = fcntl(fd, F_GETFL, 0);
     if (-1 == flags) { throw ErrnoException(); }
     return !(flags & O_NONBLOCK);
 }
void ServerSocketHandle::Listen (const SocketAddress & addr, int queuelength = 256)
Open a new socket and try to listen on the given SocketAddress.
Definition at line 30 of file ServerSocketHandle.cc.
Referenced by CPN::ConnectionServer::ConnectionServer(), Listen(), CPN::RemoteContextDaemon::RemoteContextDaemon(), and ServerSocketHandle().
{
     int error = 0;
     if (!Listen(addr, queuelength, error)) { throw ErrnoException(error); }
 }
void ServerSocketHandle::Listen (const SockAddrList & addrs, int queuelength = 256)
Open a new socket and try to listen on one of the addresses in the given list.
Definition at line 35 of file ServerSocketHandle.cc.
References Listen().
{
     int error = 0;
     bool success = false;
     for (SockAddrList::const_iterator itr = addrs.begin();
             itr != addrs.end(); ++itr) {
         success = Listen(*itr, queuelength, error);
         if (success) break;
     }
     if (!success) throw ErrnoException(error);
 }
bool ServerSocketHandle::Listen (const SocketAddress & addr, int queuelength, int & error) private
Definition at line 103 of file ServerSocketHandle.cc.
References SocketAddress::Family(), FileHandle::FD(), SocketAddress::GetAddr(), SocketAddress::GetLen(), and reuse_addr.
{
     SocketAddress address = addr;
     int nfd = socket(address.Family(), SOCK_STREAM, 0);
     if (nfd < 0) {
         error = errno;
         return false;
     }
     if (reuse_addr) {
         int opt = 1;
         if (setsockopt(nfd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) < 0) {
             throw ErrnoException();
         }
     }
     if (bind(nfd, address.GetAddr(), address.GetLen()) < 0) {
         error = errno;
         return false;
     }
     if (listen(nfd, queuelength) < 0) {
         error = errno;
         return false;
     }
     FD(nfd);
     return true;
 }
virtual void FileHandle::OnReadable () inline protected virtual inherited
Called by Poll when it detects that the file is readable.
Reimplemented in WakeupHandle.
Definition at line 210 of file FileHandle.h.
References FileHandle::Readable().
Referenced by FileHandle::Poll().
 { Readable(true); }
virtual void FileHandle::OnWriteable () inline protected virtual inherited
Called by Poll when it detects that the file is writeable.
Definition at line 212 of file FileHandle.h.
References FileHandle::Writeable().
Referenced by FileHandle::Poll().
 { Writeable(true); }
int FileHandle::Poll (IteratorRef< FileHandle * > begin, IteratorRef< FileHandle * > end, double timeout) static inherited
poll a list of FileHandles for any activity and call the appropriate On method.
Definition at line 34 of file FileHandle.cc.
References FileHandle::FD(), FileHandle::fd, FileHandle::OnReadable(), FileHandle::OnWriteable(), FileHandle::Readable(), and FileHandle::Writeable().
Referenced by CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::ConnectionServer::Poll(), FileHandle::Poll(), and CPN::RemoteContextDaemon::Run().
{
     fd_set rfd;
     fd_set wfd;
     FD_ZERO(&rfd);
     FD_ZERO(&wfd);
     int maxfd = 0;
     IteratorRef<FileHandle*> itr = begin;
     while (itr != end) {
         FileHandle *han = *itr;
         int fd = han->FD();
         if (fd < 0) {
             return -1;
         } else {
             bool set = false;
             if (!han->Readable()) {
                 FD_SET(fd, &rfd);
                 set = true;
             }
             if (!han->Writeable()) {
                 FD_SET(fd, &wfd);
                 set = true;
             }
             if (set) { maxfd = std::max(maxfd, fd); }
         }
         ++itr;
     }
     timeval tv;
     timeval *ptv = 0;
     if (timeout >= 0) {
         tv.tv_sec = (int)timeout;
         tv.tv_usec = (int)((timeout - tv.tv_sec) * 1e6);
         ptv = &tv;
     }
     int ret = select(maxfd + 1, &rfd, &wfd, 0, ptv);
     if (ret < 0) {
         if (errno == EINTR) {
             return 0;
         }
         throw ErrnoException();
     }
     itr = begin;
     while (itr != end) {
         FileHandle *han = *itr;
         int fd = han->FD();
         if (fd >= 0) {
             if (FD_ISSET(fd, &rfd)) {
                 han->OnReadable();
             }
             if (FD_ISSET(fd, &wfd)) {
                 han->OnWriteable();
             }
         }
         ++itr;
     }
     return ret;
 }
int FileHandle::Poll (double timeout) inherited
Poll the current file descriptor for activity specified by the current readable or writeable status, if false poll that value, and call one of OnWriteable or OnReadable whos default action is to set Readable or Writeable to true.
Parameters
timeout -1 to wait forever for activity 0 to poll and return immediately or a time to wait in seconds.
Returns
zero if timed out, positive if an event occurred or negative if an error occurred.
Definition at line 106 of file FileHandle.cc.
References FileHandle::Poll().
{
     FileHandle *fh = this;
     return Poll(&fh, &fh + 1, timeout);
 }
unsigned FileHandle::Read (void * ptr, unsigned len) inherited
Read data from the file descriptor.
Will set the end of file condition if read detects end of file.
Note
All the read functions will set readable to false if they read less than the requested amount or we are non blocking and a would block condition happened.
Parameters
ptr pointer to write data to
len the maximum number of bytes to write to ptr
Returns
0 if no bytes read (check Eof) or the number of bytes read
Definition at line 159 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::Readable(), and FileHandle::readable.
Referenced by CPN::RemoteQueue::D4RTagPacket(), and WakeupHandle::Read().
{
     int filed;
     {
         ALock al(file_lock);
         if (eof || fd == -1) { return 0; }
         filed = fd;
     }
     unsigned bytesread = 0;
     int num = read(filed, ptr, len);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN:
             Readable(false);
         case EINTR:
         case ENOMEM:
             break;
         default:
             throw ErrnoException(error);
         }
     } else if (num == 0 && len != 0) {
         ALock al(file_lock);
         eof = true;
         readable = false;
     } else {
         if (unsigned(num) < len) { Readable(false); }
         bytesread = num;
     }
     return bytesread;
 }
bool FileHandle::Readable (bool r) inline inherited
Set that the file is currently readable or not.
Parameters
r true or false
Returns
the new readable status
Definition at line 86 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::readable.
Referenced by CPN::RemoteContext::EntryPoint(), FileHandle::Poll(), CPN::ConnectionServer::Poll(), and CPN::RemoteQueue::Read().
 { ALock al(file_lock); return readable = r; }
bool FileHandle::Readable () const inline inherited
Gives the current readability status of the file.
Returns
true if it is known that a read will not block
Definition at line 91 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::readable.
Referenced by Accept(), CPN::RemoteContextDaemon::Client::Client(), FileHandle::OnReadable(), CPN::RemoteContextDaemon::Read(), FileHandle::Read(), FileHandle::Readv(), SocketHandle::Recv(), CPN::RemoteContextDaemon::Run(), and WakeupHandle::WakeupHandle().
 { ALock al(file_lock); return readable; }
unsigned FileHandle::Readv (const iovec * iov, int iovcnt) inherited
scatter gather io version of Read
Returns
see Read
Definition at line 190 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::Readable(), and FileHandle::readable.
Referenced by CPN::RemoteQueue::EnqueuePacket().
{
     int filed;
     {
         ALock al(file_lock);
         if (eof || fd == -1) { return 0; }
         filed = fd;
     }
     unsigned len = 0;
     for (int i = 0; i < iovcnt; ++i) {
         len += iov[i].iov_len;
     }
     unsigned bytesread = 0;
     int num = readv(filed, iov, iovcnt);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN:
             Readable(false);
         case EINTR:
         case ENOMEM:
             break;
         default:
             throw ErrnoException(error);
         }
     } else if (num == 0 && len != 0) {
         ALock al(file_lock);
         eof = true;
         readable = false;
     } else {
         if (unsigned(num) < len) { Readable(false); }
         bytesread = num;
     }
     return bytesread;
 }
void FileHandle::Reset () inherited
Clear all internal state including the file descriptor! WARNING does not close the file!
Definition at line 138 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::readable, and FileHandle::writeable.
Referenced by CPN::ConnectionServer::ConnectWriter(), CPN::RemoteQueue::FileThreadEntryPoint(), and FileHandle::~FileHandle().
{
     ALock al(file_lock);
     readable = false;
     writeable = false;
     eof = false;
     fd = -1;
 }
void FileHandle::SetBlocking (bool blocking) inherited
Manipulate how the current file handles blocking.
Parameters
blocking true to set to blocking mode (default) false to set to non blocking mode.
In non blocking mode all reads and writes will not block. Use Poll to block.
Definition at line 111 of file FileHandle.cc.
References FileHandle::FD().
Referenced by WakeupHandle::WakeupHandle().
{
     SetBlocking(FD(), blocking);
 }
void FileHandle::SetBlocking (int fd, bool blocking) static inherited
a convenience method that allows one to set the same blocking parameters for a file descriptor without setting it inside a FileHandle.
Parameters
fd the file descriptor
blocking true or false see SetBlock
Definition at line 115 of file FileHandle.cc.
{
     int flags = fcntl(fd, F_GETFL, 0);
     if (-1 == flags) { throw ErrnoException(); }
     if (blocking) {
         flags &= ~O_NONBLOCK;
     } else {
         flags |= O_NONBLOCK;
     }
     if (fcntl(fd, F_SETFL, flags) != 0) {
         throw ErrnoException();
     }
 }
void ServerSocketHandle::SetReuseAddr (bool reuse = true) inline
Turn on reuse of the address. Only takes effect if set before Listen.
Definition at line 70 of file ServerSocketHandle.h.
References reuse_addr.
Referenced by CPN::RemoteContextDaemon::RemoteContextDaemon().
 { reuse_addr = true; }
unsigned FileHandle::Write (const void * ptr, unsigned len) inherited
Write data to the file descriptor.
Note
All write functions will set Writeable to false if they write less than the amount requested or if the file is in non blocking mode and the write returned would block.
Parameters
ptr pointer to beginning of data to write
len length of data to write
Returns
number of bytes written
Definition at line 225 of file FileHandle.cc.
References FileHandle::fd, FileHandle::file_lock, and FileHandle::Writeable().
Referenced by CPN::ConnectionServer::ConnectWriter(), CPN::RemoteContextDaemon::Client::Send(), CPN::RemoteContext::SendMessage(), and CPN::RemoteQueue::WriteBytes().
{
     int filed;
     {
         ALock al(file_lock);
         if (fd == -1) { return 0; }
         filed = fd;
     }
     unsigned written = 0;
     int num = write(filed, ptr, len);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN: // Would block
         //case EWOULDBLOCK:
             Writeable(false);
         case EINTR: // Returned because of signal
         case ENOMEM:
         case ENOBUFS: // Buffers are full
             break;
         case EPIPE:
         case EBADF:
         case EFAULT:
         case EFBIG:
         case EINVAL:
         case EIO:
         case ENOSPC:
         default:
             throw ErrnoException(error);
         }
     } else {
         if (unsigned(num) < len) { Writeable(false); }
         written = num;
     }
     return written;
 }
bool FileHandle::Writeable (bool w) inline inherited
Set that this file is currently writeable or not.
Parameters
w true or false
Returns
the new writeable status
Definition at line 97 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::writeable.
Referenced by FileHandle::Poll().
 { ALock al(file_lock); return writeable = w; }
bool FileHandle::Writeable () const inline inherited
Gives the current writability status of the file.
Returns
true if it is known that a write will not block
Definition at line 102 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::writeable.
Referenced by FileHandle::OnWriteable(), SocketHandle::Send(), WakeupHandle::WakeupHandle(), FileHandle::Write(), and FileHandle::Writev().
 { ALock al(file_lock); return writeable; }
unsigned FileHandle::Writev (const iovec * iov, int iovcnt) inherited
scatter gather io version of Write
Returns
see Write
Definition at line 261 of file FileHandle.cc.
References FileHandle::fd, FileHandle::file_lock, and FileHandle::Writeable().
Referenced by CPN::RemoteQueue::WriteBytes().
{
     int filed;
     {
         ALock al(file_lock);
         if (fd == -1) { return 0; }
         filed = fd;
     }
     unsigned written = 0;
     int num = writev(filed, iov, iovcnt);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN:
             Writeable(false);
         case EINTR:
         case ENOMEM:
         case ENOBUFS:
             break;
         default:
             throw ErrnoException(error);
         }
     } else {
         unsigned len = 0;
         for (int i = 0; i < iovcnt; ++i) {
             len += iov[i].iov_len;
         }
         if (unsigned(num) < len) { Writeable(false); }
         written = num;
     }
     return written;
 }
Member Data Documentation
bool FileHandle::eof protected inherited
Definition at line 217 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Eof(), FileHandle::Good(), FileHandle::Read(), FileHandle::Readv(), SocketHandle::Recv(), and FileHandle::Reset().
int FileHandle::fd protected inherited
Definition at line 214 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Closed(), FileHandle::FD(), FileHandle::Good(), FileHandle::Poll(), FileHandle::Read(), FileHandle::Readv(), SocketHandle::Recv(), FileHandle::Reset(), SocketHandle::Send(), FileHandle::Write(), FileHandle::Writev(), and FileHandle::~FileHandle().
PthreadMutex FileHandle::file_lock mutable protected inherited
Definition at line 213 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Closed(), FileHandle::Eof(), FileHandle::FD(), FileHandle::Good(), FileHandle::Read(), FileHandle::Readable(), FileHandle::Readv(), SocketHandle::Recv(), FileHandle::Reset(), SocketHandle::Send(), WakeupHandle::SendWakeup(), FileHandle::Write(), FileHandle::Writeable(), and FileHandle::Writev().
bool FileHandle::readable protected inherited
Definition at line 215 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Read(), FileHandle::Readable(), FileHandle::Readv(), SocketHandle::Recv(), and FileHandle::Reset().
bool ServerSocketHandle::reuse_addr private
Definition at line 75 of file ServerSocketHandle.h.
Referenced by GetReuseAddr(), Listen(), and SetReuseAddr().
bool FileHandle::writeable protected inherited
Definition at line 216 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Reset(), and FileHandle::Writeable().
The documentation for this class was generated from the following files:
include/cpn/io/ServerSocketHandle.h
lib/io/ServerSocketHandle.cc