CPN: CPN::KernelAttr Class Reference
CPN::KernelAttr Class Reference
The attribute for the Kernel.
#include <KernelAttr.h>
Public Member Functions
KernelAttr (const std::string &name_)
Create a new KernelAttr. There is only one required attributed and that is to give the Kernel a name.
KernelAttr (const char *name_)
KernelAttr & SetName (const std::string &n)
KernelAttr & SetHostName (const std::string &hn)
KernelAttr & SetServName (const std::string &sn)
KernelAttr & SetContext (shared_ptr< Context > ctx)
KernelAttr & SetRemoteEnabled (bool en)
KernelAttr & UseD4R (bool enable)
KernelAttr & SwallowBrokenQueueExceptions (bool enable)
KernelAttr & GrowQueueMaxThreshold (bool enable)
KernelAttr & AddSharedLib (const std::string &lib)
KernelAttr & AddNodeList (const std::string &list)
KernelAttr & AddNodeSearchPath (const std::string &p)
const std::string & GetName () const
const std::string & GetHostName () const
const std::string & GetServName () const
shared_ptr< Context > GetContext () const
bool GetRemoteEnabled () const
bool UseD4R () const
bool SwallowBrokenQueueExceptions () const
bool GrowQueueMaxThreshold () const
const std::vector< std::string > & GetSharedLibs () const
const std::vector< std::string > & GetNodeLists () const
const std::vector< std::string > & GetNodeSearchPaths () const
Private Attributes
std::string name
std::string hostname
std::string servname
shared_ptr< Context > context
bool remote_enabled
bool useD4R
bool swallowbrokenqueue
bool growmaxthresh
std::vector< std::string > sharedlibs
std::vector< std::string > nodelists
std::vector< std::string > searchpaths
Detailed Description
The attribute for the Kernel.
Possible parameters to the Kernel are the name, hostname, servname, and context. Only name is required.
Definition at line 40 of file KernelAttr.h.
Constructor & Destructor Documentation
CPN::KernelAttr::KernelAttr (const std::string & name_) inline
Create a new KernelAttr. There is only one required attributed and that is to give the Kernel a name.
Parameters
name_ the name for the Kernel.
Definition at line 46 of file KernelAttr.h.
             : name(name_),
             hostname("localhost"),
             servname(""),
             remote_enabled(false),
             useD4R(true), swallowbrokenqueue(false),
             growmaxthresh(true)
         {}
CPN::KernelAttr::KernelAttr (const char * name_) inline
Definition at line 55 of file KernelAttr.h.
             : name(name_),
             hostname("localhost"),
             servname(""),
             remote_enabled(false),
             useD4R(true), swallowbrokenqueue(false),
             growmaxthresh(true)
         {}
Member Function Documentation
KernelAttr& CPN::KernelAttr::AddNodeList (const std::string & list) inline
Definition at line 109 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             nodelists.push_back(list);
             return *this;
         }
KernelAttr& CPN::KernelAttr::AddNodeSearchPath (const std::string & p) inline
Definition at line 114 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             searchpaths.push_back(p);
             return *this;
         }
KernelAttr& CPN::KernelAttr::AddSharedLib (const std::string & lib) inline
Definition at line 104 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             sharedlibs.push_back(lib);
             return *this;
         }
shared_ptr<Context> CPN::KernelAttr::GetContext () const inline
Definition at line 125 of file KernelAttr.h.
 { return context; }
const std::string& CPN::KernelAttr::GetHostName () const inline
Definition at line 121 of file KernelAttr.h.
Referenced by CPN::Kernel::Kernel().
 { return hostname; }
const std::string& CPN::KernelAttr::GetName () const inline
Definition at line 119 of file KernelAttr.h.
 { return name; }
const std::vector<std::string>& CPN::KernelAttr::GetNodeLists () const inline
Definition at line 137 of file KernelAttr.h.
Referenced by CPN::Kernel::Kernel().
 { return nodelists; }
const std::vector<std::string>& CPN::KernelAttr::GetNodeSearchPaths () const inline
Definition at line 139 of file KernelAttr.h.
Referenced by CPN::Kernel::Kernel().
 { return searchpaths; }
bool CPN::KernelAttr::GetRemoteEnabled () const inline
Definition at line 127 of file KernelAttr.h.
 { return remote_enabled; }
const std::string& CPN::KernelAttr::GetServName () const inline
Definition at line 123 of file KernelAttr.h.
Referenced by CPN::Kernel::Kernel().
 { return servname; }
const std::vector<std::string>& CPN::KernelAttr::GetSharedLibs () const inline
Definition at line 135 of file KernelAttr.h.
Referenced by CPN::Kernel::Kernel().
 { return sharedlibs; }
KernelAttr& CPN::KernelAttr::GrowQueueMaxThreshold (bool enable) inline
Definition at line 99 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             growmaxthresh = enable;
             return *this;
         }
bool CPN::KernelAttr::GrowQueueMaxThreshold () const inline
Definition at line 133 of file KernelAttr.h.
 { return growmaxthresh; }
KernelAttr& CPN::KernelAttr::SetContext (shared_ptr< Context > ctx) inline
Definition at line 79 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             context = ctx;
             return *this;
         }
KernelAttr& CPN::KernelAttr::SetHostName (const std::string & hn) inline
Definition at line 69 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             hostname = hn;
             return *this;
         }
KernelAttr& CPN::KernelAttr::SetName (const std::string & n) inline
Definition at line 64 of file KernelAttr.h.
{
             name = n;
             return *this;
         }
KernelAttr& CPN::KernelAttr::SetRemoteEnabled (bool en) inline
Definition at line 84 of file KernelAttr.h.
{
             remote_enabled = en;
             return *this;
         }
KernelAttr& CPN::KernelAttr::SetServName (const std::string & sn) inline
Definition at line 74 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             servname = sn;
             return *this;
         }
KernelAttr& CPN::KernelAttr::SwallowBrokenQueueExceptions (bool enable) inline
Definition at line 94 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             swallowbrokenqueue = enable;
             return *this;
         }
bool CPN::KernelAttr::SwallowBrokenQueueExceptions () const inline
Definition at line 131 of file KernelAttr.h.
 { return swallowbrokenqueue; }
KernelAttr& CPN::KernelAttr::UseD4R (bool enable) inline
Definition at line 89 of file KernelAttr.h.
Referenced by CPN::VariantCPNLoader::GetKernelAttr().
{
             useD4R = enable;
             return *this;
         }
bool CPN::KernelAttr::UseD4R () const inline
Definition at line 129 of file KernelAttr.h.
 { return useD4R; }
Member Data Documentation
shared_ptr<Context> CPN::KernelAttr::context private
Definition at line 144 of file KernelAttr.h.
bool CPN::KernelAttr::growmaxthresh private
Definition at line 148 of file KernelAttr.h.
std::string CPN::KernelAttr::hostname private
Definition at line 142 of file KernelAttr.h.
std::string CPN::KernelAttr::name private
Definition at line 141 of file KernelAttr.h.
std::vector<std::string> CPN::KernelAttr::nodelists private
Definition at line 150 of file KernelAttr.h.
bool CPN::KernelAttr::remote_enabled private
Definition at line 145 of file KernelAttr.h.
std::vector<std::string> CPN::KernelAttr::searchpaths private
Definition at line 151 of file KernelAttr.h.
std::string CPN::KernelAttr::servname private
Definition at line 143 of file KernelAttr.h.
std::vector<std::string> CPN::KernelAttr::sharedlibs private
Definition at line 149 of file KernelAttr.h.
bool CPN::KernelAttr::swallowbrokenqueue private
Definition at line 147 of file KernelAttr.h.
bool CPN::KernelAttr::useD4R private
Definition at line 146 of file KernelAttr.h.
The documentation for this class was generated from the following file:
include/cpn/KernelAttr.h