CPN: CPN::NodeAttr Class Reference
CPN::NodeAttr Class Reference
Attributes for a node.
#include <NodeAttr.h>
Public Member Functions
NodeAttr (const std::string &name_, const std::string &nodetype_)
NodeAttr & SetName (const std::string &name_)
NodeAttr & SetTypeName (const std::string &nodetype_)
NodeAttr & SetKernel (const std::string &kname)
NodeAttr & SetKernelKey (Key_t k)
NodeAttr & SetParam (const std::string &key, const std::string value)
template<typename T >
NodeAttr & SetParam (const std::string &key, T value)
NodeAttr & SetKey (Key_t key_)
const std::string & GetKernel () const
Key_t GetKernelKey () const
const std::string & GetName () const
const std::string & GetTypeName () const
const std::map< std::string,
std::string > & GetParams () const
Key_t GetKey () const
Private Attributes
std::string kernelname
Key_t kernelkey
std::string name
std::string nodetype
std::map< std::string,
std::string > params
Key_t key
Detailed Description
Attributes for a node.
This structure contains all the attributes and parameters a node needs to start up. Note that this structure is used to pass to the Kernel to create a node and that fields like key are set by the Kernel.
The only required parameters are the name and node type.
The other parameters that the user may set are:
The kernel for the node can be set as either the kernel name or the kernel key. If the kernel key is set kernel name is ignored. See SetKernel and SetKernelKey.
The parameters sent to the node. See SetParam and GetParam
Note that the key attribute are set by the kernel when the node is to be created and such are overwritten.
Definition at line 58 of file NodeAttr.h.
Constructor & Destructor Documentation
CPN::NodeAttr::NodeAttr (const std::string & name_, const std::string & nodetype_) inline
Definition at line 60 of file NodeAttr.h.
             : kernelname(),
             kernelkey(0),
             name(name_),
             nodetype(nodetype_),
             key(0)
         {}
Member Function Documentation
const std::string& CPN::NodeAttr::GetKernel () const inline
Definition at line 107 of file NodeAttr.h.
Referenced by CPN::Kernel::CreateNode(), and CPN::RemoteContextClient::SendCreateNode().
 { return kernelname; }
Key_t CPN::NodeAttr::GetKernelKey () const inline
Definition at line 108 of file NodeAttr.h.
Referenced by CPN::Kernel::CreateNode().
 { return kernelkey; }
Key_t CPN::NodeAttr::GetKey () const inline
Definition at line 116 of file NodeAttr.h.
Referenced by CPN::Kernel::InternalCreateNode(), and CPN::RemoteContextClient::SendCreateNode().
 { return key; }
const std::string& CPN::NodeAttr::GetName () const inline
Definition at line 110 of file NodeAttr.h.
Referenced by CPN::Kernel::CreateNode(), CPN::VariantCPNLoader::LoadNode(), and CPN::RemoteContextClient::SendCreateNode().
 { return name; }
const std::map<std::string, std::string>& CPN::NodeAttr::GetParams () const inline
Definition at line 114 of file NodeAttr.h.
Referenced by CPN::RemoteContextClient::SendCreateNode().
 { return params; }
const std::string& CPN::NodeAttr::GetTypeName () const inline
Definition at line 112 of file NodeAttr.h.
Referenced by CPN::Kernel::InternalCreateNode(), and CPN::RemoteContextClient::SendCreateNode().
 { return nodetype; }
NodeAttr& CPN::NodeAttr::SetKernel (const std::string & kname) inline
Definition at line 79 of file NodeAttr.h.
Referenced by CPN::VariantCPNLoader::LoadNode(), and CPN::MsgToNodeAttr().
{
             kernelname = kname;
             return *this;
         }
NodeAttr& CPN::NodeAttr::SetKernelKey (Key_t k) inline
Definition at line 84 of file NodeAttr.h.
Referenced by CPN::Kernel::CreateNode().
{
             kernelkey = k;
             return *this;
         }
NodeAttr& CPN::NodeAttr::SetKey (Key_t key_) inline
Definition at line 102 of file NodeAttr.h.
Referenced by CPN::Kernel::CreateNode(), and CPN::MsgToNodeAttr().
{
             key = key_;
             return *this;
         }
NodeAttr& CPN::NodeAttr::SetName (const std::string & name_) inline
Definition at line 69 of file NodeAttr.h.
{
             name = name_;
             return *this;
         }
NodeAttr& CPN::NodeAttr::SetParam (const std::string & key, const std::string value) inline
Definition at line 89 of file NodeAttr.h.
Referenced by CPN::VariantCPNLoader::LoadNode(), and CPN::MsgToNodeAttr().
{
             params[key] = value;
             return *this;
         }
template<typename T > NodeAttr& CPN::NodeAttr::SetParam (const std::string & key, T value) inline
Definition at line 95 of file NodeAttr.h.
{
             std::ostringstream oss;
             oss << value;
             params[key] = oss.str();
             return *this;
         }
NodeAttr& CPN::NodeAttr::SetTypeName (const std::string & nodetype_) inline
Definition at line 74 of file NodeAttr.h.
{
             nodetype = nodetype_;
             return *this;
         }
Member Data Documentation
Key_t CPN::NodeAttr::kernelkey private
Definition at line 120 of file NodeAttr.h.
std::string CPN::NodeAttr::kernelname private
Definition at line 119 of file NodeAttr.h.
Key_t CPN::NodeAttr::key private
Definition at line 124 of file NodeAttr.h.
std::string CPN::NodeAttr::name private
Definition at line 121 of file NodeAttr.h.
std::string CPN::NodeAttr::nodetype private
Definition at line 122 of file NodeAttr.h.
std::map<std::string, std::string> CPN::NodeAttr::params private
Definition at line 123 of file NodeAttr.h.
The documentation for this class was generated from the following file:
include/cpn/NodeAttr.h