CPN: CPN::ExternalEndpoint Class Reference
CPN::ExternalEndpoint Class Reference
Public Member Functions
ExternalEndpoint (const std::string &name, Key_t nodekey, shared_ptr< Context > context, bool iswriter_)
virtual ~ExternalEndpoint ()
bool IsWriter () const
const std::string & GetName () const
Key_t GetKey () const
shared_ptr< QueueReader > GetIQueue (const std::string &portname)
This method is for use by the user to aquire a reader endpoint. This function blocks until the CPN::Kernel hands this node the queue associated with the endpoint.
shared_ptr< QueueWriter > GetOQueue (const std::string &portname)
This method is for use by the user to aquire a writer endpoint. This function blocks until the CPN::Kernel hands this node the queue associated with the endpoint.
void CreateReader (shared_ptr< QueueBase > q)
for use by the CPN::Kernel to create a new read endpoint.
void CreateWriter (shared_ptr< QueueBase > q)
for use by the CPN::Kernel to create a new writer endpoint.
void NotifyTerminate ()
Called by the kernel when it is shutting down.
virtual void Shutdown ()
Perform actions (like joining a thread) before destruction.
virtual bool IsPurePseudo ()
virtual void LogState ()
For debugging ONLY!
Protected Attributes
Logger logger
Private Attributes
bool iswriter
Detailed Description
Definition at line 166 of file Kernel.cc.
Constructor & Destructor Documentation
CPN::ExternalEndpoint::ExternalEndpoint (const std::string & name, Key_t nodekey, shared_ptr< Context > context, bool iswriter_) inline
Definition at line 168 of file Kernel.cc.
             : PseudoNode(name, nodekey, context), iswriter(iswriter_) {}
virtual CPN::ExternalEndpoint::~ExternalEndpoint () inline virtual
Definition at line 171 of file Kernel.cc.
 {}
Member Function Documentation
void CPN::PseudoNode::CreateReader (shared_ptr< QueueBase > q) inherited
for use by the CPN::Kernel to create a new read endpoint.
Definition at line 55 of file PseudoNode.cc.
References ASSERT, CPN::PseudoNode::cond, CPN::PseudoNode::d4rnode, CPN::PseudoNode::lock, CPN::PseudoNode::readermap, and Sync::ReentrantCondition::Signal().
{
         Sync::AutoReentrantLock arl(lock);
         Key_t readerkey = q->GetReaderKey();
         d4rnode->AddReader(q);
         q->SetReaderNode(d4rnode);
         q->SignalReaderTagChanged();
         ASSERT(readermap.find(readerkey) == readermap.end(), "The reader already exists");
         shared_ptr<QueueReader> reader;
         reader = shared_ptr<QueueReader>(new QueueReader(this, q));
         readermap.insert(std::make_pair(readerkey, reader));
         cond.Signal();
     }
void CPN::PseudoNode::CreateWriter (shared_ptr< QueueBase > q) inherited
for use by the CPN::Kernel to create a new writer endpoint.
Definition at line 68 of file PseudoNode.cc.
References ASSERT, CPN::PseudoNode::cond, CPN::PseudoNode::d4rnode, CPN::PseudoNode::lock, Sync::ReentrantCondition::Signal(), and CPN::PseudoNode::writermap.
{
         Sync::AutoReentrantLock arl(lock);
         Key_t writerkey = q->GetWriterKey();
         d4rnode->AddWriter(q);
         q->SetWriterNode(d4rnode);
         q->SignalWriterTagChanged();
         ASSERT(writermap.find(writerkey) == writermap.end(), "The writer already exists.");
         shared_ptr<QueueWriter> writer;
         writer = shared_ptr<QueueWriter>(new QueueWriter(this, q));
         writermap.insert(std::make_pair(writerkey, writer));
         cond.Signal();
     }
shared_ptr< QueueReader > CPN::PseudoNode::GetIQueue (const std::string & portname) inherited
This method is for use by the user to aquire a reader endpoint. This function blocks until the CPN::Kernel hands this node the queue associated with the endpoint.
Parameters
portname the port name of the reader to get.
Returns
a shared pointer to a reader for he given endpoint name
Definition at line 43 of file PseudoNode.cc.
References CPN::PseudoNode::context, CPN::PseudoNode::GetReader(), and CPN::PseudoNode::nodekey.
{
         context->CheckTerminated();
         Key_t ekey = context->GetCreateReaderKey(nodekey, portname);
         return GetReader(ekey);
     }
Key_t CPN::PseudoNode::GetKey () const inline inherited
Returns
the process network wide unique id for this node
Definition at line 43 of file PseudoNode.h.
Referenced by CPN::NodeBase::EntryPoint().
 { return nodekey; }
const std::string& CPN::PseudoNode::GetName () const inline inherited
Returns
the unique name of this node
Definition at line 40 of file PseudoNode.h.
Referenced by CPN::NodeBase::EntryPoint(), and CPN::NodeBase::GetParam().
 { return name; }
shared_ptr< QueueWriter > CPN::PseudoNode::GetOQueue (const std::string & portname) inherited
This method is for use by the user to aquire a writer endpoint. This function blocks until the CPN::Kernel hands this node the queue associated with the endpoint.
Parameters
portname the port name fo the writer to get.
Returns
a shared pointer to a writer for the given endpoint name.
Definition at line 49 of file PseudoNode.cc.
References CPN::PseudoNode::context, CPN::PseudoNode::GetWriter(), and CPN::PseudoNode::nodekey.
{
         context->CheckTerminated();
         Key_t ekey = context->GetCreateWriterKey(nodekey, portname);
         return GetWriter(ekey);
     }
bool CPN::PseudoNode::IsPurePseudo () virtual inherited
Reimplemented in CPN::NodeBase.
Definition at line 163 of file PseudoNode.cc.
{
         return true;
     }
bool CPN::ExternalEndpoint::IsWriter () const inline
Definition at line 173 of file Kernel.cc.
References iswriter.
 { return iswriter; }
void CPN::PseudoNode::LogState () virtual inherited
For debugging ONLY!
Reimplemented in CPN::NodeBase.
Definition at line 167 of file PseudoNode.cc.
References D4R::Tag::Count(), CPN::PseudoNode::d4rnode, Logger::Error(), D4R::Tag::Key(), CPN::PseudoNode::logger, CPN::PseudoNode::nodekey, D4R::Tag::QueueKey(), D4R::Tag::QueueSize(), CPN::PseudoNode::readermap, and CPN::PseudoNode::writermap.
Referenced by CPN::NodeBase::LogState().
{
         logger.Error("Logging (key: %llu), %u readers, %u writers",
                 nodekey, readermap.size(), writermap.size());
         D4R::Tag tag = d4rnode->GetPrivateTag();
         logger.Error("Private key: (%llu, %llu, %llu, %llu)", tag.Count(), tag.Key(), tag.QueueSize(), tag.QueueKey());
         tag = d4rnode->GetPublicTag();
         logger.Error("Public key: (%llu, %llu, %llu, %llu)", tag.Count(), tag.Key(), tag.QueueSize(), tag.QueueKey());
         ReaderMap::iterator r = readermap.begin();
         while (r != readermap.end()) {
             r->second->GetQueue()->LogState();
             ++r;
         }
         WriterMap::iterator w = writermap.begin();
         while (w != writermap.end()) {
             w->second->GetQueue()->LogState();
             ++w;
         }
     }
void CPN::PseudoNode::NotifyTerminate () inherited
Called by the kernel when it is shutting down.
Definition at line 123 of file PseudoNode.cc.
References CPN::PseudoNode::cond, CPN::PseudoNode::lock, CPN::PseudoNode::readermap, Sync::ReentrantCondition::Signal(), and CPN::PseudoNode::writermap.
{
         Sync::AutoReentrantLock arl(lock);
         cond.Signal();
         WriterMap::iterator witr = writermap.begin();
         while (witr != writermap.end()) { (witr++)->second->NotifyTerminate(); }
         ReaderMap::iterator ritr = readermap.begin();
         while (ritr != readermap.end()) { (ritr++)->second->NotifyTerminate(); }
     }
void CPN::PseudoNode::Shutdown () virtual inherited
Perform actions (like joining a thread) before destruction.
Reimplemented in CPN::NodeBase.
Definition at line 81 of file PseudoNode.cc.
References CPN::PseudoNode::lock, CPN::PseudoNode::readermap, AutoLock< Lockable >::Unlock(), and CPN::PseudoNode::writermap.
Referenced by CPN::NodeBase::Shutdown().
{
         Sync::AutoReentrantLock arl(lock);
         ReaderMap readers;
         readers.swap(readermap);
         WriterMap writers;
         writers.swap(writermap);
         arl.Unlock();
         for (ReaderMap::iterator i = readers.begin(); i != readers.end(); ++i) {
             i->second->GetQueue()->ShutdownReader();
         }
         for (WriterMap::iterator i = writers.begin(); i != writers.end(); ++i) {
             i->second->GetQueue()->ShutdownWriter();
         }
         readers.clear();
         writers.clear();
     }
Member Data Documentation
bool CPN::ExternalEndpoint::iswriter private
Definition at line 175 of file Kernel.cc.
Referenced by IsWriter().
Logger CPN::PseudoNode::logger protected inherited
Definition at line 76 of file PseudoNode.h.
Referenced by CPN::NodeBase::EntryPoint(), CPN::PseudoNode::LogState(), and CPN::NodeBase::LogState().
The documentation for this class was generated from the following file:
lib/Kernel.cc