CPN: Logger Class Reference
Logger Class Reference
Logger object that is used for forwarding log messages.
#include <Logger.h>
Public Types
enum {
ERROR = 100, WARNING = 75, INFO = 50, DEBUG = 25,
TRACE = 0
}
Public Member Functions
Logger ()
Logger (int dfltlvl)
Logger (LoggerOutput *lo, int dfltlvl)
Logger (LoggerOutput *lo, int dfltlevel, const std::string &nm)
virtual ~Logger ()
int LogLevel () const
int LogLevel (int level)
int DefaultLevel () const
int DefaultLevel (int level)
int Adjust () const
int Adjust (int a)
const std::string & Name () const
const std::string & Name (const std::string &nm)
LoggerOutput * Output ()
LoggerOutput * Output (LoggerOutput *output)
virtual void Log (int level, const std::string &msg)
Log a message to this outputer.
void Log (const std::string &msg)
void Logf (int level, const char *fmt,...)
void vLogf (int level, const char *fmt, va_list ap)
void Logf (const char *fmt,...)
void Error (const char *fmt,...)
void Warn (const char *fmt,...)
void Info (const char *fmt,...)
void Debug (const char *fmt,...)
void Trace (const char *fmt,...)
Protected Member Functions
Logger (const Logger &)
Logger & operator= (const Logger &)
Private Attributes
Sync::ReentrantLock lock
LoggerOutput * logout
int loglevel
int defaultlevel
int adjust
std::string name
Detailed Description
Logger object that is used for forwarding log messages.
Definition at line 57 of file Logger.h.
Member Enumeration Documentation
anonymous enum
Enumerator
ERROR
WARNING
INFO
DEBUG
TRACE
Definition at line 59 of file Logger.h.
          {
         ERROR = 100,
         WARNING = 75,
         INFO = 50,
         DEBUG = 25,
         TRACE = 0
     };
Constructor & Destructor Documentation
Logger::Logger ()
Definition at line 34 of file Logger.cc.
     : logout(0), loglevel(WARNING), defaultlevel(INFO), adjust(0)
 {}
Logger::Logger (int dfltlvl)
Definition at line 38 of file Logger.cc.
     : logout(0), loglevel(WARNING), defaultlevel(dfltlvl), adjust(0)
 {}
Logger::Logger (LoggerOutput * lo, int dfltlvl)
Definition at line 44 of file Logger.cc.
References ASSERT, LoggerOutput::LogLevel(), loglevel, and logout.
     : logout(lo), loglevel(WARNING), defaultlevel(dfltlvl), adjust(0)
 {
     ASSERT(logout);
     loglevel = logout->LogLevel();
 }
Logger::Logger (LoggerOutput * lo, int dfltlevel, const std::string & nm)
Definition at line 51 of file Logger.cc.
References ASSERT, LoggerOutput::LogLevel(), loglevel, and logout.
     : logout(lo), loglevel(WARNING), defaultlevel(dfltlevel), name(nm)
 {
     ASSERT(logout);
     loglevel = logout->LogLevel();
 }
Logger::~Logger () virtual
Definition at line 42 of file Logger.cc.
 {}
Logger::Logger (const Logger &) protected
Member Function Documentation
int Logger::Adjust () const
Definition at line 78 of file Logger.cc.
References adjust, and lock.
{
     Sync::AutoReentrantLock arl(lock);
     return adjust;
 }
int Logger::Adjust (int a)
Definition at line 83 of file Logger.cc.
References adjust, and lock.
{
     Sync::AutoReentrantLock arl(lock);
     return adjust = a;
 }
void Logger::Debug (const char * fmt, ...)
Definition at line 186 of file Logger.cc.
References DEBUG, lock, loglevel, and vLogf().
Referenced by CPN::QueueBase::Detect(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteQueue::Read(), CPN::RemoteQueue::SendEndOfReadPacket(), and CPN::RemoteQueue::SendEndOfWritePacket().
{
     Sync::AutoReentrantLock arl(lock);
     if (DEBUG < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(DEBUG, fmt, ap);
     va_end(ap);
 }
int Logger::DefaultLevel () const
Definition at line 68 of file Logger.cc.
References defaultlevel, and lock.
{
     Sync::AutoReentrantLock arl(lock);
     return defaultlevel;
 }
int Logger::DefaultLevel (int level)
Definition at line 73 of file Logger.cc.
References defaultlevel, and lock.
{
     Sync::AutoReentrantLock arl(lock);
     return defaultlevel = level;
 }
void Logger::Error (const char * fmt, ...)
Definition at line 159 of file Logger.cc.
References ERROR, lock, loglevel, and vLogf().
Referenced by CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), CPN::PseudoNode::LogState(), CPN::RemoteQueue::LogState(), CPN::ConnectionServer::LogState(), CPN::NodeBase::LogState(), CPN::QueueBase::LogState(), CPN::Kernel::LogState(), and CPN::ConnectionServer::Poll().
{
     Sync::AutoReentrantLock arl(lock);
     if (ERROR < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(ERROR, fmt, ap);
     va_end(ap);
 }
void Logger::Info (const char * fmt, ...)
Definition at line 177 of file Logger.cc.
References INFO, lock, loglevel, and vLogf().
Referenced by CPN::NodeBase::EntryPoint(), and CPN::Kernel::Kernel().
{
     Sync::AutoReentrantLock arl(lock);
     if (INFO < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(INFO, fmt, ap);
     va_end(ap);
 }
void Logger::Log (int level, const std::string & msg) virtual
Log a message to this outputer.
Parameters
level the level of this message
msg the message
Implements LoggerOutput.
Definition at line 108 of file Logger.cc.
References adjust, lock, LoggerOutput::Log(), loglevel, logout, and name.
Referenced by vLogf().
{
     Sync::AutoReentrantLock arl(lock);
     if (level < loglevel) { return; }
     if (logout) { logout->Log(level + adjust, name + ":" + msg); }
 }
void Logger::Log (const std::string & msg) inline
Definition at line 89 of file Logger.h.
References defaultlevel, and Log().
Referenced by Log().
 { Log(defaultlevel, msg); }
void Logger::Logf (int level, const char * fmt, ...)
Definition at line 114 of file Logger.cc.
References lock, loglevel, and vLogf().
{
     Sync::AutoReentrantLock arl(lock);
     if (level < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(level, fmt, ap);
     va_end(ap);
 }
void Logger::Logf (const char * fmt, ...)
Definition at line 123 of file Logger.cc.
References defaultlevel, lock, loglevel, and vLogf().
{
     Sync::AutoReentrantLock arl(lock);
     if (defaultlevel < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(defaultlevel, fmt, ap);
     va_end(ap);
 }
int Logger::LogLevel () const virtual
Returns
the current log level
Implements LoggerOutput.
Definition at line 58 of file Logger.cc.
References lock, and loglevel.
Referenced by CPN::RemoteQueue::InternalCheckStatus(), and CPN::Kernel::Kernel().
{
     Sync::AutoReentrantLock arl(lock);
     return loglevel;
 }
int Logger::LogLevel (int level) virtual
Parameters
level the new log level
Returns
the new log level
Implements LoggerOutput.
Definition at line 63 of file Logger.cc.
References lock, and loglevel.
{
     Sync::AutoReentrantLock arl(lock);
     return loglevel = level;
 }
const std::string & Logger::Name () const
Definition at line 88 of file Logger.cc.
References lock, and name.
Referenced by CPN::NodeBase::EntryPoint(), CPN::Kernel::Kernel(), CPN::QueueBase::QueueBase(), and CPN::RemoteQueue::RemoteQueue().
{
     Sync::AutoReentrantLock arl(lock);
     return name;
 }
const std::string & Logger::Name (const std::string & nm)
Definition at line 93 of file Logger.cc.
References lock, and name.
{
     Sync::AutoReentrantLock arl(lock);
     return name = nm;
 }
Logger& Logger::operator= (const Logger &) protected
LoggerOutput * Logger::Output ()
Definition at line 98 of file Logger.cc.
References lock, and logout.
Referenced by CPN::Kernel::Kernel().
{
     Sync::AutoReentrantLock arl(lock);
     return logout;
 }
LoggerOutput * Logger::Output (LoggerOutput * output)
Definition at line 103 of file Logger.cc.
References lock, and logout.
{
     Sync::AutoReentrantLock arl(lock);
     return logout = output;
 }
void Logger::Trace (const char * fmt, ...)
Definition at line 195 of file Logger.cc.
References lock, loglevel, TRACE, and vLogf().
Referenced by CPN::RemoteQueue::RemoteQueue(), ScopeTrace::ScopeTrace(), CPN::RemoteQueue::~RemoteQueue(), and ScopeTrace::~ScopeTrace().
{
     Sync::AutoReentrantLock arl(lock);
     if (TRACE < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(TRACE, fmt, ap);
     va_end(ap);
 }
void Logger::vLogf (int level, const char * fmt, va_list ap)
Definition at line 132 of file Logger.cc.
References lock, Log(), and loglevel.
Referenced by Debug(), Error(), Info(), Logf(), Trace(), and Warn().
{
     Sync::AutoReentrantLock arl(lock);
     if (level < loglevel) { return; }
     // This code was based on an example of how
     // to use vsnprintf in the unix man pages.
     std::vector<char> buff(128);
     while (1) {
         /* Try to print in the allocated space. */
         va_list ap_copy;
         va_copy(ap_copy, ap);
         int n = vsnprintf(&buff[0], buff.size(), fmt, ap_copy);
         /* If that worked, return the string. */
         if (n > -1 && unsigned(n) < buff.size()) {
             std::string ret = &buff[0];
             Log(level, ret);
             return;
         }
         /* Else try again with more space. */
         if (n > -1) { /* glibc 2.1 */ /* precisely what is needed */
             buff.resize(n+1);
         }
         else { /* glibc 2.0 */ /* twice the old size */
             buff.resize(buff.size()*2);
         }
     }
 }
void Logger::Warn (const char * fmt, ...)
Definition at line 168 of file Logger.cc.
References lock, loglevel, vLogf(), and WARNING.
Referenced by CPN::RemoteQueue::EnqueuePacket(), CPN::Kernel::EntryPoint(), and CPN::Kernel::NodeTerminated().
{
     Sync::AutoReentrantLock arl(lock);
     if (WARNING < loglevel) { return; }
     va_list ap;
     va_start(ap, fmt);
     vLogf(WARNING, fmt, ap);
     va_end(ap);
 }
Member Data Documentation
int Logger::adjust private
Definition at line 111 of file Logger.h.
Referenced by Adjust(), and Log().
int Logger::defaultlevel private
Definition at line 110 of file Logger.h.
Referenced by DefaultLevel(), Log(), and Logf().
Sync::ReentrantLock Logger::lock private
Definition at line 107 of file Logger.h.
Referenced by Adjust(), Debug(), DefaultLevel(), Error(), Info(), Log(), Logf(), LogLevel(), Name(), Output(), Trace(), vLogf(), and Warn().
int Logger::loglevel private
Definition at line 109 of file Logger.h.
Referenced by Debug(), Error(), Info(), Log(), Logf(), Logger(), LogLevel(), Trace(), vLogf(), and Warn().
LoggerOutput* Logger::logout private
Definition at line 108 of file Logger.h.
Referenced by Log(), Logger(), and Output().
std::string Logger::name private
Definition at line 112 of file Logger.h.
Referenced by Log(), and Name().
The documentation for this class was generated from the following files:
include/cpn/utils/Logger.h
lib/utils/Logger.cc