CPN: PthreadCondition Class Reference
PthreadCondition Class Reference
#include <PthreadCondition.h>
Public Member Functions
PthreadCondition (void)
PthreadCondition (const PthreadConditionAttr &condattr)
~PthreadCondition (void)
operator pthread_cond_t * (void)
PthreadCondition & Signal (void)
PthreadCondition & Broadcast (void)
PthreadCondition & Wait (PthreadMutex &mutex)
int TimedWait (PthreadMutex &mutex, const timespec *abstime)
int TimedWait (PthreadMutex &mutex, double reltime)
int Error (void)
void Clear (void)
Protected Member Functions
void TrapError (int result)
Protected Attributes
int error
Private Attributes
pthread_cond_t theCond
Detailed Description
Definition at line 40 of file PthreadCondition.h.
Constructor & Destructor Documentation
PthreadCondition::PthreadCondition (void)
Definition at line 32 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
 {
     TrapError(pthread_cond_init(&theCond, 0));
 }
PthreadCondition::PthreadCondition (const PthreadConditionAttr & condattr)
Definition at line 41 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
 {
     //  It should simply be:
 //  TrapError(pthread_cond_init(&theCond, cAttr));
     //  This is necessary because
     //      SGI's pthread_cond_init is not const correct!!!
     pthread_condattr_t* myAttr = (PthreadConditionAttr&)cAttr;
     TrapError(pthread_cond_init(&theCond, myAttr));
 }
PthreadCondition::~PthreadCondition (void)
Definition at line 56 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
 {
     try {
         TrapError(pthread_cond_destroy(&theCond));
     } catch (...) {
         std::terminate();
     }
 }
Member Function Documentation
PthreadCondition & PthreadCondition::Broadcast (void)
Definition at line 76 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
Referenced by CPN::RemoteQueue::ActionThreadEntryPoint(), Sync::Future< int >::Cancel(), Sync::Future< void >::Cancel(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), CPN::QueueBase::InternalFlush(), CPN::QueueBase::InternalReset(), Sync::Future< int >::InternalSet(), Sync::Future< void >::InternalSet(), Pthread::Join(), CPN::QueueBase::NotifyData(), CPN::QueueBase::NotifyFreespace(), CPN::QueueBase::NotifyTerminate(), Pthread::Pthread(), Pthread::PthreadCleanup(), Pthread::PthreadEntryPoint(), CPN::LocalContext::SignalKernelEnd(), CPN::LocalContext::SignalKernelStart(), CPN::LocalContext::SignalNodeEnd(), CPN::LocalContext::SignalNodeStart(), Pthread::Start(), CPN::LocalContext::Terminate(), CPN::RemoteQueue::UnlockedShutdown(), PthreadReadWriteLock::WriteUnlock(), Pthread::~Pthread(), and CPN::RemoteQueue::~RemoteQueue().
 {   TrapError(pthread_cond_broadcast(&theCond));
     return *this;
 }
void PthreadErrorHandler::Clear (void) inline inherited
Definition at line 40 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { error = 0; }
int PthreadErrorHandler::Error (void) inline inherited
Definition at line 39 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { return error; }
PthreadCondition::operator pthread_cond_t * (void) inline
Definition at line 47 of file PthreadCondition.h.
References theCond.
 { return &theCond; }
PthreadCondition & PthreadCondition::Signal (void)
Definition at line 68 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
Referenced by CPN::RemoteQueueHolder::CleanupQueue(), and PthreadReadWriteLock::ReadUnlock().
 {   TrapError(pthread_cond_signal(&theCond));
     return *this;
 }
int PthreadCondition::TimedWait (PthreadMutex & mutex, const timespec * abstime)
Definition at line 91 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
 {
     int err = pthread_cond_timedwait(&theCond, mutex, abstime);
     if (err != 0) {
         if (err == ETIMEDOUT) { return true; }
         TrapError(err);
     }
     return false;
 }
int PthreadCondition::TimedWait (PthreadMutex & mutex, double reltime)
Definition at line 103 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
 {
     timespec ts;
     timeval tv;
     int ret = gettimeofday(&tv, 0);
     if (ret != 0) throw ErrnoException();
     ts.tv_sec = tv.tv_sec;
     ts.tv_nsec = tv.tv_usec * 1000;
     unsigned sec = (unsigned)reltime;
     if (sec > 0) {
         ts.tv_sec += sec;
         unsigned nsec = (unsigned)((reltime - sec)*1e9);
         if (nsec > 0) ts.tv_nsec += nsec;
     }
     int err = pthread_cond_timedwait(&theCond, mutex, &ts);
     if (err != 0) {
         if (err == ETIMEDOUT) { return true; }
         TrapError(err);
     }
     return false;
 }
void PthreadErrorHandler::TrapError (int result) inline protected inherited
Definition at line 48 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
Referenced by Broadcast(), PthreadAttr::DetachState(), PthreadBase::Join(), Pthread::Join(), PthreadMutex::Lock(), PthreadMutex::Poll(), Pthread::Pthread(), PthreadAttr::PthreadAttr(), PthreadBase::PthreadBase(), PthreadCondition(), PthreadConditionAttr::PthreadConditionAttr(), PthreadKey< T >::PthreadKey(), PthreadMutex::PthreadMutex(), PthreadMutexAttr::PthreadMutexAttr(), PthreadReadWriteLock::ReadUnlock(), PthreadAttr::ScheduleScope(), PthreadKey< T >::Set(), Signal(), TimedWait(), PthreadMutex::Unlock(), Wait(), PthreadReadWriteLock::WriteUnlock(), PthreadAttr::~PthreadAttr(), ~PthreadCondition(), PthreadConditionAttr::~PthreadConditionAttr(), PthreadKey< T >::~PthreadKey(), PthreadMutex::~PthreadMutex(), and PthreadMutexAttr::~PthreadMutexAttr().
 {
     if (err) {
         error = err;
         throw ErrnoException(err);
     }
 }
PthreadCondition & PthreadCondition::Wait (PthreadMutex & mutex)
Definition at line 84 of file PthreadCondition.cc.
References theCond, and PthreadErrorHandler::TrapError().
Referenced by CPN::RemoteQueue::FileThreadEntryPoint(), Sync::Future< int >::InternalWait(), Sync::Future< void >::InternalWait(), Pthread::Join(), Pthread::PthreadEntryPoint(), PthreadReadWriteLock::ReadLock(), CPN::RemoteContextClient::RemoteCall(), CPN::RemoteQueueHolder::Shutdown(), CPN::RemoteQueue::UnlockedGrow(), CPN::LocalContext::WaitForAllNodeEnd(), CPN::QueueBase::WaitForData(), CPN::QueueBase::WaitForFreespace(), CPN::LocalContext::WaitForKernelStart(), CPN::LocalContext::WaitForNodeEnd(), CPN::LocalContext::WaitForNodeStart(), and PthreadReadWriteLock::WriteLock().
 {   TrapError(pthread_cond_wait(&theCond, mutex));
     return *this;
 }
Member Data Documentation
int PthreadErrorHandler::error protected inherited
Definition at line 43 of file PthreadErrorHandler.h.
Referenced by PthreadErrorHandler::Clear(), PthreadErrorHandler::Error(), PthreadErrorHandler::PthreadErrorHandler(), and PthreadErrorHandler::TrapError().
pthread_cond_t PthreadCondition::theCond private
Definition at line 60 of file PthreadCondition.h.
Referenced by Broadcast(), operator pthread_cond_t *(), PthreadCondition(), Signal(), TimedWait(), Wait(), and ~PthreadCondition().
The documentation for this class was generated from the following files:
include/cpn/threading/PthreadCondition.h
lib/threading/PthreadCondition.cc