CPN: PthreadBase Class Reference
PthreadBase Class Reference
#include <PthreadBase.h>
Classes
class CancelProtected
Public Member Functions
PthreadBase (void)
PthreadBase (pthread_t thread)
PthreadBase (void *(*entryFunc)(void *), void *arg=0)
PthreadBase (PthreadAttr &attr, void *(*entryFunc)(void *), void *arg=0)
operator pthread_t * (void)
operator pthread_t (void)
int operator== (pthread_t t2)
void * Join (void)
int Detach (void)
int Cancel (void)
int SendSignal (int sig)
int Kill (int sig)
int Error (void)
void Clear (void)
Static Public Member Functions
static pthread_t Self (void)
static void TestCancel (void)
static void Exit (void *value)
static int SendSignal (pthread_t thd, int sig)
static int Kill (pthread_t thd, int sig)
static int GetSignalMask (sigset_t *oldSet)
static int SetSignalMask (const sigset_t *set, sigset_t *oldSet=0)
static int BlockSignals (const sigset_t *set, sigset_t *oldSet=0)
static int UnblockSignals (const sigset_t *set, sigset_t *oldSet=0)
static int CancelEnable (void)
static int CancelDisable (void)
static int CancelDeferred (void)
static int CancelAsynchronous (void)
Protected Member Functions
void TrapError (int result)
Protected Attributes
pthread_t theThread
int error
Detailed Description
Definition at line 41 of file PthreadBase.h.
Constructor & Destructor Documentation
PthreadBase::PthreadBase (void)
Definition at line 34 of file PthreadBase.cc.
References Self(), and theThread.
 {
     theThread = Self();
 }
PthreadBase::PthreadBase (pthread_t thread)
Definition at line 42 of file PthreadBase.cc.
References theThread.
 {
     theThread = thread;
 }
PthreadBase::PthreadBase (void *(*)(void *) entryFunc, void * arg = 0)
Definition at line 50 of file PthreadBase.cc.
References theThread, and PthreadErrorHandler::TrapError().
 {
     TrapError( pthread_create( (pthread_t*)&theThread, 0, entryFunc, arg) );
 }
PthreadBase::PthreadBase (PthreadAttr & attr, void *(*)(void *) entryFunc, void * arg = 0)
Definition at line 58 of file PthreadBase.cc.
References theThread, and PthreadErrorHandler::TrapError().
 {
     TrapError( pthread_create( (pthread_t*)&theThread, (pthread_attr_t*)attr, entryFunc, arg) );
 }
Member Function Documentation
static int PthreadBase::BlockSignals (const sigset_t * set, sigset_t * oldSet = 0) inline static
Definition at line 77 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_BLOCK, set, oldSet); }
int PthreadBase::Cancel (void) inline
Definition at line 59 of file PthreadBase.h.
References theThread.
 { return pthread_cancel(theThread); }
int PthreadBase::CancelAsynchronous (void) static
Definition at line 105 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, &oldState);
     return oldState;
 }
int PthreadBase::CancelDeferred (void) static
Definition at line 95 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcanceltype(PTHREAD_CANCEL_DEFERRED, &oldState);
     return oldState;
 }
int PthreadBase::CancelDisable (void) static
Definition at line 86 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &oldState);
     return oldState;
 }
int PthreadBase::CancelEnable (void) static
Definition at line 76 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldState);
     return oldState;
 }
void PthreadErrorHandler::Clear (void) inline inherited
Definition at line 40 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { error = 0; }
int PthreadBase::Detach (void) inline
Definition at line 58 of file PthreadBase.h.
References theThread.
 { return pthread_detach(theThread); }
int PthreadErrorHandler::Error (void) inline inherited
Definition at line 39 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { return error; }
static void PthreadBase::Exit (void * value) inline static
Definition at line 64 of file PthreadBase.h.
 { pthread_exit(value); }
static int PthreadBase::GetSignalMask (sigset_t * oldSet) inline static
Definition at line 73 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_SETMASK, 0, oldSet); }
void * PthreadBase::Join (void)
Definition at line 66 of file PthreadBase.cc.
References theThread, and PthreadErrorHandler::TrapError().
 {
     void* result = 0;
     TrapError( pthread_join(theThread, &result) );
     return result;
 }
int PthreadBase::Kill (int sig) inline
Definition at line 68 of file PthreadBase.h.
References theThread.
 { return pthread_kill(theThread, sig); }
static int PthreadBase::Kill (pthread_t thd, int sig) inline static
Definition at line 71 of file PthreadBase.h.
 { return pthread_kill(thd, sig); }
PthreadBase::operator pthread_t (void) inline
Definition at line 52 of file PthreadBase.h.
References theThread.
 { return theThread; }
PthreadBase::operator pthread_t * (void) inline
Definition at line 51 of file PthreadBase.h.
References theThread.
 { return &theThread; }
int PthreadBase::operator== (pthread_t t2) inline
Definition at line 54 of file PthreadBase.h.
References theThread.
 { return pthread_equal(theThread, t2); }
static pthread_t PthreadBase::Self (void) inline static
Definition at line 61 of file PthreadBase.h.
Referenced by PthreadBase().
 { return pthread_self(); }
int PthreadBase::SendSignal (int sig) inline
Definition at line 67 of file PthreadBase.h.
References theThread.
 { return pthread_kill(theThread, sig); }
static int PthreadBase::SendSignal (pthread_t thd, int sig) inline static
Definition at line 70 of file PthreadBase.h.
 { return pthread_kill(thd, sig); }
static int PthreadBase::SetSignalMask (const sigset_t * set, sigset_t * oldSet = 0) inline static
Definition at line 75 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_SETMASK, set, oldSet); }
static void PthreadBase::TestCancel (void) inline static
Definition at line 63 of file PthreadBase.h.
Referenced by Pthread::PthreadEntryPoint().
 { pthread_testcancel(); }
void PthreadErrorHandler::TrapError (int result) inline protected inherited
Definition at line 48 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
Referenced by PthreadCondition::Broadcast(), PthreadAttr::DetachState(), Join(), Pthread::Join(), PthreadMutex::Lock(), PthreadMutex::Poll(), Pthread::Pthread(), PthreadAttr::PthreadAttr(), PthreadBase(), PthreadCondition::PthreadCondition(), PthreadConditionAttr::PthreadConditionAttr(), PthreadKey< T >::PthreadKey(), PthreadMutex::PthreadMutex(), PthreadMutexAttr::PthreadMutexAttr(), PthreadReadWriteLock::ReadUnlock(), PthreadAttr::ScheduleScope(), PthreadKey< T >::Set(), PthreadCondition::Signal(), PthreadCondition::TimedWait(), PthreadMutex::Unlock(), PthreadCondition::Wait(), PthreadReadWriteLock::WriteUnlock(), PthreadAttr::~PthreadAttr(), PthreadCondition::~PthreadCondition(), PthreadConditionAttr::~PthreadConditionAttr(), PthreadKey< T >::~PthreadKey(), PthreadMutex::~PthreadMutex(), and PthreadMutexAttr::~PthreadMutexAttr().
 {
     if (err) {
         error = err;
         throw ErrnoException(err);
     }
 }
static int PthreadBase::UnblockSignals (const sigset_t * set, sigset_t * oldSet = 0) inline static
Definition at line 79 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_UNBLOCK, set, oldSet); }
Member Data Documentation
int PthreadErrorHandler::error protected inherited
Definition at line 43 of file PthreadErrorHandler.h.
Referenced by PthreadErrorHandler::Clear(), PthreadErrorHandler::Error(), PthreadErrorHandler::PthreadErrorHandler(), and PthreadErrorHandler::TrapError().
pthread_t PthreadBase::theThread protected
Definition at line 126 of file PthreadBase.h.
Referenced by Cancel(), Detach(), Join(), Pthread::Join(), Kill(), operator pthread_t(), operator pthread_t *(), operator==(), Pthread::Pthread(), PthreadBase(), and SendSignal().
The documentation for this class was generated from the following files:
include/cpn/threading/PthreadBase.h
lib/threading/PthreadBase.cc