CPN: CPN::PacketDecoder Class Reference
CPN::PacketDecoder Class Reference abstract
#include <PacketDecoder.h>
Public Member Functions
PacketDecoder ()
virtual ~PacketDecoder ()
void * GetDecoderBytes (unsigned &amount)
void ReleaseDecoderBytes (unsigned amount)
void Reset ()
unsigned NumBytes () const
void FirePacket (const Packet &packet)
virtual void EnqueuePacket (const Packet &packet)=0
virtual void DequeuePacket (const Packet &packet)=0
virtual void ReadBlockPacket (const Packet &packet)=0
virtual void WriteBlockPacket (const Packet &packet)=0
virtual void EndOfWritePacket (const Packet &packet)=0
virtual void EndOfReadPacket (const Packet &packet)=0
virtual void GrowPacket (const Packet &packet)=0
virtual void D4RTagPacket (const Packet &packet)=0
virtual void FlushPacket (const Packet &packet)=0
virtual void ResetPacket (const Packet &packet)=0
virtual void IDReaderPacket (const Packet &packet)=0
virtual void IDWriterPacket (const Packet &packet)=0
Private Attributes
Packet header
unsigned numbytes
Detailed Description
The packet decoder receives bytes through GetDecoderbytes and ReleaseDecoderBytes. When enough bytes have been recieved to call one of the Received event functions those events will be called and the internal state will remove the information. If the information is not delt with in the event function it will be lost. This class is ment to be enherited by some other class which implements the event functions.
Definition at line 40 of file PacketDecoder.h.
Constructor & Destructor Documentation
CPN::PacketDecoder::PacketDecoder ()
Definition at line 30 of file PacketDecoder.cc.
         : numbytes(0)
     {
     }
CPN::PacketDecoder::~PacketDecoder () virtual
Definition at line 35 of file PacketDecoder.cc.
 {}
Member Function Documentation
virtual void CPN::PacketHandler::D4RTagPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::DequeuePacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::EndOfReadPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::EndOfWritePacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::EnqueuePacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
void CPN::PacketHandler::FirePacket (const Packet & packet) inherited
Definition at line 31 of file PacketHeader.cc.
References ASSERT, CPN::PacketHandler::D4RTagPacket(), CPN::PacketHandler::DequeuePacket(), CPN::PacketHandler::EndOfReadPacket(), CPN::PacketHandler::EndOfWritePacket(), CPN::PacketHandler::EnqueuePacket(), CPN::PacketHandler::FlushPacket(), CPN::PacketHandler::GrowPacket(), CPN::PacketHandler::IDReaderPacket(), CPN::PacketHandler::IDWriterPacket(), CPN::PACKET_D4RTAG, CPN::PACKET_DEQUEUE, CPN::PACKET_ENDOFREAD, CPN::PACKET_ENDOFWRITE, CPN::PACKET_ENQUEUE, CPN::PACKET_FLUSH, CPN::PACKET_GROW, CPN::PACKET_ID_READER, CPN::PACKET_ID_WRITER, CPN::PACKET_READBLOCK, CPN::PACKET_RESET, CPN::PACKET_WRITEBLOCK, CPN::PacketHandler::ReadBlockPacket(), CPN::PacketHandler::ResetPacket(), CPN::Packet::Type(), CPN::Packet::Valid(), and CPN::PacketHandler::WriteBlockPacket().
Referenced by ReleaseDecoderBytes().
{
         ASSERT(packet.Valid(), "Invalid packet");
         switch (packet.Type()) {
         case PACKET_ENQUEUE:
             EnqueuePacket(packet);
             break;
         case PACKET_DEQUEUE:
             DequeuePacket(packet);
             break;
         case PACKET_READBLOCK:
             ReadBlockPacket(packet);
             break;
         case PACKET_WRITEBLOCK:
             WriteBlockPacket(packet);
             break;
         case PACKET_ENDOFWRITE:
             EndOfWritePacket(packet);
             break;
         case PACKET_ENDOFREAD:
             EndOfReadPacket(packet);
             break;
         case PACKET_GROW:
             GrowPacket(packet);
             break;
         case PACKET_D4RTAG:
             D4RTagPacket(packet);
             break;
         case PACKET_FLUSH:
             FlushPacket(packet);
             break;
         case PACKET_RESET:
             ResetPacket(packet);
             break;
         case PACKET_ID_READER:
             IDReaderPacket(packet);
             break;
         case PACKET_ID_WRITER:
             IDWriterPacket(packet);
             break;
         default:
             ASSERT(false, "Invalid packet type.");
         }
     }
virtual void CPN::PacketHandler::FlushPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
void * CPN::PacketDecoder::GetDecoderBytes (unsigned & amount)
Definition at line 37 of file PacketDecoder.cc.
References ASSERT, header, CPN::Packet::header, and numbytes.
Referenced by CPN::RemoteQueue::Read().
{
         char *ptr = reinterpret_cast<char*>(&header.header);
         amount = sizeof(header.header) - numbytes;
         ASSERT(amount != 0, "Zero decoder bytes");
         return ptr + numbytes;
     }
virtual void CPN::PacketHandler::GrowPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::IDReaderPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::IDWriterPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
unsigned CPN::PacketDecoder::NumBytes () const inline
Definition at line 48 of file PacketDecoder.h.
 { return numbytes; }
virtual void CPN::PacketHandler::ReadBlockPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
void CPN::PacketDecoder::ReleaseDecoderBytes (unsigned amount)
Definition at line 44 of file PacketDecoder.cc.
References ASSERT, CPN::PacketHandler::FirePacket(), header, CPN::Packet::header, numbytes, and CPN::Packet::Valid().
Referenced by CPN::RemoteQueue::Read().
{
         ASSERT(numbytes + amount <= sizeof(header.header));
         numbytes += amount;
         if (numbytes == sizeof(header.header)) {
             if (header.Valid()) {
                 FirePacket(header);
                 numbytes = 0;
             } else {
                 // If it is not valid, what do we do??
                 // Well, we can search for the header word
                 // wont always work...
                 char *ptr = reinterpret_cast<char*>(&header.header);
                 numbytes -= 1;
                 memmove(ptr, ptr + 1, numbytes);
             }
         }
     }
void CPN::PacketDecoder::Reset ()
Definition at line 62 of file PacketDecoder.cc.
References numbytes.
{
         numbytes = 0;
     }
virtual void CPN::PacketHandler::ResetPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
virtual void CPN::PacketHandler::WriteBlockPacket (const Packet & packet) pure virtual inherited
Implemented in CPN::RemoteQueue.
Referenced by CPN::PacketHandler::FirePacket().
Member Data Documentation
Packet CPN::PacketDecoder::header private
Definition at line 52 of file PacketDecoder.h.
Referenced by GetDecoderBytes(), ReleaseDecoderBytes(), and CPN::RemoteQueue::SendEnqueuePacket().
unsigned CPN::PacketDecoder::numbytes private
Definition at line 53 of file PacketDecoder.h.
Referenced by GetDecoderBytes(), ReleaseDecoderBytes(), and Reset().
The documentation for this class was generated from the following files:
lib/PacketDecoder.h
lib/PacketDecoder.cc