CPN: AutoLock< Lockable > Class Template Reference
AutoLock< Lockable > Class Template Reference
#include <AutoLock.h>
Public Member Functions
AutoLock (Lockable &mutex_)
AutoLock (Lockable &mutex_, bool lock)
~AutoLock ()
void Unlock ()
void Lock ()
Private Attributes
Lockable & mutex
int count
Detailed Description
template<class Lockable>
class AutoLock< Lockable >
An automatic lock that ensures the lock is left in the state at construction when destroyed.
Definition at line 35 of file AutoLock.h.
Constructor & Destructor Documentation
template<class Lockable> AutoLock< Lockable >::AutoLock (Lockable & mutex_) inline
Create a new AutoLock and lock the mutex.
Parameters
mutex_ the mutex
Definition at line 41 of file AutoLock.h.
References AutoLock< Lockable >::Lock().
                                : mutex(mutex_), count(0) {
         Lock();
     }
template<class Lockable> AutoLock< Lockable >::AutoLock (Lockable & mutex_, bool lock) inline
Create a new AutoLock and only lock the mutex if lock is true
Parameters
mutex_ the mutex
lock true to lock or false to not
Definition at line 49 of file AutoLock.h.
References AutoLock< Lockable >::Lock().
                                           : mutex(mutex_), count(0) {
         if (lock) { Lock(); }
     }
template<class Lockable> AutoLock< Lockable >::~AutoLock () inline
Definition at line 53 of file AutoLock.h.
References AutoLock< Lockable >::count, and AutoLock< Lockable >::Unlock().
                 {
         while (count > 0)
             Unlock();
     }
Member Function Documentation
template<class Lockable> void AutoLock< Lockable >::Lock (void) inline
Unlock the mutex
Definition at line 69 of file AutoLock.h.
References AutoLock< Lockable >::count, and AutoLock< Lockable >::mutex.
Referenced by AutoLock< Lockable >::AutoLock(), and CPN::Kernel::EntryPoint().
                 {
         mutex.Lock();
         ++count;
     }
template<class Lockable> void AutoLock< Lockable >::Unlock (void) inline
Lock the mutex
Definition at line 61 of file AutoLock.h.
References AutoLock< Lockable >::count, and AutoLock< Lockable >::mutex.
Referenced by D4R::Node::Block(), CPN::RemoteQueueHolder::Cleanup(), CPN::ConnectionServer::ConnectWriter(), CPN::Kernel::CreateExternalEndpoint(), CPN::Kernel::CreateReaderEndpoint(), CPN::Kernel::CreateWriterEndpoint(), CPN::Kernel::DestroyExternalEndpoint(), CPN::RemoteContextClient::DispatchMessage(), CPN::Kernel::EntryPoint(), CPN::ConnectionServer::PendingConnection::Get(), CPN::Kernel::GetExternalIQueue(), CPN::Kernel::GetExternalOQueue(), CPN::PseudoNode::ReleaseReader(), CPN::PseudoNode::ReleaseWriter(), CPN::ConnectionServer::PendingConnection::Set(), CPN::PseudoNode::Shutdown(), D4R::Node::Transmit(), and AutoLock< Lockable >::~AutoLock().
                   {
         --count;
         mutex.Unlock();
     }
Member Data Documentation
template<class Lockable> int AutoLock< Lockable >::count private
Definition at line 76 of file AutoLock.h.
Referenced by AutoLock< Lockable >::Lock(), AutoLock< Lockable >::Unlock(), and AutoLock< Lockable >::~AutoLock().
template<class Lockable> Lockable& AutoLock< Lockable >::mutex private
Definition at line 75 of file AutoLock.h.
Referenced by AutoLock< Lockable >::Lock(), and AutoLock< Lockable >::Unlock().
The documentation for this class was generated from the following file:
include/cpn/utils/AutoLock.h