CPN: CPN::PacketHandler Class Reference
CPN::PacketHandler Class Reference abstract
#include <PacketHeader.h>
Public Member Functions
virtual ~PacketHandler ()
void FirePacket (const Packet &packet)
virtual void EnqueuePacket (const Packet &packet)=0
virtual void DequeuePacket (const Packet &packet)=0
virtual void ReadBlockPacket (const Packet &packet)=0
virtual void WriteBlockPacket (const Packet &packet)=0
virtual void EndOfWritePacket (const Packet &packet)=0
virtual void EndOfReadPacket (const Packet &packet)=0
virtual void GrowPacket (const Packet &packet)=0
virtual void D4RTagPacket (const Packet &packet)=0
virtual void FlushPacket (const Packet &packet)=0
virtual void ResetPacket (const Packet &packet)=0
virtual void IDReaderPacket (const Packet &packet)=0
virtual void IDWriterPacket (const Packet &packet)=0
Detailed Description
This class makes it easy to process packets.
Definition at line 154 of file PacketHeader.h.
Constructor & Destructor Documentation
CPN::PacketHandler::~PacketHandler () virtual
Definition at line 29 of file PacketHeader.cc.
 {}
Member Function Documentation
virtual void CPN::PacketHandler::D4RTagPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::DequeuePacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::EndOfReadPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::EndOfWritePacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::EnqueuePacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
void CPN::PacketHandler::FirePacket (const Packet & packet)
Definition at line 31 of file PacketHeader.cc.
References ASSERT, D4RTagPacket(), DequeuePacket(), EndOfReadPacket(), EndOfWritePacket(), EnqueuePacket(), FlushPacket(), GrowPacket(), IDReaderPacket(), IDWriterPacket(), CPN::PACKET_D4RTAG, CPN::PACKET_DEQUEUE, CPN::PACKET_ENDOFREAD, CPN::PACKET_ENDOFWRITE, CPN::PACKET_ENQUEUE, CPN::PACKET_FLUSH, CPN::PACKET_GROW, CPN::PACKET_ID_READER, CPN::PACKET_ID_WRITER, CPN::PACKET_READBLOCK, CPN::PACKET_RESET, CPN::PACKET_WRITEBLOCK, ReadBlockPacket(), ResetPacket(), CPN::Packet::Type(), CPN::Packet::Valid(), and WriteBlockPacket().
Referenced by CPN::PacketDecoder::ReleaseDecoderBytes().
{
         ASSERT(packet.Valid(), "Invalid packet");
         switch (packet.Type()) {
         case PACKET_ENQUEUE:
             EnqueuePacket(packet);
             break;
         case PACKET_DEQUEUE:
             DequeuePacket(packet);
             break;
         case PACKET_READBLOCK:
             ReadBlockPacket(packet);
             break;
         case PACKET_WRITEBLOCK:
             WriteBlockPacket(packet);
             break;
         case PACKET_ENDOFWRITE:
             EndOfWritePacket(packet);
             break;
         case PACKET_ENDOFREAD:
             EndOfReadPacket(packet);
             break;
         case PACKET_GROW:
             GrowPacket(packet);
             break;
         case PACKET_D4RTAG:
             D4RTagPacket(packet);
             break;
         case PACKET_FLUSH:
             FlushPacket(packet);
             break;
         case PACKET_RESET:
             ResetPacket(packet);
             break;
         case PACKET_ID_READER:
             IDReaderPacket(packet);
             break;
         case PACKET_ID_WRITER:
             IDWriterPacket(packet);
             break;
         default:
             ASSERT(false, "Invalid packet type.");
         }
     }
virtual void CPN::PacketHandler::FlushPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::GrowPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::IDReaderPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::IDWriterPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::ReadBlockPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::ResetPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
virtual void CPN::PacketHandler::WriteBlockPacket (const Packet & packet) pure virtual
Implemented in CPN::RemoteQueue.
Referenced by FirePacket().
The documentation for this class was generated from the following files:
lib/PacketHeader.h
lib/PacketHeader.cc