CPN: Sync::ReentrantCondition Class Reference
Sync::ReentrantCondition Class Reference
Works just like a pthread condition but works with the ReentrantLock.
#include <ReentrantLock.h>
Public Member Functions
ReentrantCondition ()
~ReentrantCondition ()
void Signal ()
void Broadcast ()
void Wait (ReentrantLock &lock) const
Private Attributes
pthread_cond_t cond
Detailed Description
Works just like a pthread condition but works with the ReentrantLock.
Definition at line 123 of file ReentrantLock.h.
Constructor & Destructor Documentation
Sync::ReentrantCondition::ReentrantCondition () inline
Definition at line 125 of file ReentrantLock.h.
References cond, and ENSURE.
{
             ENSURE(!pthread_cond_init(&cond, 0));
 #ifdef SYNC_PROFILE
             wait_time = 0;
 #endif
         }
Sync::ReentrantCondition::~ReentrantCondition () inline
Definition at line 131 of file ReentrantLock.h.
References cond, and ENSURE_ABORT.
 { ENSURE_ABORT(!pthread_cond_destroy(&cond)); }
Member Function Documentation
void Sync::ReentrantCondition::Broadcast (void) inline
Definition at line 133 of file ReentrantLock.h.
References cond.
 { pthread_cond_broadcast(&cond); }
void Sync::ReentrantCondition::Signal (void) inline
Definition at line 132 of file ReentrantLock.h.
References cond.
Referenced by CPN::PseudoNode::CreateReader(), CPN::PseudoNode::CreateWriter(), CPN::Kernel::NodeTerminated(), CPN::PseudoNode::NotifyTerminate(), and CPN::Kernel::SendWakeup().
 { pthread_cond_signal(&cond); }
void Sync::ReentrantCondition::Wait (ReentrantLock & lock) const inline
Definition at line 134 of file ReentrantLock.h.
References cond, and Sync::ReentrantLock::lock.
Referenced by CPN::Kernel::EntryPoint(), CPN::PseudoNode::GetReader(), and CPN::PseudoNode::GetWriter().
{
 #ifdef SYNC_PROFILE
             double time = Internal::getTime();
             unsigned lock_count = lock.lock_count;
             lock.lock_count = 0;
             lock.lock_time += time - lock.lock_last;
 #endif
             pthread_cond_wait(&cond, &lock.lock);
 #ifdef SYNC_PROFILE
             double end = Internal::getTime();
             lock.lock_count = lock_count;
             lock.lock_last = end;
             wait_time += end - time;
 #endif
         }
Member Data Documentation
pthread_cond_t Sync::ReentrantCondition::cond mutable private
Definition at line 156 of file ReentrantLock.h.
Referenced by Broadcast(), ReentrantCondition(), Signal(), Wait(), and ~ReentrantCondition().
The documentation for this class was generated from the following file:
include/cpn/threading/ReentrantLock.h