CPN: PthreadAttr Class Reference
PthreadAttr Class Reference
#include <PthreadAttr.h>
Public Member Functions
PthreadAttr (int systemScope=0)
~PthreadAttr (void)
PthreadAttr (const PthreadAttr &)
operator pthread_attr_t * (void)
operator const pthread_attr_t * (void) const
void CreateDetached (void)
void CreateJoinable (void)
int Detached (void)
int Joinable (void)
void SystemScope (void)
void ProcessScope (void)
int InSystemScope (void)
int InProcessScope (void)
int Error (void)
void Clear (void)
Protected Member Functions
void TrapError (int result)
Protected Attributes
int error
Private Member Functions
int DetachState (int detState)
int DetachState (void)
int ScheduleScope (int scope)
int ScheduleScope (void)
Private Attributes
pthread_attr_t attr
int referenceCount
Detailed Description
Definition at line 40 of file PthreadAttr.h.
Constructor & Destructor Documentation
PthreadAttr::PthreadAttr (int systemScope = 0)
Definition at line 32 of file PthreadAttr.cc.
References attr, referenceCount, SystemScope(), and PthreadErrorHandler::TrapError().
 {
     TrapError(pthread_attr_init(&attr));
     if (systemScope) SystemScope();
     referenceCount = 1;
 //  printf("PthreadAttr::PthreadAttr()\n");
 }
PthreadAttr::~PthreadAttr (void)
Definition at line 42 of file PthreadAttr.cc.
References attr, referenceCount, and PthreadErrorHandler::TrapError().
 {
     try {
         referenceCount--;
     //  printf("PthreadAttr::~PthreadAttr: referenceCount = %d\n", referenceCount);
         if (!referenceCount)
             TrapError(pthread_attr_destroy(&attr));
     } catch (...) {
         std::terminate();
     }
 }
PthreadAttr::PthreadAttr (const PthreadAttr & cpAttr)
Definition at line 57 of file PthreadAttr.cc.
References attr, and referenceCount.
 {
     attr = cpAttr.attr;
     referenceCount = cpAttr.referenceCount+1;
 //  printf("PthreadAttr::PthreadAttr(const PthreadAttr&): referenceCount = %d\n", referenceCount);
 }
Member Function Documentation
void PthreadErrorHandler::Clear (void) inline inherited
Definition at line 40 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { error = 0; }
void PthreadAttr::CreateDetached (void) inline
Definition at line 51 of file PthreadAttr.h.
References DetachState().
 { DetachState(PTHREAD_CREATE_DETACHED); }
void PthreadAttr::CreateJoinable (void) inline
Definition at line 52 of file PthreadAttr.h.
References DetachState().
 { DetachState(PTHREAD_CREATE_JOINABLE); }
int PthreadAttr::Detached (void) inline
Definition at line 53 of file PthreadAttr.h.
References DetachState().
 { return DetachState() == PTHREAD_CREATE_DETACHED; }
int PthreadAttr::DetachState (int detState) private
Definition at line 83 of file PthreadAttr.cc.
References attr, and PthreadErrorHandler::TrapError().
 {
     TrapError(pthread_attr_setdetachstate(&attr, detState));
     return detState;
 }
int PthreadAttr::DetachState (void) private
Definition at line 67 of file PthreadAttr.cc.
References attr, and PthreadErrorHandler::TrapError().
Referenced by CreateDetached(), CreateJoinable(), Detached(), and Joinable().
 {
     int detState;
     TrapError(pthread_attr_getdetachstate(&attr, &detState));
     return detState;
 }
int PthreadErrorHandler::Error (void) inline inherited
Definition at line 39 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { return error; }
int PthreadAttr::InProcessScope (void) inline
Definition at line 97 of file PthreadAttr.h.
References ScheduleScope().
 { return ScheduleScope() == PTHREAD_SCOPE_PROCESS; }
int PthreadAttr::InSystemScope (void) inline
Definition at line 96 of file PthreadAttr.h.
References ScheduleScope().
 { return ScheduleScope() == PTHREAD_SCOPE_SYSTEM; }
int PthreadAttr::Joinable (void) inline
Definition at line 54 of file PthreadAttr.h.
References DetachState().
 { return DetachState() == PTHREAD_CREATE_JOINABLE; }
PthreadAttr::operator const pthread_attr_t * (void) const inline
Definition at line 48 of file PthreadAttr.h.
References attr.
 { return &attr; }
PthreadAttr::operator pthread_attr_t * (void) inline
Definition at line 47 of file PthreadAttr.h.
References attr.
 { return &attr; }
void PthreadAttr::ProcessScope (void) inline
Definition at line 95 of file PthreadAttr.h.
References ScheduleScope().
 { ScheduleScope(PTHREAD_SCOPE_PROCESS); }
int PthreadAttr::ScheduleScope (int scope) private
Definition at line 209 of file PthreadAttr.cc.
References attr, and PthreadErrorHandler::TrapError().
 {
     TrapError(pthread_attr_setscope(&attr, scope));
     return scope;
 }
int PthreadAttr::ScheduleScope (void) private
Definition at line 217 of file PthreadAttr.cc.
References attr, and PthreadErrorHandler::TrapError().
Referenced by InProcessScope(), InSystemScope(), ProcessScope(), and SystemScope().
 {   int scope;
     TrapError(pthread_attr_getscope(&attr, &scope));
     return scope;
 }
void PthreadAttr::SystemScope (void) inline
Definition at line 94 of file PthreadAttr.h.
References ScheduleScope().
Referenced by PthreadAttr().
 { ScheduleScope(PTHREAD_SCOPE_SYSTEM); }
void PthreadErrorHandler::TrapError (int result) inline protected inherited
Definition at line 48 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
Referenced by PthreadCondition::Broadcast(), DetachState(), PthreadBase::Join(), Pthread::Join(), PthreadMutex::Lock(), PthreadMutex::Poll(), Pthread::Pthread(), PthreadAttr(), PthreadBase::PthreadBase(), PthreadCondition::PthreadCondition(), PthreadConditionAttr::PthreadConditionAttr(), PthreadKey< T >::PthreadKey(), PthreadMutex::PthreadMutex(), PthreadMutexAttr::PthreadMutexAttr(), PthreadReadWriteLock::ReadUnlock(), ScheduleScope(), PthreadKey< T >::Set(), PthreadCondition::Signal(), PthreadCondition::TimedWait(), PthreadMutex::Unlock(), PthreadCondition::Wait(), PthreadReadWriteLock::WriteUnlock(), ~PthreadAttr(), PthreadCondition::~PthreadCondition(), PthreadConditionAttr::~PthreadConditionAttr(), PthreadKey< T >::~PthreadKey(), PthreadMutex::~PthreadMutex(), and PthreadMutexAttr::~PthreadMutexAttr().
 {
     if (err) {
         error = err;
         throw ErrnoException(err);
     }
 }
Member Data Documentation
pthread_attr_t PthreadAttr::attr private
Definition at line 100 of file PthreadAttr.h.
Referenced by DetachState(), operator const pthread_attr_t *(), operator pthread_attr_t *(), PthreadAttr(), ScheduleScope(), and ~PthreadAttr().
int PthreadErrorHandler::error protected inherited
Definition at line 43 of file PthreadErrorHandler.h.
Referenced by PthreadErrorHandler::Clear(), PthreadErrorHandler::Error(), PthreadErrorHandler::PthreadErrorHandler(), and PthreadErrorHandler::TrapError().
int PthreadAttr::referenceCount private
Definition at line 101 of file PthreadAttr.h.
Referenced by PthreadAttr(), and ~PthreadAttr().
The documentation for this class was generated from the following files:
include/cpn/threading/PthreadAttr.h
lib/threading/PthreadAttr.cc