CPN: CPN::RemoteContextDaemon Class Reference
CPN::RemoteContextDaemon Class Reference
#include <RemoteContextDaemon.h>
Classes
class Client
Public Types
typedef AutoLock< PthreadMutex > ALock
Public Member Functions
RemoteContextDaemon (const SocketAddress &addr)
RemoteContextDaemon (const SockAddrList &addrs)
~RemoteContextDaemon ()
void Run ()
Run the actual Context returns when the context is terminated and all clients have disconnected.
bool IsTerminated () const
int DebugLevel () const
int DebugLevel (int level)
void Listen (const SocketAddress &addr, int queuelength=256)
void Listen (const SockAddrList &addrs, int queuelength=256)
int Accept (SocketAddress &addr)
int Accept ()
void SetReuseAddr (bool reuse=true)
Turn on reuse of the address. Only takes effect if set before Listen.
bool GetReuseAddr ()
int Poll (double timeout)
bool Readable (bool r)
Set that the file is currently readable or not.
bool Readable () const
Gives the current readability status of the file.
bool Writeable (bool w)
Set that this file is currently writeable or not.
bool Writeable () const
Gives the current writability status of the file.
int FD () const
int FD (int filed)
Set the current file descriptor.
bool Eof () const
bool Eof (bool e)
Set/reset the end of file condition.
bool Good () const
Convenience method for testing if the file this FileHandle has is open and not at end of file.
bool Closed () const
void SetBlocking (bool blocking)
Manipulate how the current file handles blocking.
bool IsBlocking () const
Test if the current file is in blocking or non blocking mode.
void Reset ()
Clear all internal state including the file descriptor! WARNING does not close the file!
void Close ()
Close the file and reset the internal state.
unsigned Read (void *ptr, unsigned len)
Read data from the file descriptor.
unsigned Readv (const iovec *iov, int iovcnt)
scatter gather io version of Read
unsigned Write (const void *ptr, unsigned len)
Write data to the file descriptor.
unsigned Writev (const iovec *iov, int iovcnt)
scatter gather io version of Write
void Flush ()
Tell the OS to flush any buffers it has. May not be supported for all file types.
Static Public Member Functions
static int Poll (IteratorRef< FileHandle * > begin, IteratorRef< FileHandle * > end, double timeout)
poll a list of FileHandles for any activity and call the appropriate On method.
static void SetBlocking (int fd, bool blocking)
a convenience method that allows one to set the same blocking parameters for a file descriptor without setting it inside a FileHandle.
static bool IsBlocking (int fd)
Test the given file descriptor if it is in blocking mode.
Protected Member Functions
void DispatchMessage (const std::string &sender, const Variant &msg)
Process the given message.
void dbprintf (int level, const char *fmt,...)
virtual void OnReadable ()
Called by Poll when it detects that the file is readable.
virtual void OnWriteable ()
Called by Poll when it detects that the file is writeable.
Protected Attributes
PthreadMutex file_lock
int fd
bool readable
bool writeable
bool eof
Private Types
typedef std::tr1::shared_ptr
< Client > ClientPtr
typedef std::map< std::string,
ClientPtr > ClientMap
Private Member Functions
void Terminate ()
void Terminate (const std::string &name)
void Read ()
void SendMessage (const std::string &recipient, const Variant &msg)
Send the given message to the given client.
void BroadcastMessage (const Variant &msg)
Broadcast a message to all clients.
void LogMessage (const std::string &msg)
Log a message.
Private Attributes
ClientMap clients
Friends
class Client
Detailed Description
The RemoteContextDaemon is an implementation of RemoteContextServer that uses simple tcp/ip and listens on an address you specify.
Definition at line 41 of file RemoteContextDaemon.h.
Member Typedef Documentation
typedef AutoLock<PthreadMutex> FileHandle::ALock inherited
Definition at line 43 of file FileHandle.h.
typedef std::map<std::string, ClientPtr> CPN::RemoteContextDaemon::ClientMap private
Definition at line 75 of file RemoteContextDaemon.h.
typedef std::tr1::shared_ptr<Client> CPN::RemoteContextDaemon::ClientPtr private
Definition at line 74 of file RemoteContextDaemon.h.
Constructor & Destructor Documentation
CPN::RemoteContextDaemon::RemoteContextDaemon (const SocketAddress & addr)
Definition at line 31 of file RemoteContextDaemon.cc.
References ServerSocketHandle::Listen(), and ServerSocketHandle::SetReuseAddr().
     {
         SetReuseAddr();
         Listen(addr);
     }
CPN::RemoteContextDaemon::RemoteContextDaemon (const SockAddrList & addrs)
Definition at line 37 of file RemoteContextDaemon.cc.
References ServerSocketHandle::Listen(), and ServerSocketHandle::SetReuseAddr().
     {
         SetReuseAddr();
         Listen(addrs);
     }
CPN::RemoteContextDaemon::~RemoteContextDaemon ()
Definition at line 42 of file RemoteContextDaemon.cc.
{
     }
Member Function Documentation
int ServerSocketHandle::Accept (SocketAddress & addr) inherited
Accept an incoming connection.
Parameters
addr a SocketAddress object to fill with the address of the connecting peer.
Returns
-1 if no connection >=0 on success
Exceptions
ErrnoException for errors
Definition at line 46 of file ServerSocketHandle.cc.
References ServerSocketHandle::Accept().
Referenced by CPN::ConnectionServer::Poll().
{
     return Accept(&addr);
 }
int ServerSocketHandle::Accept () inherited
Accept an incoming connection
Definition at line 50 of file ServerSocketHandle.cc.
Referenced by ServerSocketHandle::Accept(), and Read().
{
     return Accept(0);
 }
void CPN::RemoteContextDaemon::BroadcastMessage (const Variant & msg) private virtual
Broadcast a message to all clients.
Parameters
msg the message to send to all clients
Implements CPN::RemoteContextServer.
Definition at line 125 of file RemoteContextDaemon.cc.
References clients, CPN::RemoteContextServer::dbprintf(), and CPN::RemoteContextServer::IsTerminated().
{
         if (IsTerminated()) {
             dbprintf(1, "Trying to braodcast after shutdown\n%s", libvariant::SerializeJSON(msg).c_str());
             return;
         }
         ClientMap::iterator entry = clients.begin();
         dbprintf(4, "broadcast:%s\n", libvariant::SerializeJSON(msg).c_str());
         while (entry != clients.end()) {
             entry->second->Send(msg);
             ++entry;
         }
     }
void FileHandle::Close () inherited
Close the file and reset the internal state.
Definition at line 146 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::readable, and FileHandle::writeable.
Referenced by CPN::ConnectionServer::Close(), CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), and Terminate().
{
     ALock al(file_lock);
     if (fd != -1) {
         if (close(fd) != 0) {
             throw ErrnoException();
         }
         fd = -1;
     }
     readable = false;
     writeable = false;
     eof = false;
 }
bool FileHandle::Closed () const inline inherited
Returns
false if this FileHandle has an open file
Definition at line 128 of file FileHandle.h.
References FileHandle::fd, and FileHandle::file_lock.
Referenced by SocketHandle::Connect(), CPN::ConnectionServer::ConnectReader(), CPN::ConnectionServer::ConnectWriter(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteQueue::LogState(), CPN::ConnectionServer::LogState(), Run(), CPN::RemoteContextDaemon::Client::Send(), and CPN::RemoteContext::SendMessage().
 { ALock al(file_lock); return fd == -1; }
void CPN::RemoteContextServer::dbprintf (int level, const char * fmt, ...) protected inherited
Definition at line 40 of file RemoteContextServer.cc.
References CPN::RemoteContextServer::debuglevel.
Referenced by BroadcastMessage(), CPN::RemoteContextDaemon::Client::Client(), CPN::RemoteContextServer::CreateNodeKey(), CPN::RemoteContextServer::DispatchMessage(), LogMessage(), Run(), SendMessage(), CPN::RemoteContextServer::SetupKernel(), CPN::RemoteContextServer::SignalKernelEnd(), CPN::RemoteContextServer::SignalKernelStart(), CPN::RemoteContextServer::SignalNodeEnd(), CPN::RemoteContextServer::SignalNodeStart(), and Terminate().
{
         if (debuglevel >= level) {
             va_list ap;
             va_start(ap, fmt);
             vprintf(fmt, ap);
             va_end(ap);
         }
     }
int CPN::RemoteContextServer::DebugLevel () const inline inherited
Definition at line 126 of file RemoteContextServer.h.
References CPN::RemoteContextServer::debuglevel.
 { return debuglevel; }
int CPN::RemoteContextServer::DebugLevel (int level) inline inherited
Definition at line 127 of file RemoteContextServer.h.
References CPN::RemoteContextServer::debuglevel.
 { return debuglevel = level; }
void CPN::RemoteContextServer::DispatchMessage (const std::string & sender, const Variant & msg) protected inherited
Process the given message.
Parameters
sender a string id for the client
msg the message that the client sent
Definition at line 49 of file RemoteContextServer.cc.
References ASSERT, CPN::RemoteContextServer::ConnectEndpoints(), CPN::RemoteContextServer::CreateNodeKey(), CPN::RemoteContextServer::dbprintf(), CPN::RemoteContextServer::GetCreateEndpointKey(), CPN::RemoteContextServer::GetEndpointInfo(), CPN::RemoteContextServer::GetKernelInfo(), CPN::RemoteContextServer::GetNodeInfo(), CPN::RemoteContextServer::GetNumNodeLive(), CPN::RemoteContextServer::IsTerminated(), CPN::RemoteContextServer::LogMessage(), CPN::RCTXMT_CONNECT_ENDPOINTS, CPN::RCTXMT_CREATE_NODE, CPN::RCTXMT_CREATE_NODE_KEY, CPN::RCTXMT_CREATE_QUEUE, CPN::RCTXMT_CREATE_READER, CPN::RCTXMT_CREATE_WRITER, CPN::RCTXMT_GET_CREATE_READER_KEY, CPN::RCTXMT_GET_CREATE_WRITER_KEY, CPN::RCTXMT_GET_KERNEL_INFO, CPN::RCTXMT_GET_NODE_INFO, CPN::RCTXMT_GET_NUM_NODE_LIVE, CPN::RCTXMT_GET_READER_INFO, CPN::RCTXMT_GET_WRITER_INFO, CPN::RCTXMT_LOG, CPN::RCTXMT_SETUP_KERNEL, CPN::RCTXMT_SIGNAL_KERNEL_END, CPN::RCTXMT_SIGNAL_KERNEL_START, CPN::RCTXMT_SIGNAL_NODE_END, CPN::RCTXMT_SIGNAL_NODE_START, CPN::RCTXMT_TERMINATE, CPN::RemoteContextServer::RouteKernelMessage(), CPN::RemoteContextServer::SetupKernel(), CPN::RemoteContextServer::SignalKernelEnd(), CPN::RemoteContextServer::SignalKernelStart(), CPN::RemoteContextServer::SignalNodeEnd(), CPN::RemoteContextServer::SignalNodeStart(), and CPN::RemoteContextServer::Terminate().
{
         dbprintf(4, "msg:%s:%s\n", sender.c_str(), libvariant::SerializeJSON(msg).c_str());
         if (!msg.IsMap()) { return; }
         if (IsTerminated()) {
             return;
         }
         RCTXMT_t type = msg["type"].AsNumber<RCTXMT_t>();
         switch (type) {
         case RCTXMT_SETUP_KERNEL:
             SetupKernel(sender, msg);
             break;
         case RCTXMT_SIGNAL_KERNEL_START:
             SignalKernelStart(msg);
             break;
         case RCTXMT_SIGNAL_KERNEL_END:
             SignalKernelEnd(msg);
             break;
         case RCTXMT_GET_KERNEL_INFO:
             GetKernelInfo(sender, msg);
             break;
         case RCTXMT_CREATE_WRITER:
         case RCTXMT_CREATE_READER:
         case RCTXMT_CREATE_QUEUE:
         case RCTXMT_CREATE_NODE:
             RouteKernelMessage(msg);
             break;
         case RCTXMT_CREATE_NODE_KEY:
             CreateNodeKey(sender, msg);
             break;
         case RCTXMT_SIGNAL_NODE_START:
             SignalNodeStart(msg);
             break;
         case RCTXMT_SIGNAL_NODE_END:
             SignalNodeEnd(msg);
             break;
         case RCTXMT_GET_NODE_INFO:
             GetNodeInfo(sender, msg);
             break;
         case RCTXMT_GET_NUM_NODE_LIVE:
             GetNumNodeLive(sender, msg);
             break;
         case RCTXMT_GET_CREATE_READER_KEY:
             GetCreateEndpointKey(sender, msg);
             break;
         case RCTXMT_GET_READER_INFO:
             GetEndpointInfo(sender, msg);
             break;
         case RCTXMT_GET_CREATE_WRITER_KEY:
             GetCreateEndpointKey(sender, msg);
             break;
         case RCTXMT_GET_WRITER_INFO:
             GetEndpointInfo(sender, msg);
             break;
         case RCTXMT_CONNECT_ENDPOINTS:
             ConnectEndpoints(msg);
             break;
         case RCTXMT_TERMINATE:
             Terminate();
             break;
         case RCTXMT_LOG:
             LogMessage(sender + ":" + msg["msg"].AsString());
             break;
         default:
             ASSERT(false);
         }
     }
bool FileHandle::Eof () const inline inherited
Returns
the current end of file condition
Definition at line 115 of file FileHandle.h.
References FileHandle::eof, and FileHandle::file_lock.
Referenced by CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteContextDaemon::Client::Read(), and CPN::RemoteQueue::Read().
 { ALock al(file_lock); return eof; }
bool FileHandle::Eof (bool e) inline inherited
Set/reset the end of file condition.
Parameters
e the new end of file condition
Returns
the new end of file condition
Definition at line 120 of file FileHandle.h.
References FileHandle::eof, and FileHandle::file_lock.
 { ALock al(file_lock); return eof = e; }
int FileHandle::FD () const inline inherited
Returns
the current set file descriptor
Definition at line 106 of file FileHandle.h.
References FileHandle::fd, and FileHandle::file_lock.
Referenced by ServerSocketHandle::Accept(), CPN::RemoteContextDaemon::Client::Client(), SocketHandle::Connect(), CPN::ConnectionServer::ConnectWriter(), SocketHandle::CreatePair(), CPN::RemoteQueue::FileThreadEntryPoint(), FileHandle::Flush(), CPN::ConnectionServer::GetAddress(), SocketHandle::GetKeepAlive(), SocketHandle::GetLingerTimeout(), SocketHandle::GetNoDelay(), SocketHandle::GetPendingError(), SocketHandle::GetReceiveBufferSize(), SocketHandle::GetReceiveTimeout(), SocketHandle::GetSendBufferSize(), SocketHandle::GetSendTimeout(), FileHandle::IsBlocking(), ServerSocketHandle::Listen(), FileHandle::Poll(), Run(), FileHandle::SetBlocking(), SocketHandle::SetKeepAlive(), SocketHandle::SetLingerTimeout(), SocketHandle::SetNoDelay(), SocketHandle::SetReceiveBufferSize(), SocketHandle::SetReceiveTimeout(), SocketHandle::SetSendBufferSize(), SocketHandle::SetSendTimeout(), SocketHandle::ShutdownRead(), SocketHandle::ShutdownWrite(), and WakeupHandle::WakeupHandle().
 { ALock al(file_lock); return fd; }
int FileHandle::FD (int filed) inline inherited
Set the current file descriptor.
Parameters
filed the new file descriptor
Returns
the new file descriptor
Definition at line 111 of file FileHandle.h.
References FileHandle::fd, and FileHandle::file_lock.
 { ALock al(file_lock); return fd = filed; }
void FileHandle::Flush () inherited
Tell the OS to flush any buffers it has. May not be supported for all file types.
Definition at line 293 of file FileHandle.cc.
References FileHandle::FD().
{
     if (fsync(FD()) != 0) {
         throw ErrnoException();
     }
 }
bool ServerSocketHandle::GetReuseAddr () inline inherited
Definition at line 71 of file ServerSocketHandle.h.
References ServerSocketHandle::reuse_addr.
 { return reuse_addr; }
bool FileHandle::Good () const inline inherited
Convenience method for testing if the file this FileHandle has is open and not at end of file.
Returns
true if open and not at end of file otherwise false
Definition at line 125 of file FileHandle.h.
References FileHandle::eof, FileHandle::fd, and FileHandle::file_lock.
Referenced by CPN::RemoteContext::EntryPoint(), and CPN::RemoteContextDaemon::Client::Read().
 { ALock al(file_lock); return !(eof || fd == -1); }
bool FileHandle::IsBlocking () const inherited
Test if the current file is in blocking or non blocking mode.
Returns
true if blocking or false if non blocking
Definition at line 128 of file FileHandle.cc.
References FileHandle::FD().
{
     return IsBlocking(FD());
 }
bool FileHandle::IsBlocking (int fd) static inherited
Test the given file descriptor if it is in blocking mode.
Parameters
fd the file descriptor to test
Returns
true if blocking or false if non blocking
Definition at line 132 of file FileHandle.cc.
{
     int flags = fcntl(fd, F_GETFL, 0);
     if (-1 == flags) { throw ErrnoException(); }
     return !(flags & O_NONBLOCK);
 }
bool CPN::RemoteContextServer::IsTerminated () const inline inherited
Returns
whether or not the context is in the shutdown state.
Definition at line 125 of file RemoteContextServer.h.
References CPN::RemoteContextServer::shutdown.
Referenced by BroadcastMessage(), CPN::RemoteContextServer::DispatchMessage(), Run(), SendMessage(), and Terminate().
 { return shutdown; }
void ServerSocketHandle::Listen (const SocketAddress & addr, int queuelength = 256) inherited
Open a new socket and try to listen on the given SocketAddress.
Definition at line 30 of file ServerSocketHandle.cc.
Referenced by CPN::ConnectionServer::ConnectionServer(), ServerSocketHandle::Listen(), RemoteContextDaemon(), and ServerSocketHandle::ServerSocketHandle().
{
     int error = 0;
     if (!Listen(addr, queuelength, error)) { throw ErrnoException(error); }
 }
void ServerSocketHandle::Listen (const SockAddrList & addrs, int queuelength = 256) inherited
Open a new socket and try to listen on one of the addresses in the given list.
Definition at line 35 of file ServerSocketHandle.cc.
References ServerSocketHandle::Listen().
{
     int error = 0;
     bool success = false;
     for (SockAddrList::const_iterator itr = addrs.begin();
             itr != addrs.end(); ++itr) {
         success = Listen(*itr, queuelength, error);
         if (success) break;
     }
     if (!success) throw ErrnoException(error);
 }
void CPN::RemoteContextDaemon::LogMessage (const std::string & msg) private virtual
Log a message.
Parameters
msg the message to be logged
Implements CPN::RemoteContextServer.
Definition at line 138 of file RemoteContextDaemon.cc.
References CPN::RemoteContextServer::dbprintf().
{
         dbprintf(1, "log:%s\n", msg.c_str());
     }
virtual void FileHandle::OnReadable () inline protected virtual inherited
Called by Poll when it detects that the file is readable.
Reimplemented in WakeupHandle.
Definition at line 210 of file FileHandle.h.
References FileHandle::Readable().
Referenced by FileHandle::Poll().
 { Readable(true); }
virtual void FileHandle::OnWriteable () inline protected virtual inherited
Called by Poll when it detects that the file is writeable.
Definition at line 212 of file FileHandle.h.
References FileHandle::Writeable().
Referenced by FileHandle::Poll().
 { Writeable(true); }
int FileHandle::Poll (IteratorRef< FileHandle * > begin, IteratorRef< FileHandle * > end, double timeout) static inherited
poll a list of FileHandles for any activity and call the appropriate On method.
Definition at line 34 of file FileHandle.cc.
References FileHandle::FD(), FileHandle::fd, FileHandle::OnReadable(), FileHandle::OnWriteable(), FileHandle::Readable(), and FileHandle::Writeable().
Referenced by CPN::RemoteContext::EntryPoint(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::ConnectionServer::Poll(), FileHandle::Poll(), and Run().
{
     fd_set rfd;
     fd_set wfd;
     FD_ZERO(&rfd);
     FD_ZERO(&wfd);
     int maxfd = 0;
     IteratorRef<FileHandle*> itr = begin;
     while (itr != end) {
         FileHandle *han = *itr;
         int fd = han->FD();
         if (fd < 0) {
             return -1;
         } else {
             bool set = false;
             if (!han->Readable()) {
                 FD_SET(fd, &rfd);
                 set = true;
             }
             if (!han->Writeable()) {
                 FD_SET(fd, &wfd);
                 set = true;
             }
             if (set) { maxfd = std::max(maxfd, fd); }
         }
         ++itr;
     }
     timeval tv;
     timeval *ptv = 0;
     if (timeout >= 0) {
         tv.tv_sec = (int)timeout;
         tv.tv_usec = (int)((timeout - tv.tv_sec) * 1e6);
         ptv = &tv;
     }
     int ret = select(maxfd + 1, &rfd, &wfd, 0, ptv);
     if (ret < 0) {
         if (errno == EINTR) {
             return 0;
         }
         throw ErrnoException();
     }
     itr = begin;
     while (itr != end) {
         FileHandle *han = *itr;
         int fd = han->FD();
         if (fd >= 0) {
             if (FD_ISSET(fd, &rfd)) {
                 han->OnReadable();
             }
             if (FD_ISSET(fd, &wfd)) {
                 han->OnWriteable();
             }
         }
         ++itr;
     }
     return ret;
 }
int FileHandle::Poll (double timeout) inherited
Poll the current file descriptor for activity specified by the current readable or writeable status, if false poll that value, and call one of OnWriteable or OnReadable whos default action is to set Readable or Writeable to true.
Parameters
timeout -1 to wait forever for activity 0 to poll and return immediately or a time to wait in seconds.
Returns
zero if timed out, positive if an event occurred or negative if an error occurred.
Definition at line 106 of file FileHandle.cc.
References FileHandle::Poll().
{
     FileHandle *fh = this;
     return Poll(&fh, &fh + 1, timeout);
 }
void CPN::RemoteContextDaemon::Read () private
Definition at line 104 of file RemoteContextDaemon.cc.
References ServerSocketHandle::Accept(), Client, clients, and FileHandle::Readable().
Referenced by Run().
{
         int nfd = Accept();
         if (nfd >= 0) {
             ClientPtr conn = ClientPtr(new Client(this, nfd));
             clients.insert(std::make_pair(conn->GetName(), conn));
             Readable(false);
         }
     }
unsigned FileHandle::Read (void * ptr, unsigned len) inherited
Read data from the file descriptor.
Will set the end of file condition if read detects end of file.
Note
All the read functions will set readable to false if they read less than the requested amount or we are non blocking and a would block condition happened.
Parameters
ptr pointer to write data to
len the maximum number of bytes to write to ptr
Returns
0 if no bytes read (check Eof) or the number of bytes read
Definition at line 159 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::Readable(), and FileHandle::readable.
Referenced by CPN::RemoteQueue::D4RTagPacket(), and WakeupHandle::Read().
{
     int filed;
     {
         ALock al(file_lock);
         if (eof || fd == -1) { return 0; }
         filed = fd;
     }
     unsigned bytesread = 0;
     int num = read(filed, ptr, len);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN:
             Readable(false);
         case EINTR:
         case ENOMEM:
             break;
         default:
             throw ErrnoException(error);
         }
     } else if (num == 0 && len != 0) {
         ALock al(file_lock);
         eof = true;
         readable = false;
     } else {
         if (unsigned(num) < len) { Readable(false); }
         bytesread = num;
     }
     return bytesread;
 }
bool FileHandle::Readable (bool r) inline inherited
Set that the file is currently readable or not.
Parameters
r true or false
Returns
the new readable status
Definition at line 86 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::readable.
Referenced by CPN::RemoteContext::EntryPoint(), FileHandle::Poll(), CPN::ConnectionServer::Poll(), and CPN::RemoteQueue::Read().
 { ALock al(file_lock); return readable = r; }
bool FileHandle::Readable () const inline inherited
Gives the current readability status of the file.
Returns
true if it is known that a read will not block
Definition at line 91 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::readable.
Referenced by ServerSocketHandle::Accept(), CPN::RemoteContextDaemon::Client::Client(), FileHandle::OnReadable(), Read(), FileHandle::Read(), FileHandle::Readv(), SocketHandle::Recv(), Run(), and WakeupHandle::WakeupHandle().
 { ALock al(file_lock); return readable; }
unsigned FileHandle::Readv (const iovec * iov, int iovcnt) inherited
scatter gather io version of Read
Returns
see Read
Definition at line 190 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::Readable(), and FileHandle::readable.
Referenced by CPN::RemoteQueue::EnqueuePacket().
{
     int filed;
     {
         ALock al(file_lock);
         if (eof || fd == -1) { return 0; }
         filed = fd;
     }
     unsigned len = 0;
     for (int i = 0; i < iovcnt; ++i) {
         len += iov[i].iov_len;
     }
     unsigned bytesread = 0;
     int num = readv(filed, iov, iovcnt);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN:
             Readable(false);
         case EINTR:
         case ENOMEM:
             break;
         default:
             throw ErrnoException(error);
         }
     } else if (num == 0 && len != 0) {
         ALock al(file_lock);
         eof = true;
         readable = false;
     } else {
         if (unsigned(num) < len) { Readable(false); }
         bytesread = num;
     }
     return bytesread;
 }
void FileHandle::Reset () inherited
Clear all internal state including the file descriptor! WARNING does not close the file!
Definition at line 138 of file FileHandle.cc.
References FileHandle::eof, FileHandle::fd, FileHandle::file_lock, FileHandle::readable, and FileHandle::writeable.
Referenced by CPN::ConnectionServer::ConnectWriter(), CPN::RemoteQueue::FileThreadEntryPoint(), and FileHandle::~FileHandle().
{
     ALock al(file_lock);
     readable = false;
     writeable = false;
     eof = false;
     fd = -1;
 }
void CPN::RemoteContextDaemon::Run ()
Run the actual Context returns when the context is terminated and all clients have disconnected.
Definition at line 45 of file RemoteContextDaemon.cc.
References clients, FileHandle::Closed(), CPN::RemoteContextServer::dbprintf(), FileHandle::FD(), SocketAddress::GetHostName(), SocketAddress::GetServName(), CPN::RemoteContextServer::IsTerminated(), FileHandle::Poll(), Read(), FileHandle::Readable(), SocketAddress::SetFromSockName(), and Terminate().
{
         Readable(false);
         SocketAddress addr;
         addr.SetFromSockName(FD());
         dbprintf(1, "Listening on %s:%s\n", addr.GetHostName().c_str(), addr.GetServName().c_str());
         while (true) {
             std::vector<FileHandle*> fds;
             if (!Closed()) {
                 if (Readable()) {
                     Read();
                 }
                 fds.push_back(this);
             }
             ClientMap::iterator itr = clients.begin();
             while (itr != clients.end()) {
                 ClientPtr client = itr->second;
                 if (client->Closed()) {
                     ClientMap::iterator todelete = itr;
                     ++itr;
                     clients.erase(todelete);
                     Terminate();
                 } else {
                     if (client->Readable()) {
                         client->Read();
                     }
                     fds.push_back(client.get());
                     ++itr;
                 }
             }
             if ((clients.empty() && IsTerminated()) || fds.empty()) {
                 break;
             }
             Poll(fds.begin(), fds.end(), -1);
         }
     }
void CPN::RemoteContextDaemon::SendMessage (const std::string & recipient, const Variant & msg) private virtual
Send the given message to the given client.
Parameters
recipient the id (previously used in DispatchMessage sender)
msg the message to be sent to the client
Implements CPN::RemoteContextServer.
Definition at line 113 of file RemoteContextDaemon.cc.
References ASSERT, clients, CPN::RemoteContextServer::dbprintf(), and CPN::RemoteContextServer::IsTerminated().
{
         if (IsTerminated()) {
             dbprintf(1, "Trying to send a reply after shutdown\n%s:%s",
                     recipient.c_str(), libvariant::SerializeJSON(msg).c_str());
             return;
         }
         ClientMap::iterator entry = clients.find(recipient);
         ASSERT(entry != clients.end());
         dbprintf(4, "reply:%s:%s\n", recipient.c_str(), libvariant::SerializeJSON(msg).c_str());
         entry->second->Send(msg);
     }
void FileHandle::SetBlocking (bool blocking) inherited
Manipulate how the current file handles blocking.
Parameters
blocking true to set to blocking mode (default) false to set to non blocking mode.
In non blocking mode all reads and writes will not block. Use Poll to block.
Definition at line 111 of file FileHandle.cc.
References FileHandle::FD().
Referenced by WakeupHandle::WakeupHandle().
{
     SetBlocking(FD(), blocking);
 }
void FileHandle::SetBlocking (int fd, bool blocking) static inherited
a convenience method that allows one to set the same blocking parameters for a file descriptor without setting it inside a FileHandle.
Parameters
fd the file descriptor
blocking true or false see SetBlock
Definition at line 115 of file FileHandle.cc.
{
     int flags = fcntl(fd, F_GETFL, 0);
     if (-1 == flags) { throw ErrnoException(); }
     if (blocking) {
         flags &= ~O_NONBLOCK;
     } else {
         flags |= O_NONBLOCK;
     }
     if (fcntl(fd, F_SETFL, flags) != 0) {
         throw ErrnoException();
     }
 }
void ServerSocketHandle::SetReuseAddr (bool reuse = true) inline inherited
Turn on reuse of the address. Only takes effect if set before Listen.
Definition at line 70 of file ServerSocketHandle.h.
References ServerSocketHandle::reuse_addr.
Referenced by RemoteContextDaemon().
 { reuse_addr = true; }
void CPN::RemoteContextDaemon::Terminate () private virtual
Cause the context to go into the shutdown state.
Reimplemented from CPN::RemoteContextServer.
Definition at line 81 of file RemoteContextDaemon.cc.
References clients, FileHandle::Close(), CPN::RemoteContextServer::IsTerminated(), and CPN::RemoteContextServer::Terminate().
Referenced by Run().
{
         if (IsTerminated()) return;
         CPN::RemoteContextServer::Terminate();
         Close();
         ClientMap::iterator itr = clients.begin();
         while (itr != clients.end()) {
             ClientPtr client = itr->second;
             if (!client->Closed()) {
                 try {
                     client->ShutdownWrite();
                 } catch (const ErrnoException &e) {
                     //ignore
                 }
             }
             ++itr;
         }
     }
void CPN::RemoteContextDaemon::Terminate (const std::string & name) private
Definition at line 99 of file RemoteContextDaemon.cc.
References clients, and CPN::RemoteContextServer::dbprintf().
{
         dbprintf(1, "Terminating %s\n", name.c_str());
         clients[name]->Close();
     }
unsigned FileHandle::Write (const void * ptr, unsigned len) inherited
Write data to the file descriptor.
Note
All write functions will set Writeable to false if they write less than the amount requested or if the file is in non blocking mode and the write returned would block.
Parameters
ptr pointer to beginning of data to write
len length of data to write
Returns
number of bytes written
Definition at line 225 of file FileHandle.cc.
References FileHandle::fd, FileHandle::file_lock, and FileHandle::Writeable().
Referenced by CPN::ConnectionServer::ConnectWriter(), CPN::RemoteContextDaemon::Client::Send(), CPN::RemoteContext::SendMessage(), and CPN::RemoteQueue::WriteBytes().
{
     int filed;
     {
         ALock al(file_lock);
         if (fd == -1) { return 0; }
         filed = fd;
     }
     unsigned written = 0;
     int num = write(filed, ptr, len);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN: // Would block
         //case EWOULDBLOCK:
             Writeable(false);
         case EINTR: // Returned because of signal
         case ENOMEM:
         case ENOBUFS: // Buffers are full
             break;
         case EPIPE:
         case EBADF:
         case EFAULT:
         case EFBIG:
         case EINVAL:
         case EIO:
         case ENOSPC:
         default:
             throw ErrnoException(error);
         }
     } else {
         if (unsigned(num) < len) { Writeable(false); }
         written = num;
     }
     return written;
 }
bool FileHandle::Writeable (bool w) inline inherited
Set that this file is currently writeable or not.
Parameters
w true or false
Returns
the new writeable status
Definition at line 97 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::writeable.
Referenced by FileHandle::Poll().
 { ALock al(file_lock); return writeable = w; }
bool FileHandle::Writeable () const inline inherited
Gives the current writability status of the file.
Returns
true if it is known that a write will not block
Definition at line 102 of file FileHandle.h.
References FileHandle::file_lock, and FileHandle::writeable.
Referenced by FileHandle::OnWriteable(), SocketHandle::Send(), WakeupHandle::WakeupHandle(), FileHandle::Write(), and FileHandle::Writev().
 { ALock al(file_lock); return writeable; }
unsigned FileHandle::Writev (const iovec * iov, int iovcnt) inherited
scatter gather io version of Write
Returns
see Write
Definition at line 261 of file FileHandle.cc.
References FileHandle::fd, FileHandle::file_lock, and FileHandle::Writeable().
Referenced by CPN::RemoteQueue::WriteBytes().
{
     int filed;
     {
         ALock al(file_lock);
         if (fd == -1) { return 0; }
         filed = fd;
     }
     unsigned written = 0;
     int num = writev(filed, iov, iovcnt);
     if (num < 0) {
         int error = errno;
         switch (error) {
         case EAGAIN:
             Writeable(false);
         case EINTR:
         case ENOMEM:
         case ENOBUFS:
             break;
         default:
             throw ErrnoException(error);
         }
     } else {
         unsigned len = 0;
         for (int i = 0; i < iovcnt; ++i) {
             len += iov[i].iov_len;
         }
         if (unsigned(num) < len) { Writeable(false); }
         written = num;
     }
     return written;
 }
Friends And Related Function Documentation
friend class Client friend
Definition at line 73 of file RemoteContextDaemon.h.
Referenced by Read().
Member Data Documentation
ClientMap CPN::RemoteContextDaemon::clients private
Definition at line 77 of file RemoteContextDaemon.h.
Referenced by BroadcastMessage(), Read(), Run(), SendMessage(), and Terminate().
bool FileHandle::eof protected inherited
Definition at line 217 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Eof(), FileHandle::Good(), FileHandle::Read(), FileHandle::Readv(), SocketHandle::Recv(), and FileHandle::Reset().
int FileHandle::fd protected inherited
Definition at line 214 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Closed(), FileHandle::FD(), FileHandle::Good(), FileHandle::Poll(), FileHandle::Read(), FileHandle::Readv(), SocketHandle::Recv(), FileHandle::Reset(), SocketHandle::Send(), FileHandle::Write(), FileHandle::Writev(), and FileHandle::~FileHandle().
PthreadMutex FileHandle::file_lock mutable protected inherited
Definition at line 213 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Closed(), FileHandle::Eof(), FileHandle::FD(), FileHandle::Good(), FileHandle::Read(), FileHandle::Readable(), FileHandle::Readv(), SocketHandle::Recv(), FileHandle::Reset(), SocketHandle::Send(), WakeupHandle::SendWakeup(), FileHandle::Write(), FileHandle::Writeable(), and FileHandle::Writev().
bool FileHandle::readable protected inherited
Definition at line 215 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Read(), FileHandle::Readable(), FileHandle::Readv(), SocketHandle::Recv(), and FileHandle::Reset().
bool FileHandle::writeable protected inherited
Definition at line 216 of file FileHandle.h.
Referenced by FileHandle::Close(), FileHandle::Reset(), and FileHandle::Writeable().
The documentation for this class was generated from the following files:
include/cpn/remote_context/RemoteContextDaemon.h
lib/RemoteContextDaemon.cc