CPN: PthreadKey< T > Class Template Reference
PthreadKey< T > Class Template Reference
#include <PthreadKey.h>
Public Member Functions
PthreadKey (void(*destructor)(T)=0)
~PthreadKey (void)
operator pthread_key_t * (void)
operator const pthread_key_t * (void) const
T Get (void) const
PthreadKey< T > & Set (T val)
int Error (void)
void Clear (void)
Protected Member Functions
void TrapError (int result)
Protected Attributes
int error
Private Attributes
pthread_key_t theKey
Detailed Description
template<class T>
class PthreadKey< T >
Definition at line 35 of file PthreadKey.h.
Constructor & Destructor Documentation
template<class T > PthreadKey< T >::PthreadKey (void(*)(T) destructor = 0) inline
Definition at line 37 of file PthreadKey.h.
References PthreadKey< T >::theKey, and PthreadErrorHandler::TrapError().
         { TrapError(pthread_key_create(&theKey, (void(*)(void*))destructor)); }
template<class T > PthreadKey< T >::~PthreadKey (void) inline
Definition at line 39 of file PthreadKey.h.
References PthreadKey< T >::theKey, and PthreadErrorHandler::TrapError().
         { try { TrapError(pthread_key_delete(theKey)); } catch (...) { std::terminate(); } }
Member Function Documentation
void PthreadErrorHandler::Clear (void) inline inherited
Definition at line 40 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { error = 0; }
int PthreadErrorHandler::Error (void) inline inherited
Definition at line 39 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { return error; }
template<class T > T PthreadKey< T >::Get (void) const inline
Definition at line 45 of file PthreadKey.h.
References PthreadKey< T >::theKey.
                     { return (T)pthread_getspecific(theKey); }
template<class T > PthreadKey< T >::operator const pthread_key_t * (void) const inline
Definition at line 43 of file PthreadKey.h.
References PthreadKey< T >::theKey.
 { return &theKey; }
template<class T > PthreadKey< T >::operator pthread_key_t * (void) inline
Definition at line 42 of file PthreadKey.h.
References PthreadKey< T >::theKey.
 { return &theKey; }
template<class T > PthreadKey<T>& PthreadKey< T >::Set (T val) inline
Definition at line 48 of file PthreadKey.h.
References PthreadKey< T >::theKey, and PthreadErrorHandler::TrapError().
                     {   TrapError(pthread_setspecific(theKey, (void*)val));
                         return *this;
                     }
void PthreadErrorHandler::TrapError (int result) inline protected inherited
Definition at line 48 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
Referenced by PthreadCondition::Broadcast(), PthreadAttr::DetachState(), PthreadBase::Join(), Pthread::Join(), PthreadMutex::Lock(), PthreadMutex::Poll(), Pthread::Pthread(), PthreadAttr::PthreadAttr(), PthreadBase::PthreadBase(), PthreadCondition::PthreadCondition(), PthreadConditionAttr::PthreadConditionAttr(), PthreadKey< T >::PthreadKey(), PthreadMutex::PthreadMutex(), PthreadMutexAttr::PthreadMutexAttr(), PthreadReadWriteLock::ReadUnlock(), PthreadAttr::ScheduleScope(), PthreadKey< T >::Set(), PthreadCondition::Signal(), PthreadCondition::TimedWait(), PthreadMutex::Unlock(), PthreadCondition::Wait(), PthreadReadWriteLock::WriteUnlock(), PthreadAttr::~PthreadAttr(), PthreadCondition::~PthreadCondition(), PthreadConditionAttr::~PthreadConditionAttr(), PthreadKey< T >::~PthreadKey(), PthreadMutex::~PthreadMutex(), and PthreadMutexAttr::~PthreadMutexAttr().
 {
     if (err) {
         error = err;
         throw ErrnoException(err);
     }
 }
Member Data Documentation
int PthreadErrorHandler::error protected inherited
Definition at line 43 of file PthreadErrorHandler.h.
Referenced by PthreadErrorHandler::Clear(), PthreadErrorHandler::Error(), PthreadErrorHandler::PthreadErrorHandler(), and PthreadErrorHandler::TrapError().
template<class T > pthread_key_t PthreadKey< T >::theKey private
Definition at line 54 of file PthreadKey.h.
Referenced by PthreadKey< T >::Get(), PthreadKey< T >::operator const pthread_key_t *(), PthreadKey< T >::operator pthread_key_t *(), PthreadKey< T >::PthreadKey(), PthreadKey< T >::Set(), and PthreadKey< T >::~PthreadKey().
The documentation for this class was generated from the following file:
include/cpn/threading/PthreadKey.h