CPN: MirrorBufferSet Class Reference
MirrorBufferSet Class Reference
#include <MirrorBufferSet.h>
Public Types
enum { eNotSupported =0, eSupportedPosixShm, eSupportedTmpFile }
typedef unsigned long ulong
Public Member Functions
MirrorBufferSet (ulong bufferSz, ulong mirrorSz, int nBuffers=1)
~MirrorBufferSet (void)
ulong BufferSize (void) const
ulong MirrorSize (void) const
ulong NumBuffers (void) const
operator void * (void) const
Static Public Member Functions
static int Supported (void)
static ulong PageSize (void)
Protected Member Functions
int GetFileDescriptor (void)
Protected Attributes
void * bufferBase
ulong bufferSize
ulong mirrorSize
int numBuffers
char fileName [112]
Detailed Description
Definition at line 27 of file MirrorBufferSet.h.
Member Typedef Documentation
typedef unsigned long MirrorBufferSet::ulong
Definition at line 29 of file MirrorBufferSet.h.
Member Enumeration Documentation
anonymous enum
Enumerator
eNotSupported
eSupportedPosixShm
eSupportedTmpFile
Definition at line 38 of file MirrorBufferSet.h.
 { eNotSupported=0, eSupportedPosixShm, eSupportedTmpFile };
Constructor & Destructor Documentation
MirrorBufferSet::MirrorBufferSet (ulong bufferSz, ulong mirrorSz, int nBuffers = 1)
Definition at line 140 of file MirrorBufferSet.cc.
References bufferBase, bufferSize, fileName, fprintf1, fprintf2, GetFileDescriptor(), MAP_FAILED, MAP_NORESERVE, mirrorSize, numBuffers, PageSize(), and StrError().
 :   bufferBase(0),
     bufferSize(bufferSz),
     mirrorSize(mirrorSz),
     numBuffers(nBuffers)
 {
     fileName[0] = 0;
     ulong pageSize = PageSize();
     // if bufferSize or mirrorSize are not a multiple of pageSize, round them up
     if (bufferSize % pageSize) {
         bufferSize += pageSize - (bufferSize % pageSize);
     }
     if (mirrorSize % pageSize) {
         mirrorSize += pageSize - (mirrorSize % pageSize);
     }
 #if 1
     // do a sanity check for our math
     if ( bufferSize % pageSize)
         fprintf(stderr, "### Error: bufferSize = %lu is not a multiple of pageSize = %lu\n",
             bufferSize, pageSize);
     if ( mirrorSize % pageSize)
         fprintf(stderr, "### Error: mirrorSize = %lu is not a multiple of pageSize = %lu\n",
             mirrorSize, pageSize);
 #endif
     int fd = GetFileDescriptor();
     // make the file large enough
     ulong numBytes = (bufferSize+mirrorSize) * numBuffers;
     if ( ftruncate(fd, numBytes) ) {
         perror("ftruncate");
         close(fd);
         throw std::runtime_error(StrError(errno));
     }
     // map the entire buffer space, so there will be enough space reserved
     fprintf1((stderr,"MirrorBufferSet: reserving %lu bytes for mapping ", numBytes));
     caddr_t baseAddr = (caddr_t) mmap(0, numBytes, PROT_READ|PROT_WRITE,
             MAP_SHARED|MAP_NORESERVE, fd, (off_t)0);
     if (baseAddr == MAP_FAILED) {
         fprintf1((stderr,"failed\n"));
         perror("mmap");
         close(fd);
         throw std::runtime_error(StrError(errno));
     }
     bufferBase = baseAddr;
     fprintf1((stderr,"[%p - %p)\n", (void*)baseAddr, (void*)(baseAddr+numBytes)));
     fprintf1((stderr,"MirrorBufferSet: file \"%s\" is %d bytes\n",
         fileName, (int)(bufferSize*numBuffers)));
     // now map each of the individual buffers twice
     for (int buf=0; buf<numBuffers; buf++) {
         // once for the buffer
         caddr_t theAddr     = baseAddr+buf*(bufferSize+mirrorSize);
         size_t  theSize     = bufferSize;
         off_t  theOffset   = buf*bufferSize;
         fprintf2((stderr,"mapping 0x%06lX bytes @ offset 0x%06lX ", (long unsigned)theSize, (long unsigned)theOffset));
         caddr_t addr = (caddr_t) mmap(theAddr, theSize, PROT_READ|PROT_WRITE,
             MAP_SHARED|MAP_FIXED|MAP_NORESERVE, fd, theOffset);
         if (addr == MAP_FAILED) {
             fprintf2((stderr,"failed\n"));
             perror("mmap");
             close(fd);
             throw std::runtime_error(StrError(errno));
         }
         fprintf2((stderr,"to [%p - %p)\n", (void*)theAddr, (void*)(theAddr+theSize)));
         if (addr!=theAddr) {
             fprintf(stderr, "### Error: mapped to 0x%p instead of 0x%p\n",
                 addr, theAddr );
             close(fd);
             throw std::runtime_error(StrError(errno));
         }
         // and again for the mirror
         theAddr     +=bufferSize;
         theSize     = mirrorSize;
         fprintf2((stderr,"mapping 0x%06lX bytes @ offset 0x%06lX ", (long unsigned)theSize, (long unsigned)theOffset));
         addr = (caddr_t) mmap(theAddr, theSize, PROT_READ|PROT_WRITE,
             MAP_SHARED|MAP_FIXED|MAP_NORESERVE, fd, theOffset);
         if (addr == MAP_FAILED) {
             fprintf2((stderr,"failed\n"));
             perror("mmap");
             close(fd);
             throw std::runtime_error(StrError(errno));
         }
         fprintf2((stderr,"to [%p - %p)\n", (void*)theAddr, (void*)(theAddr+theSize)));
         if (addr!=theAddr) {
             fprintf(stderr, "### Error: mapped to 0x%p instead of 0x%p\n", addr, theAddr );
             close(fd);
             throw std::runtime_error(StrError(errno));
         }
     }
     // close the file
     if ( close(fd) ) {
         perror("close");
     }
 }
MirrorBufferSet::~MirrorBufferSet (void)
Definition at line 290 of file MirrorBufferSet.cc.
References bufferBase, bufferSize, fileName, fprintf2, mirrorSize, and numBuffers.
 {
     if (!bufferBase) return;
     // unmap the file
     if ( munmap((caddr_t)bufferBase, (bufferSize+mirrorSize)*numBuffers) ) {
         perror("munmap");
     }
     fprintf2((stderr,"unmapped- \"%s\" [%p - %p), %lu bytes\n",
         fileName, bufferBase,
         (void*)((char*)bufferBase+((bufferSize+mirrorSize)*numBuffers)),
         ((bufferSize+mirrorSize)*numBuffers)));
 }
Member Function Documentation
ulong MirrorBufferSet::BufferSize (void) const inline
Definition at line 34 of file MirrorBufferSet.h.
References bufferSize.
Referenced by ThresholdQueueBase::AllocateBuf().
 { return bufferSize; }
int MirrorBufferSet::GetFileDescriptor (void) protected
Definition at line 244 of file MirrorBufferSet.cc.
References fileName, and fprintf2.
Referenced by MirrorBufferSet().
 {
     // get a temporary file name
 #if MBS_USE_POSIX_SHM
     unsigned i = 0;
     while (true) {
         sprintf(fileName, "/MirrorBufferSet-%u", i);
         #if defined(OS_IRIX) || defined(OS_HPUX)
         // these platforms don't do shm_open as defined in the spec
         tmpnam(fileName);
         fprintf2((stderr,"tmpnam returned \"%s\"\n",fileName));
         #endif
         fprintf2((stderr,"calling shm_open with \"%s\"\n",fileName));
         int fd = shm_open(fileName,O_RDWR|O_CREAT|O_EXCL,0600);
         if (fd < 0) {
             if (errno == EEXIST) {
                 ++i;
             } else{
                 fprintf(stderr, "shm_open \"%s\": ", fileName);
                 perror(0);
                 return -1;
             }
         } else {
             // remove the shared memory object
             if ( shm_unlink(fileName) ) {
                 fprintf(stderr, "### shm_unlink(\"%s\") failed: ", fileName);
                 perror(0);
             }
             return fd;
         }
     }
 #else
     sprintf(fileName, "/tmp/MirrorBufferSet-XXXXXX");
     int fd = mkstemp(fileName);
     // remove the temporary file
     if ( unlink(fileName) ) {
         fprintf(stderr, "### unlink(\"%s\") failed: ", fileName);
         perror(0);
     }
     return fd;
 #endif
 }
ulong MirrorBufferSet::MirrorSize (void) const inline
Definition at line 35 of file MirrorBufferSet.h.
References mirrorSize.
Referenced by ThresholdQueueBase::AllocateBuf().
 { return mirrorSize; }
ulong MirrorBufferSet::NumBuffers (void) const inline
Definition at line 36 of file MirrorBufferSet.h.
References numBuffers.
 { return numBuffers; }
MirrorBufferSet::operator void * (void) const inline
Definition at line 43 of file MirrorBufferSet.h.
References bufferBase.
 { return bufferBase; }
unsigned long MirrorBufferSet::PageSize (void) static
Definition at line 307 of file MirrorBufferSet.cc.
Referenced by MirrorBufferSet(), and ThresholdQueueBase::ThresholdQueueBase().
 {
 #ifdef __APPLE__
     return getpagesize();
 #else
     return sysconf(_SC_PAGESIZE);
 #endif
 }
int MirrorBufferSet::Supported (void) static
Definition at line 27 of file MirrorBufferSet.cc.
References eNotSupported, eSupportedPosixShm, and eSupportedTmpFile.
Referenced by ThresholdQueueBase::AllocateBuf().
 {
     #if !MirrorBufferSet_SUPPORTED
         return eNotSupported;
     #endif
     #if MBS_USE_POSIX_SHM
         return eSupportedPosixShm;
     #else
         return eSupportedTmpFile;
     #endif
 }
Member Data Documentation
void* MirrorBufferSet::bufferBase protected
Definition at line 48 of file MirrorBufferSet.h.
Referenced by MirrorBufferSet(), operator void *(), and ~MirrorBufferSet().
ulong MirrorBufferSet::bufferSize protected
Definition at line 49 of file MirrorBufferSet.h.
Referenced by BufferSize(), MirrorBufferSet(), and ~MirrorBufferSet().
char MirrorBufferSet::fileName[112] protected
Definition at line 52 of file MirrorBufferSet.h.
Referenced by GetFileDescriptor(), MirrorBufferSet(), and ~MirrorBufferSet().
ulong MirrorBufferSet::mirrorSize protected
Definition at line 50 of file MirrorBufferSet.h.
Referenced by MirrorBufferSet(), MirrorSize(), and ~MirrorBufferSet().
int MirrorBufferSet::numBuffers protected
Definition at line 51 of file MirrorBufferSet.h.
Referenced by MirrorBufferSet(), NumBuffers(), and ~MirrorBufferSet().
The documentation for this class was generated from the following files:
lib/MirrorBufferSet.h
lib/MirrorBufferSet.cc