CPN: Pthread Class Reference
Pthread Class Reference abstract
#include <PthreadLib.h>
Public Member Functions
Pthread (void)
Pthread (const PthreadAttr &attr)
virtual ~Pthread (void)
void Start (void)
int Running (void)
int Done (void)
void * Join (void)
operator pthread_t * (void)
operator pthread_t (void)
int operator== (pthread_t t2)
int Detach (void)
int Cancel (void)
int SendSignal (int sig)
int Kill (int sig)
int Error (void)
void Clear (void)
Static Public Member Functions
static pthread_t Self (void)
static void TestCancel (void)
static void Exit (void *value)
static int SendSignal (pthread_t thd, int sig)
static int Kill (pthread_t thd, int sig)
static int GetSignalMask (sigset_t *oldSet)
static int SetSignalMask (const sigset_t *set, sigset_t *oldSet=0)
static int BlockSignals (const sigset_t *set, sigset_t *oldSet=0)
static int UnblockSignals (const sigset_t *set, sigset_t *oldSet=0)
static int CancelEnable (void)
static int CancelDisable (void)
static int CancelDeferred (void)
static int CancelAsynchronous (void)
Protected Member Functions
virtual void * EntryPoint (void)=0
void TrapError (int result)
Protected Attributes
pthread_t theThread
int error
Private Types
enum PthreadState {
uninitialized = 0, created, started, running,
done, joined, canceled
}
Static Private Member Functions
static void * PthreadEntryPoint (void *arg)
static void PthreadCleanup (void *arg)
Private Attributes
PthreadMutex mutex
PthreadCondition cond
void * returnResult
bool inJoin
PthreadState state
Detailed Description
Definition at line 56 of file PthreadLib.h.
Member Enumeration Documentation
enum Pthread::PthreadState private
Enumerator
uninitialized
created
started
running
done
joined
canceled
Definition at line 89 of file PthreadLib.h.
 { uninitialized = 0, created, started, running, done, joined, canceled };
Constructor & Destructor Documentation
Pthread::Pthread (void)
Definition at line 32 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), cond, created, inJoin, mutex, PthreadEntryPoint(), returnResult, state, PthreadBase::theThread, PthreadErrorHandler::TrapError(), and uninitialized.
 {
     PthreadMutexProtected p(mutex);
     returnResult = 0;
     inJoin = false;
     state = uninitialized;
     TrapError( pthread_create( &theThread, 0, PthreadEntryPoint, this) );
     state = created;
     cond.Broadcast();
 }
Pthread::Pthread (const PthreadAttr & attr)
Definition at line 46 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), cond, created, inJoin, mutex, PthreadEntryPoint(), returnResult, state, PthreadBase::theThread, PthreadErrorHandler::TrapError(), and uninitialized.
 {
     PthreadMutexProtected p(mutex);
     returnResult = 0;
     inJoin = false;
     state = uninitialized;
     //  It should simply be:
 //  TrapError( pthread_create(&theThread, attr, PthreadEntryPoint, this) );
     //  This is necessary because
     //      SGI's pthread_create is not const correct!!!
     pthread_attr_t* myAttr = (PthreadAttr&)attr;
     TrapError( pthread_create(&theThread, myAttr, PthreadEntryPoint, this) );
     state = created;
     cond.Broadcast();
 }
Pthread::~Pthread (void) virtual
Definition at line 67 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), canceled, cond, created, Join(), mutex, running, Start(), started, state, and uninitialized.
 {
     try {
         // Force the thread to terminate if it has not already done so.
         // Is it safe to do this to a thread that has already terminated?
         bool need_start = false;
         {
             PthreadMutexProtected p(mutex);
             switch (state) {
                 case uninitialized:
                     // should be impossible
                     return;
                 case created:
                     need_start = true;
                 case started:
                 case running:
                     state = canceled;
                     cond.Broadcast();
                 default:
                     break;
             }
         }
         if (need_start) { Start(); }
         // Now wait.
         Join();
     } catch (...) {
         std::terminate();
     }
 }
Member Function Documentation
static int PthreadBase::BlockSignals (const sigset_t * set, sigset_t * oldSet = 0) inline static inherited
Definition at line 77 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_BLOCK, set, oldSet); }
int PthreadBase::Cancel (void) inline inherited
Definition at line 59 of file PthreadBase.h.
References PthreadBase::theThread.
 { return pthread_cancel(theThread); }
int PthreadBase::CancelAsynchronous (void) static inherited
Definition at line 105 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, &oldState);
     return oldState;
 }
int PthreadBase::CancelDeferred (void) static inherited
Definition at line 95 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcanceltype(PTHREAD_CANCEL_DEFERRED, &oldState);
     return oldState;
 }
int PthreadBase::CancelDisable (void) static inherited
Definition at line 86 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &oldState);
     return oldState;
 }
int PthreadBase::CancelEnable (void) static inherited
Definition at line 76 of file PthreadBase.cc.
 {
     int oldState;
     pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldState);
     return oldState;
 }
void PthreadErrorHandler::Clear (void) inline inherited
Definition at line 40 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { error = 0; }
int PthreadBase::Detach (void) inline inherited
Definition at line 58 of file PthreadBase.h.
References PthreadBase::theThread.
 { return pthread_detach(theThread); }
int Pthread::Done (void) inline
Returns
true if Joining would not block.
Definition at line 72 of file PthreadLib.h.
References done, joined, mutex, and state.
                    {
         PthreadMutexProtected p(mutex);
         return state == done || state == joined;
     }
virtual void* Pthread::EntryPoint (void) protected pure virtual
Implemented in PthreadFunctionalTemplate< T >, and PthreadFunctional.
Referenced by PthreadEntryPoint().
int PthreadErrorHandler::Error (void) inline inherited
Definition at line 39 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { return error; }
static void PthreadBase::Exit (void * value) inline static inherited
Definition at line 64 of file PthreadBase.h.
 { pthread_exit(value); }
static int PthreadBase::GetSignalMask (sigset_t * oldSet) inline static inherited
Definition at line 73 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_SETMASK, 0, oldSet); }
void * Pthread::Join (void)
Definition at line 108 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), cond, inJoin, joined, mutex, returnResult, state, PthreadBase::theThread, PthreadErrorHandler::TrapError(), and PthreadCondition::Wait().
Referenced by ~Pthread().
{
     void *result = 0;
     {
         PthreadMutexProtected p(mutex);
         if (inJoin || state == joined) {
             while (state != joined) {
                 cond.Wait(mutex);
             }
             return returnResult;
         }
         inJoin = true;
     }
     TrapError( pthread_join(theThread, &result) );
     {
         PthreadMutexProtected p(mutex);
         returnResult = result;
         state = joined;
         cond.Broadcast();
         return returnResult;
     }
 }
int PthreadBase::Kill (int sig) inline inherited
Definition at line 68 of file PthreadBase.h.
References PthreadBase::theThread.
 { return pthread_kill(theThread, sig); }
static int PthreadBase::Kill (pthread_t thd, int sig) inline static inherited
Definition at line 71 of file PthreadBase.h.
 { return pthread_kill(thd, sig); }
PthreadBase::operator pthread_t (void) inline inherited
Definition at line 52 of file PthreadBase.h.
References PthreadBase::theThread.
 { return theThread; }
PthreadBase::operator pthread_t * (void) inline inherited
Definition at line 51 of file PthreadBase.h.
References PthreadBase::theThread.
 { return &theThread; }
int PthreadBase::operator== (pthread_t t2) inline inherited
Definition at line 54 of file PthreadBase.h.
References PthreadBase::theThread.
 { return pthread_equal(theThread, t2); }
void Pthread::PthreadCleanup (void * arg) static private
Definition at line 154 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), cond, done, mutex, and state.
Referenced by PthreadEntryPoint().
 {
     Pthread* ptr = (Pthread*) arg;
     PthreadMutexProtected p(ptr->mutex);
 //  ptr->Cleanup();     // the sub-classes have already been destructed
     ptr->state = done;
     ptr->cond.Broadcast();
 }
void * Pthread::PthreadEntryPoint (void * arg) static private
Definition at line 131 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), cond, created, EntryPoint(), mutex, PthreadCleanup(), running, started, state, PthreadBase::TestCancel(), and PthreadCondition::Wait().
Referenced by Pthread().
 {
     void* result = 0;
     Pthread* ptr = (Pthread*) arg;
     {
         PthreadMutexProtected p(ptr->mutex);
         while (ptr->state == created) {
             ptr->cond.Wait(ptr->mutex);
         }
         if (ptr->state != started) return 0;
         ptr->state = running;
         ptr->cond.Broadcast();
     }
     TestCancel();
     pthread_cleanup_push( PthreadCleanup, ptr);
     result = ptr->EntryPoint();
     pthread_cleanup_pop(1);
     return result;
 }
int Pthread::Running (void) inline
Definition at line 64 of file PthreadLib.h.
References mutex, running, and state.
                       {
         PthreadMutexProtected p(mutex);
         return state == running;
     }
static pthread_t PthreadBase::Self (void) inline static inherited
Definition at line 61 of file PthreadBase.h.
Referenced by PthreadBase::PthreadBase().
 { return pthread_self(); }
int PthreadBase::SendSignal (int sig) inline inherited
Definition at line 67 of file PthreadBase.h.
References PthreadBase::theThread.
 { return pthread_kill(theThread, sig); }
static int PthreadBase::SendSignal (pthread_t thd, int sig) inline static inherited
Definition at line 70 of file PthreadBase.h.
 { return pthread_kill(thd, sig); }
static int PthreadBase::SetSignalMask (const sigset_t * set, sigset_t * oldSet = 0) inline static inherited
Definition at line 75 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_SETMASK, set, oldSet); }
void Pthread::Start (void)
Definition at line 100 of file PthreadLib.cc.
References PthreadCondition::Broadcast(), cond, created, mutex, started, and state.
Referenced by ~Pthread().
{
     PthreadMutexProtected p(mutex);
     if (state == created) {
         state = started;
         cond.Broadcast();
     }
 }
static void PthreadBase::TestCancel (void) inline static inherited
Definition at line 63 of file PthreadBase.h.
Referenced by PthreadEntryPoint().
 { pthread_testcancel(); }
void PthreadErrorHandler::TrapError (int result) inline protected inherited
Definition at line 48 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
Referenced by PthreadCondition::Broadcast(), PthreadAttr::DetachState(), PthreadBase::Join(), Join(), PthreadMutex::Lock(), PthreadMutex::Poll(), Pthread(), PthreadAttr::PthreadAttr(), PthreadBase::PthreadBase(), PthreadCondition::PthreadCondition(), PthreadConditionAttr::PthreadConditionAttr(), PthreadKey< T >::PthreadKey(), PthreadMutex::PthreadMutex(), PthreadMutexAttr::PthreadMutexAttr(), PthreadReadWriteLock::ReadUnlock(), PthreadAttr::ScheduleScope(), PthreadKey< T >::Set(), PthreadCondition::Signal(), PthreadCondition::TimedWait(), PthreadMutex::Unlock(), PthreadCondition::Wait(), PthreadReadWriteLock::WriteUnlock(), PthreadAttr::~PthreadAttr(), PthreadCondition::~PthreadCondition(), PthreadConditionAttr::~PthreadConditionAttr(), PthreadKey< T >::~PthreadKey(), PthreadMutex::~PthreadMutex(), and PthreadMutexAttr::~PthreadMutexAttr().
 {
     if (err) {
         error = err;
         throw ErrnoException(err);
     }
 }
static int PthreadBase::UnblockSignals (const sigset_t * set, sigset_t * oldSet = 0) inline static inherited
Definition at line 79 of file PthreadBase.h.
                                     { return pthread_sigmask(SIG_UNBLOCK, set, oldSet); }
Member Data Documentation
PthreadCondition Pthread::cond private
Definition at line 85 of file PthreadLib.h.
Referenced by Join(), Pthread(), PthreadCleanup(), PthreadEntryPoint(), Start(), and ~Pthread().
int PthreadErrorHandler::error protected inherited
Definition at line 43 of file PthreadErrorHandler.h.
Referenced by PthreadErrorHandler::Clear(), PthreadErrorHandler::Error(), PthreadErrorHandler::PthreadErrorHandler(), and PthreadErrorHandler::TrapError().
bool Pthread::inJoin private
Definition at line 87 of file PthreadLib.h.
Referenced by Join(), and Pthread().
PthreadMutex Pthread::mutex private
Definition at line 84 of file PthreadLib.h.
Referenced by Done(), Join(), Pthread(), PthreadCleanup(), PthreadEntryPoint(), Running(), Start(), and ~Pthread().
void* Pthread::returnResult private
Definition at line 86 of file PthreadLib.h.
Referenced by Join(), and Pthread().
PthreadState Pthread::state private
Definition at line 90 of file PthreadLib.h.
Referenced by Done(), Join(), Pthread(), PthreadCleanup(), PthreadEntryPoint(), Running(), Start(), and ~Pthread().
pthread_t PthreadBase::theThread protected inherited
Definition at line 126 of file PthreadBase.h.
Referenced by PthreadBase::Cancel(), PthreadBase::Detach(), PthreadBase::Join(), Join(), PthreadBase::Kill(), PthreadBase::operator pthread_t(), PthreadBase::operator pthread_t *(), PthreadBase::operator==(), Pthread(), PthreadBase::PthreadBase(), and PthreadBase::SendSignal().
The documentation for this class was generated from the following files:
include/cpn/threading/PthreadLib.h
lib/threading/PthreadLib.cc