CPN: CPN::Packet Class Reference
CPN::Packet Class Reference
#include <PacketHeader.h>
Public Member Functions
Packet ()
Packet (uint32_t datalen, PacketType_t type)
Packet (PacketType_t type)
Packet (const PacketHeader &ph)
Packet & Init (uint32_t datalen, PacketType_t type)
uint32_t DataLength () const
PacketType_t Type () const
uint32_t QueueSize () const
uint64_t SourceKey () const
uint64_t DestinationKey () const
uint32_t Requested () const
uint32_t MaxThreshold () const
uint32_t Count () const
uint64_t ReadClock () const
uint64_t WriteClock () const
bool Valid () const
Packet & DataLength (uint32_t dl)
Packet & Type (PacketType_t t)
Packet & QueueSize (uint32_t qs)
Packet & SourceKey (uint64_t k)
Packet & DestinationKey (uint64_t k)
Packet & Requested (uint32_t r)
Packet & MaxThreshold (uint32_t mt)
Packet & Count (uint32_t cnt)
Packet & ReadClock (uint64_t c)
Packet & WriteClock (uint64_t c)
Public Attributes
PacketHeader header
Detailed Description
A class to make dealing with a packet easy.
Definition at line 112 of file PacketHeader.h.
Constructor & Destructor Documentation
CPN::Packet::Packet () inline
Definition at line 114 of file PacketHeader.h.
 { memset(&header, 0, sizeof(header)); }
CPN::Packet::Packet (uint32_t datalen, PacketType_t type) inline
Definition at line 115 of file PacketHeader.h.
 { Init(datalen, type); }
CPN::Packet::Packet (PacketType_t type) inline
Definition at line 116 of file PacketHeader.h.
 { Init(0, type); }
CPN::Packet::Packet (const PacketHeader & ph) inline
Definition at line 117 of file PacketHeader.h.
 : header(ph) {}
Member Function Documentation
uint32_t CPN::Packet::Count () const inline
Definition at line 131 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::DequeuePacket(), CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteQueue::SendDequeuePacket(), CPN::PacketEncoder::SendEnqueue(), and CPN::RemoteQueue::SendEnqueuePacket().
 { return header.count; }
Packet& CPN::Packet::Count (uint32_t cnt) inline
Definition at line 143 of file PacketHeader.h.
 { header.count = cnt; return *this; }
uint32_t CPN::Packet::DataLength () const inline
Definition at line 124 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::D4RTagPacket(), CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteQueue::SendD4RTagPacket(), and CPN::PacketEncoder::SendPacket().
 { return header.dataLength; }
Packet& CPN::Packet::DataLength (uint32_t dl) inline
Definition at line 136 of file PacketHeader.h.
 { header.dataLength = dl; return *this; }
uint64_t CPN::Packet::DestinationKey () const inline
Definition at line 128 of file PacketHeader.h.
 { return header.dstkey; }
Packet& CPN::Packet::DestinationKey (uint64_t k) inline
Definition at line 140 of file PacketHeader.h.
 { header.dstkey = k; return *this; }
Packet& CPN::Packet::Init (uint32_t datalen, PacketType_t type) inline
Definition at line 119 of file PacketHeader.h.
References CPN::InitPacket().
{
             InitPacket(&header, datalen, type);
             return *this;
         }
uint32_t CPN::Packet::MaxThreshold () const inline
Definition at line 130 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::GrowPacket(), and CPN::RemoteQueue::SendGrowPacket().
 { return header.maxThresh; }
Packet& CPN::Packet::MaxThreshold (uint32_t mt) inline
Definition at line 142 of file PacketHeader.h.
 { header.maxThresh = mt; return *this; }
uint32_t CPN::Packet::QueueSize () const inline
Definition at line 126 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::GrowPacket(), and CPN::RemoteQueue::SendGrowPacket().
 { return header.queueSize; }
Packet& CPN::Packet::QueueSize (uint32_t qs) inline
Definition at line 138 of file PacketHeader.h.
 { header.queueSize = qs; return *this; }
uint64_t CPN::Packet::ReadClock () const inline
Definition at line 132 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::SetupPacket(), and CPN::RemoteQueue::UpdateClock().
 { return header.readclock; }
Packet& CPN::Packet::ReadClock (uint64_t c) inline
Definition at line 144 of file PacketHeader.h.
 { header.readclock = c; return *this; }
uint32_t CPN::Packet::Requested () const inline
Definition at line 129 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::ReadBlockPacket(), CPN::RemoteQueue::SendReadBlockPacket(), CPN::RemoteQueue::SendWriteBlockPacket(), and CPN::RemoteQueue::WriteBlockPacket().
 { return header.requested; }
Packet& CPN::Packet::Requested (uint32_t r) inline
Definition at line 141 of file PacketHeader.h.
 { header.requested = r; return *this; }
uint64_t CPN::Packet::SourceKey () const inline
Definition at line 127 of file PacketHeader.h.
Referenced by CPN::ConnectionServer::ConnectWriter().
 { return header.srckey; }
Packet& CPN::Packet::SourceKey (uint64_t k) inline
Definition at line 139 of file PacketHeader.h.
 { header.srckey = k; return *this; }
PacketType_t CPN::Packet::Type () const inline
Definition at line 125 of file PacketHeader.h.
Referenced by CPN::PacketHandler::FirePacket(), and CPN::PacketEncoder::SendEnqueue().
 { return static_cast<PacketType_t>(header.dataType); }
Packet& CPN::Packet::Type (PacketType_t t) inline
Definition at line 137 of file PacketHeader.h.
 { header.dataType = t; return *this; }
bool CPN::Packet::Valid () const inline
Definition at line 134 of file PacketHeader.h.
References CPN::ValidPacket().
Referenced by CPN::PacketHandler::FirePacket(), and CPN::PacketDecoder::ReleaseDecoderBytes().
 { return ValidPacket(&header); }
uint64_t CPN::Packet::WriteClock () const inline
Definition at line 133 of file PacketHeader.h.
Referenced by CPN::RemoteQueue::UpdateClock().
 { return header.writeclock; }
Packet& CPN::Packet::WriteClock (uint64_t c) inline
Definition at line 145 of file PacketHeader.h.
 { header.writeclock = c; return *this; }
Member Data Documentation
PacketHeader CPN::Packet::header
Definition at line 148 of file PacketHeader.h.
Referenced by CPN::ConnectionServer::ConnectWriter(), CPN::PacketDecoder::GetDecoderBytes(), CPN::PacketDecoder::ReleaseDecoderBytes(), CPN::PacketEncoder::SendEnqueue(), CPN::RemoteQueue::SendEnqueuePacket(), and CPN::PacketEncoder::SendPacket().
The documentation for this class was generated from the following file:
lib/PacketHeader.h