CPN: CPN::QueueBase Class Reference
CPN::QueueBase Class Reference abstract
The base class for all queues in the CPN library.
#include <QueueBase.h>
Public Member Functions
virtual ~QueueBase ()
const void * GetRawDequeuePtr (unsigned thresh, unsigned chan)
void Dequeue (unsigned count)
bool RawDequeue (void *data, unsigned count, unsigned numChans, unsigned chanStride)
bool RawDequeue (void *data, unsigned count)
void * GetRawEnqueuePtr (unsigned thresh, unsigned chan)
void Enqueue (unsigned count)
void RawEnqueue (const void *data, unsigned count, unsigned numChans, unsigned chanStride)
void RawEnqueue (const void *data, unsigned count)
void Reset ()
void Flush ()
bool Flushed () const
unsigned NumChannels () const
unsigned Count () const
bool Empty () const
unsigned Freespace () const
bool Full () const
unsigned MaxThreshold () const
unsigned QueueLength () const
unsigned EnqueueChannelStride () const
unsigned DequeueChannelStride () const
void Grow (unsigned queueLen, unsigned maxThresh)
Key_t GetWriterKey () const
Key_t GetReaderKey () const
const std::string & GetDatatype () const
void ShutdownReader ()
Called by the QueueReader when no more data will be read.
void ShutdownWriter ()
Called by the QueueWriter when no more data will be written.
void NotifyTerminate ()
Used to tell any waiting threads that the network is terminating.
void Lock () const
void Unlock () const
unsigned ReadRequest ()
For unit tests.
unsigned WriteRequest ()
For unit tests.
bool IsReaderShutdown ()
bool IsWriterShutdown ()
virtual void LogState ()
For debugging ONLY!! Otherwise non deterministic output.
unsigned NumEnqueued () const
unsigned NumDequeued () const
void SetReaderNode (shared_ptr< Node > n)
void SetWriterNode (shared_ptr< Node > n)
void SignalReaderTagChanged ()
void SignalWriterTagChanged ()
Protected Member Functions
QueueBase (KernelBase *k, const SimpleQueueAttr &attr)
virtual void WaitForData ()
virtual bool ReadBlocked ()
void NotifyData ()
virtual void WaitForFreespace ()
virtual bool WriteBlocked ()
void NotifyFreespace ()
virtual void Wait ()
virtual void Signal ()
virtual void Detect ()
virtual const void * InternalGetRawDequeuePtr (unsigned thresh, unsigned chan)=0
virtual void InternalDequeue (unsigned count)=0
virtual void * InternalGetRawEnqueuePtr (unsigned thresh, unsigned chan)=0
virtual void InternalEnqueue (unsigned count)=0
virtual void InternalFlush ()
virtual void InternalReset ()
virtual unsigned UnlockedNumChannels () const =0
virtual unsigned UnlockedCount () const =0
virtual bool UnlockedEmpty () const =0
virtual unsigned UnlockedFreespace () const =0
virtual bool UnlockedFull () const =0
virtual unsigned UnlockedMaxThreshold () const =0
virtual unsigned UnlockedQueueLength () const =0
virtual unsigned UnlockedEnqueueChannelStride () const =0
virtual unsigned UnlockedDequeueChannelStride () const =0
virtual void UnlockedGrow (unsigned queueLen, unsigned maxThresh)=0
virtual void UnlockedShutdownReader ()
virtual void UnlockedShutdownWriter ()
virtual unsigned UnlockedNumEnqueued () const =0
virtual unsigned UnlockedNumDequeued () const =0
void ReadBlock ()
void WriteBlock (unsigned qsize)
virtual void UnlockedSignalReaderTagChanged ()
virtual void UnlockedSignalWriterTagChanged ()
Protected Attributes
const Key_t readerkey
const Key_t writerkey
bool readshutdown
bool writeshutdown
unsigned prepad
unsigned postpad
unsigned readrequest
unsigned writerequest
unsigned enqueuethresh
unsigned dequeuethresh
bool indequeue
bool inenqueue
bool flushed
KernelBase * kernel
bool useD4R
Logger logger
PthreadMutex lock
PthreadCondition cond
std::string datatype
shared_ptr< Node > reader
shared_ptr< Node > writer
bool readtagchanged
bool writetagchanged
bool incomm
Detailed Description
The base class for all queues in the CPN library.
Definition at line 39 of file QueueBase.h.
Constructor & Destructor Documentation
CPN::QueueBase::~QueueBase () virtual
Reimplemented from D4R::QueueBase.
Definition at line 61 of file QueueBase.cc.
 {}
CPN::QueueBase::QueueBase (KernelBase * k, const SimpleQueueAttr & attr) protected
Definition at line 37 of file QueueBase.cc.
References logger, Logger::Name(), readerkey, and writerkey.
         : readerkey(attr.GetReaderKey()),
         writerkey(attr.GetWriterKey()),
         readshutdown(false),
         writeshutdown(false),
         prepad(0),
         postpad(0),
         readrequest(0),
         writerequest(0),
         enqueuethresh(0),
         dequeuethresh(0),
         indequeue(false),
         inenqueue(false),
         flushed(false),
         kernel(k),
         useD4R(kernel->UseD4R()),
         logger(kernel->GetContext().get(), Logger::DEBUG),
         datatype(attr.GetDatatype())
     {
         std::ostringstream oss;
         oss << "Queue(" << writerkey << ", " << readerkey << ")";
         logger.Name(oss.str());
     }
Member Function Documentation
unsigned CPN::QueueBase::Count () const
Returns
the number of bytes in the queue.
Definition at line 205 of file QueueBase.cc.
References UnlockedCount().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedCount();
     }
void CPN::QueueBase::Dequeue (unsigned count)
This function is used to remove elements from the queue. count elements will be removed from the queue when this function is called.
Parameters
count the number of bytes to remove from the queue
Definition at line 92 of file QueueBase.cc.
References dequeuethresh, GetRawDequeuePtr(), indequeue, InternalDequeue(), NotifyFreespace(), readerkey, and readshutdown.
Referenced by RawDequeue().
{
         if (!GetRawDequeuePtr(count, 0)) { throw BrokenQueueException(readerkey); }
         AutoLock<QueueBase> al(*this);
         dequeuethresh = 0;
         indequeue = false;
         if (readshutdown) { throw BrokenQueueException(readerkey); }
         InternalDequeue(count);
         NotifyFreespace();
     }
unsigned CPN::QueueBase::DequeueChannelStride () const
Returns
The current dequeue channel stride. This value is only guaranteed to be consistent inbetween a call to GetDequeuePtr and Dequeue.
Definition at line 240 of file QueueBase.cc.
References UnlockedDequeueChannelStride().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedDequeueChannelStride();
     }
void CPN::QueueBase::Detect () protected virtual
Called by the D4R algorithm when it has detected an artificial deadlock and this queue should be changed.
Implements D4R::QueueBase.
Definition at line 373 of file QueueBase.cc.
References CPN::KernelBase::CalculateGrowSize(), Logger::Debug(), kernel, logger, UnlockedCount(), UnlockedGrow(), UnlockedMaxThreshold(), UnlockedQueueLength(), and writerequest.
{
         unsigned size = kernel->CalculateGrowSize(UnlockedCount(), writerequest);
         logger.Debug("Detect: Grow(%u, %u)", size, writerequest);
         UnlockedGrow(size, writerequest);
         logger.Debug("New size: (%u, %u)", UnlockedQueueLength(), UnlockedMaxThreshold());
     }
bool CPN::QueueBase::Empty () const
Returns
true if the queue is empty
Definition at line 210 of file QueueBase.cc.
References UnlockedEmpty().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedEmpty();
     }
void CPN::QueueBase::Enqueue (unsigned count)
This function is used to release the buffer obtained with GetRawEnqueuePtr. The count specifies the number of entries that we want to be placed in the buffer.
Note
A call to this function without an accompanying call to GetRawEnqueuePtr is undefined.
Parameters
count the number of bytes to be placed in the buffer
Invariant
count <= thresh from GetRawEnqueuePtr
Definition at line 160 of file QueueBase.cc.
References enqueuethresh, inenqueue, InternalEnqueue(), NotifyData(), writerkey, and writeshutdown.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), and RawEnqueue().
{
         AutoLock<QueueBase> al(*this);
         enqueuethresh = 0;
         inenqueue = false;
         if (writeshutdown) { throw BrokenQueueException(writerkey); }
         InternalEnqueue(count);
         NotifyData();
     }
unsigned CPN::QueueBase::EnqueueChannelStride () const
Returns
The current enqueue channel stride. This value is only guaranteed to be consistent inbetween a call to GetEnqueuePtr and Enqueue.
Definition at line 235 of file QueueBase.cc.
References UnlockedEnqueueChannelStride().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedEnqueueChannelStride();
     }
void CPN::QueueBase::Flush ()
Definition at line 186 of file QueueBase.cc.
References InternalFlush().
{
         AutoLock<const QueueBase> al(*this);
         InternalFlush();
     }
bool CPN::QueueBase::Flushed () const
Definition at line 191 of file QueueBase.cc.
References flushed.
{
         AutoLock<const QueueBase> al(*this);
         return flushed;
     }
unsigned CPN::QueueBase::Freespace () const
Returns
the number of bytes we can add to the queue without blocking.
Definition at line 215 of file QueueBase.cc.
References UnlockedFreespace().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedFreespace();
     }
bool CPN::QueueBase::Full () const
Returns
true if the queue is full, false otherwise
Definition at line 220 of file QueueBase.cc.
References UnlockedFull().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedFull();
     }
const std::string& CPN::QueueBase::GetDatatype () const inline
Returns
the datatype name associated with this queue
Definition at line 213 of file QueueBase.h.
 { return datatype; }
const void * CPN::QueueBase::GetRawDequeuePtr (unsigned thresh, unsigned chan)
Get a pointer to a buffer containing elements.
Note
access to the memory locations pointed to by the returned pointer after Dequeue has been called is undefined.
Parameters
thresh the number of bytes to get
chan the channel to use
Returns
A void* to a block of memory containing thresh bytes or 0 if there are not thresh bytes available.
Definition at line 63 of file QueueBase.cc.
References ASSERT, CPN::KernelBase::CheckTerminated(), dequeuethresh, flushed, CPN::KernelBase::GrowQueueMaxThreshold(), indequeue, InternalGetRawDequeuePtr(), kernel, readerkey, readrequest, readshutdown, Signal(), UnlockedGrow(), UnlockedMaxThreshold(), WaitForData(), WriteBlocked(), writerequest, and writeshutdown.
Referenced by Dequeue(), and RawDequeue().
{
         kernel->CheckTerminated();
         AutoLock<QueueBase> al(*this);
         if (indequeue) { ASSERT(dequeuethresh >= thresh); }
         else { dequeuethresh = thresh; }
         while (true) {
             const void *ptr = InternalGetRawDequeuePtr(thresh, chan);
             if (ptr ||
                     (writeshutdown && !(thresh > UnlockedMaxThreshold() && kernel->GrowQueueMaxThreshold()))
                     || flushed) {
                 if (ptr) { indequeue = true; }
                 return ptr;
             }
             if (readshutdown) { throw BrokenQueueException(readerkey); }
             if (thresh > UnlockedMaxThreshold() && kernel->GrowQueueMaxThreshold()) {
                 //printf("Grow(%u, %u)\n", 2*thresh, thresh);
                 UnlockedGrow(2*thresh, thresh);
                 Signal();
             } else if (WriteBlocked() && kernel->GrowQueueMaxThreshold()) {
                 UnlockedGrow(writerequest + thresh, thresh);
                 Signal();
             } else {
                 readrequest = thresh;
                 WaitForData();
                 readrequest = 0;
             }
         }
     }
void * CPN::QueueBase::GetRawEnqueuePtr (unsigned thresh, unsigned chan)
Return a pointer to a buffer of memory that contains thresh entries that we can write into.
Note
A call to this function without an accompanying call to Enqueue is undefined.
An access to the memory locations defined by the return value is undefined after a call to Enqueue.
Parameters
thresh the number bytes we need in the returned buffer.
chan the channel to use
Returns
void* to the memory buffer, 0 if not enough space available
Definition at line 121 of file QueueBase.cc.
References ASSERT, CPN::KernelBase::CheckTerminated(), enqueuethresh, flushed, CPN::KernelBase::GrowQueueMaxThreshold(), inenqueue, InternalGetRawEnqueuePtr(), kernel, ReadBlocked(), readrequest, readshutdown, Signal(), UnlockedGrow(), UnlockedMaxThreshold(), useD4R, Wait(), WaitForFreespace(), D4R::QueueBase::WriteBlock(), writerequest, writerkey, and writeshutdown.
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), and RawEnqueue().
{
         kernel->CheckTerminated();
         AutoLock<QueueBase> al(*this);
         // Only the enqueuer may call flush and reset will clear all state as if we
         // had not done anything yet, so block here
         while (flushed) {
             if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
             if (useD4R) {
                 WriteBlock(-1);
             } else {
                 Wait();
             }
         }
         if (inenqueue) { ASSERT(enqueuethresh >= thresh); }
         else { enqueuethresh = thresh; }
         bool grown = false;
         while (true) {
             void *ptr = InternalGetRawEnqueuePtr(thresh, chan);
             if (ptr) {
                 inenqueue = true;
                 return ptr;
             }
             if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
             if (thresh > UnlockedMaxThreshold() && kernel->GrowQueueMaxThreshold()) {
                 //printf("Grow(%u, %u)\n", 2*thresh, thresh);
                 UnlockedGrow(2*thresh, thresh);
                 Signal();
             } else if (!grown && ReadBlocked() && kernel->GrowQueueMaxThreshold()) {
                 UnlockedGrow(readrequest + thresh, thresh);
                 Signal();
                 grown = true;
             } else {
                 writerequest = thresh;
                 WaitForFreespace();
                 writerequest = 0;
             }
         }
     }
Key_t CPN::QueueBase::GetReaderKey () const inline
Returns
the reader key associated with this queue
Definition at line 211 of file QueueBase.h.
 { return readerkey; }
Key_t CPN::QueueBase::GetWriterKey () const inline
Returns
the writer key associated with this queue
Definition at line 209 of file QueueBase.h.
 { return writerkey; }
void CPN::QueueBase::Grow (unsigned queueLen, unsigned maxThresh)
Ensure that this queue has at least queueLen bytes of space and can support at least maxThresh as the maxThreshold the new queue length will be max(queueLen, QueueLength()) and the new max threshold will be max(maxThresh, MaxThreshold())
Note
that the caller must guarantee that both an enqueue and dequeue are not both outstanding. Otherwise this will fail.
Parameters
queueLen the next queue length
maxThresh the next max threshold
Definition at line 245 of file QueueBase.cc.
References UnlockedGrow().
{
         AutoLock<QueueBase> al(*this);
         UnlockedGrow(queueLen, maxThresh);
     }
virtual void CPN::QueueBase::InternalDequeue (unsigned count) protected pure virtual
Implemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Referenced by Dequeue().
virtual void CPN::QueueBase::InternalEnqueue (unsigned count) protected pure virtual
Implemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Referenced by Enqueue(), InternalFlush(), and InternalReset().
void CPN::QueueBase::InternalFlush () protected virtual
Reimplemented in CPN::RemoteQueue.
Definition at line 265 of file QueueBase.cc.
References PthreadCondition::Broadcast(), cond, flushed, InternalEnqueue(), InternalGetRawEnqueuePtr(), postpad, readshutdown, UnlockedEnqueueChannelStride(), UnlockedNumChannels(), WaitForFreespace(), writerequest, writerkey, and writeshutdown.
Referenced by Flush(), and CPN::RemoteQueue::InternalFlush().
{
         if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
         if (postpad > 0) {
             while (true) {
                 void *ptr = InternalGetRawEnqueuePtr(postpad, 0);
                 if (ptr) {
                     unsigned num_chans = UnlockedNumChannels();
                     unsigned chanstride = UnlockedEnqueueChannelStride();
                     for (unsigned chan = 0; chan < num_chans; ++chan) {
                         memset((char*)ptr + chanstride*chan, 0, postpad);
                     }
                     InternalEnqueue(postpad);
                 } else {
                     if (readshutdown || writeshutdown) { throw BrokenQueueException(writerkey); }
                     writerequest = postpad;
                     WaitForFreespace();
                     writerequest = 0;
                 }
             }
         }
         flushed = true;
         cond.Broadcast();
     }
virtual const void* CPN::QueueBase::InternalGetRawDequeuePtr (unsigned thresh, unsigned chan) protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by GetRawDequeuePtr().
virtual void* CPN::QueueBase::InternalGetRawEnqueuePtr (unsigned thresh, unsigned chan) protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by GetRawEnqueuePtr(), InternalFlush(), and InternalReset().
void CPN::QueueBase::InternalReset () protected virtual
Reimplemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Definition at line 289 of file QueueBase.cc.
References ASSERT, PthreadCondition::Broadcast(), cond, dequeuethresh, enqueuethresh, flushed, indequeue, inenqueue, InternalEnqueue(), InternalGetRawEnqueuePtr(), prepad, readrequest, UnlockedEnqueueChannelStride(), UnlockedNumChannels(), and writerequest.
Referenced by CPN::ThresholdQueue::InternalReset(), and Reset().
{
         ASSERT(flushed);
         readrequest = 0;
         writerequest = 0;
         enqueuethresh = 0;
         dequeuethresh = 0;
         indequeue = false;
         inenqueue = false;
         flushed = false;
         if (prepad > 0) {
             void *ptr = InternalGetRawEnqueuePtr(prepad, 0);
             ASSERT(ptr);
             unsigned num_chans = UnlockedNumChannels();
             unsigned chanstride = UnlockedEnqueueChannelStride();
             for (unsigned chan = 0; chan < num_chans; ++chan) {
                 memset((char*)ptr + chanstride*chan, 0, prepad);
             }
             InternalEnqueue(prepad);
         }
         cond.Broadcast();
     }
bool CPN::QueueBase::IsReaderShutdown ()
Definition at line 390 of file QueueBase.cc.
References readshutdown.
{
         AutoLock<QueueBase> al(*this);
         return readshutdown;
     }
bool CPN::QueueBase::IsWriterShutdown ()
Definition at line 395 of file QueueBase.cc.
References writeshutdown.
{
         AutoLock<QueueBase> al(*this);
         return writeshutdown;
     }
void CPN::QueueBase::Lock () const inline virtual
These functions are to access the lock for the queue.
Implements D4R::QueueBase.
Definition at line 221 of file QueueBase.h.
References lock, and PthreadMutex::Lock().
 { lock.Lock(); }
void CPN::QueueBase::LogState () virtual
For debugging ONLY!! Otherwise non deterministic output.
Reimplemented in CPN::RemoteQueue.
Definition at line 400 of file QueueBase.cc.
References dequeuethresh, enqueuethresh, Logger::Error(), flushed, indequeue, inenqueue, logger, readerkey, readrequest, readshutdown, UnlockedCount(), UnlockedFreespace(), UnlockedMaxThreshold(), UnlockedNumDequeued(), UnlockedNumEnqueued(), UnlockedQueueLength(), writerequest, writerkey, and writeshutdown.
Referenced by CPN::RemoteQueue::LogState().
{
         logger.Error("Printing state (w:%llu r:%llu)", readerkey, writerkey);
         logger.Error("size: %u, maxthresh: %u count: %u free: %u, flushed: %d",
                 UnlockedQueueLength(), UnlockedMaxThreshold(), UnlockedCount(), UnlockedFreespace(),
                 (int)flushed);
         logger.Error("readrequest: %u, writerequest: %u numenqueued: %u, numdequeued: %u",
                 readrequest, writerequest, UnlockedNumEnqueued(), UnlockedNumDequeued());
         if (indequeue) {
             logger.Error("Indequeue (thresh: %u)", dequeuethresh);
         }
         if (inenqueue) {
             logger.Error("Inenqueue (thresh: %u)", enqueuethresh);
         }
         if (readshutdown) {
             logger.Error("Reader shutdown");
         }
         if (writeshutdown) {
             logger.Error("Writer shutdown");
         }
     }
unsigned CPN::QueueBase::MaxThreshold () const
Returns
the maximum threshold this queue supports in bytes
Definition at line 225 of file QueueBase.cc.
References UnlockedMaxThreshold().
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), and CPN::ThresholdQueue::UnlockedGrow().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedMaxThreshold();
     }
void CPN::QueueBase::NotifyData () protected
Definition at line 341 of file QueueBase.cc.
References PthreadCondition::Broadcast(), cond, readrequest, and UnlockedCount().
Referenced by Enqueue(), and CPN::RemoteQueue::EnqueuePacket().
{
         if (UnlockedCount() >= readrequest) {
             cond.Broadcast();
         }
     }
void CPN::QueueBase::NotifyFreespace () protected
Definition at line 362 of file QueueBase.cc.
References PthreadCondition::Broadcast(), cond, UnlockedFreespace(), and writerequest.
Referenced by Dequeue(), and CPN::RemoteQueue::SendEnqueuePacket().
{
         if (UnlockedFreespace() >= writerequest) {
             cond.Broadcast();
         }
     }
void CPN::QueueBase::NotifyTerminate ()
Used to tell any waiting threads that the network is terminating.
Definition at line 368 of file QueueBase.cc.
References PthreadCondition::Broadcast(), and cond.
{
         AutoLock<QueueBase> al(*this);
         cond.Broadcast();
     }
unsigned CPN::QueueBase::NumChannels () const
Returns
the number of channels supported by this queue.
Definition at line 200 of file QueueBase.cc.
References UnlockedNumChannels().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedNumChannels();
     }
unsigned CPN::QueueBase::NumDequeued () const
Definition at line 321 of file QueueBase.cc.
References UnlockedNumDequeued().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedNumDequeued();
     }
unsigned CPN::QueueBase::NumEnqueued () const
Definition at line 316 of file QueueBase.cc.
References UnlockedNumEnqueued().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedNumEnqueued();
     }
unsigned CPN::QueueBase::QueueLength () const
Returns
the maximum number of bytes that can be put in this queue.
Definition at line 230 of file QueueBase.cc.
References UnlockedQueueLength().
Referenced by CPN::ThresholdQueue::TQImpl::Grow(), CPN::RemoteQueue::GrowPacket(), CPN::ThresholdQueue::UnlockedGrow(), and CPN::RemoteQueue::UnlockedGrow().
{
         AutoLock<const QueueBase> al(*this);
         return UnlockedQueueLength();
     }
bool CPN::QueueBase::RawDequeue (void * data, unsigned count, unsigned numChans, unsigned chanStride)
Dequeue data from the queue directly into the memory pointed to by data. This function shall be equivalent to a call to GetRawDequeuePtr then a memcpy and then a call to Dequeue.
Parameters
data poiner to memory to dequeue to
count the number of bytes to copy into data
numChans the number of channels to write to
chanStride the distance in bytes between the beginning of the channels in data.
Returns
true on success false on failure
Definition at line 102 of file QueueBase.cc.
References ASSERT, Dequeue(), and GetRawDequeuePtr().
Referenced by RawDequeue().
{
         const void *src = GetRawDequeuePtr(count, 0);
         char *dest = (char*)data;
         if (!src) { return false; }
         memcpy(dest, src, count);
         for (unsigned chan = 1; chan < numChans; ++chan) {
             src = GetRawDequeuePtr(count, chan);
             ASSERT(src);
             dest += chanStride;
             memcpy(dest, src, count);
         }
         Dequeue(count);
         return true;
     }
bool CPN::QueueBase::RawDequeue (void * data, unsigned count)
A version of RawDequeue to use when there is only 1 channel.
Parameters
data the data to enqueue
count the number of bytes to enqueue
Returns
true on success false if we have reached the end of the queue
Definition at line 117 of file QueueBase.cc.
References RawDequeue().
{
         return RawDequeue(data, count, 1, 0);
     }
void CPN::QueueBase::RawEnqueue (const void * data, unsigned count, unsigned numChans, unsigned chanStride)
This function shall be equivalent to a call to GetRqwEnqueuePtr and a memcpy and then a call to Enqueue
The underlying implementatin may implement ether the GetRawEnqueuePtr and Enqueue or RawEnqueue and then implement the other in terms of the one implemented.
Parameters
data pointer to the memory to enqueue
count the number of bytes to enqueue
numChans the number of channels to write to
chanStride the distance in bytes between the beginning of the channels in data.
Definition at line 169 of file QueueBase.cc.
References Enqueue(), and GetRawEnqueuePtr().
Referenced by RawEnqueue().
{
         void *dest = GetRawEnqueuePtr(count, 0);
         const char *src = (char*)data;
         memcpy(dest, src, count);
         for (unsigned chan = 1; chan < numChans; ++chan) {
             dest = GetRawEnqueuePtr(count, chan);
             src += chanStride;
             memcpy(dest, src, count);
         }
         Enqueue(count);
     }
void CPN::QueueBase::RawEnqueue (const void * data, unsigned count)
A version of RawEnqueue to use when there is only 1 channel.
Parameters
data pointer to the memory to enqueue
count the number of bytes to enqueue
Definition at line 196 of file QueueBase.cc.
References RawEnqueue().
{
         return RawEnqueue(data, count, 1, 0);
     }
void D4R::QueueBase::ReadBlock () protected inherited
reader ===> writer ReadBlock requires that you already hold the lock and if it is reentrant then a single unlock will release the lock.
Exceptions
D4R::DeadlockException
Definition at line 71 of file D4RQueue.cc.
References D4R::QueueBase::incomm, D4R::QueueBase::ReadBlocked(), D4R::QueueBase::reader, D4R::QueueBase::Signal(), D4R::QueueBase::Wait(), D4R::QueueBase::writer, and D4R::QueueBase::writetagchanged.
Referenced by WaitForData().
{
         if (!writer) {
             while (ReadBlocked() && !writer) {
                 Wait();
             }
         }
         if (!ReadBlocked()) { return; }
         writetagchanged = false;
         try {
             while (incomm) { Wait(); }
             ScopeSetter<bool> ss(incomm, true);
             AutoUnlock<QueueBase> au(*this);
             reader->Block(writer->GetPublicTag(), -1);
         } catch (...) { Signal(); throw; }
         Signal();
         while (ReadBlocked()) {
             if (writetagchanged) {
                 writetagchanged = false;
                 bool detect;
                 try {
                     while (incomm) { Wait(); }
                     ScopeSetter<bool> ss(incomm, true);
                     AutoUnlock<QueueBase> au(*this);
                     detect = reader->Transmit(writer->GetPublicTag());
                 } catch (...) { Signal(); throw; }
                 Signal();
                 if (detect) {
                     throw DeadlockException("True deadlock detected");
                 }
             } else {
                 Wait();
             }
         }
     }
bool CPN::QueueBase::ReadBlocked () protected virtual
Returns
true if we are blocked
Implements D4R::QueueBase.
Definition at line 336 of file QueueBase.cc.
References CPN::KernelBase::CheckTerminated(), flushed, kernel, readrequest, readshutdown, UnlockedCount(), and writeshutdown.
Referenced by GetRawEnqueuePtr(), CPN::RemoteQueue::WaitForData(), and WaitForData().
{
         kernel->CheckTerminated();
         return UnlockedCount() < readrequest && !(readshutdown || writeshutdown) && !flushed;
     }
unsigned CPN::QueueBase::ReadRequest ()
For unit tests.
Definition at line 380 of file QueueBase.cc.
References readrequest.
{
         AutoLock<QueueBase> al(*this);
         return readrequest;
     }
void CPN::QueueBase::Reset ()
Definition at line 181 of file QueueBase.cc.
References InternalReset().
{
         AutoLock<const QueueBase> al(*this);
         InternalReset();
     }
void D4R::QueueBase::SetReaderNode (shared_ptr< Node > n) inherited
Set the node which is reading from this queue
Parameters
n the node
Definition at line 59 of file D4RQueue.cc.
References D4R::QueueBase::reader, and D4R::QueueBase::Signal().
Referenced by CPN::RemoteQueue::RemoteQueue().
{
         AutoLock<QueueBase> al(*this);
         reader = n;
         Signal();
     }
void D4R::QueueBase::SetWriterNode (shared_ptr< Node > n) inherited
Set the node which is writing to this queue.
Parameters
n the node
Definition at line 65 of file D4RQueue.cc.
References D4R::QueueBase::Signal(), and D4R::QueueBase::writer.
Referenced by CPN::RemoteQueue::RemoteQueue().
{
         AutoLock<QueueBase> al(*this);
         writer = n;
         Signal();
     }
void CPN::QueueBase::ShutdownReader ()
Called by the QueueReader when no more data will be read.
Definition at line 250 of file QueueBase.cc.
References UnlockedShutdownReader().
Referenced by CPN::RemoteQueue::FileThreadEntryPoint().
{
         AutoLock<QueueBase> al(*this);
         UnlockedShutdownReader();
     }
void CPN::QueueBase::ShutdownWriter ()
Called by the QueueWriter when no more data will be written.
Definition at line 260 of file QueueBase.cc.
References UnlockedShutdownWriter().
Referenced by CPN::RemoteQueue::FileThreadEntryPoint().
{
         AutoLock<QueueBase> al(*this);
         UnlockedShutdownWriter();
     }
virtual void CPN::QueueBase::Signal () inline protected virtual
Signal that Wait should return
Implements D4R::QueueBase.
Reimplemented in CPN::RemoteQueue.
Definition at line 247 of file QueueBase.h.
Referenced by GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::RemoteQueue::Signal(), UnlockedShutdownReader(), and UnlockedShutdownWriter().
 { cond.Broadcast(); }
void D4R::QueueBase::SignalReaderTagChanged () inherited
These functions are called by the D4R::Node when thier tag changes.
Definition at line 139 of file D4RQueue.cc.
References D4R::QueueBase::UnlockedSignalReaderTagChanged().
{
         AutoLock<QueueBase> al(*this);
         UnlockedSignalReaderTagChanged();
     }
void D4R::QueueBase::SignalWriterTagChanged () inherited
Definition at line 150 of file D4RQueue.cc.
References D4R::QueueBase::UnlockedSignalWriterTagChanged().
{
         AutoLock<QueueBase> al(*this);
         UnlockedSignalWriterTagChanged();
     }
void CPN::QueueBase::Unlock (void) const inline virtual
Implements D4R::QueueBase.
Definition at line 222 of file QueueBase.h.
References lock, and PthreadMutex::Unlock().
 { lock.Unlock(); }
virtual unsigned CPN::QueueBase::UnlockedCount () const protected pure virtual
Implemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Referenced by Count(), Detect(), LogState(), NotifyData(), and ReadBlocked().
virtual unsigned CPN::QueueBase::UnlockedDequeueChannelStride () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by DequeueChannelStride().
virtual bool CPN::QueueBase::UnlockedEmpty () const protected pure virtual
Implemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Referenced by Empty().
virtual unsigned CPN::QueueBase::UnlockedEnqueueChannelStride () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by EnqueueChannelStride(), InternalFlush(), and InternalReset().
virtual unsigned CPN::QueueBase::UnlockedFreespace () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by Freespace(), LogState(), NotifyFreespace(), and WriteBlocked().
virtual bool CPN::QueueBase::UnlockedFull () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by Full().
virtual void CPN::QueueBase::UnlockedGrow (unsigned queueLen, unsigned maxThresh) protected pure virtual
Implemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Referenced by Detect(), GetRawDequeuePtr(), GetRawEnqueuePtr(), and Grow().
virtual unsigned CPN::QueueBase::UnlockedMaxThreshold () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by Detect(), GetRawDequeuePtr(), GetRawEnqueuePtr(), LogState(), and MaxThreshold().
virtual unsigned CPN::QueueBase::UnlockedNumChannels () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by InternalFlush(), InternalReset(), and NumChannels().
virtual unsigned CPN::QueueBase::UnlockedNumDequeued () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by LogState(), and NumDequeued().
virtual unsigned CPN::QueueBase::UnlockedNumEnqueued () const protected pure virtual
Implemented in CPN::ThresholdQueue.
Referenced by LogState(), and NumEnqueued().
virtual unsigned CPN::QueueBase::UnlockedQueueLength () const protected pure virtual
Implemented in CPN::RemoteQueue, and CPN::ThresholdQueue.
Referenced by Detect(), LogState(), QueueLength(), and WaitForFreespace().
void CPN::QueueBase::UnlockedShutdownReader () protected virtual
Definition at line 255 of file QueueBase.cc.
References readshutdown, and Signal().
Referenced by CPN::RemoteQueue::EndOfReadPacket(), CPN::RemoteQueue::InternalCheckStatus(), and ShutdownReader().
{
         readshutdown = true;
         Signal();
     }
void CPN::QueueBase::UnlockedShutdownWriter () protected virtual
Definition at line 311 of file QueueBase.cc.
References Signal(), and writeshutdown.
Referenced by CPN::RemoteQueue::EndOfWritePacket(), CPN::RemoteQueue::InternalCheckStatus(), and ShutdownWriter().
{
         writeshutdown = true;
         Signal();
     }
void D4R::QueueBase::UnlockedSignalReaderTagChanged () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 144 of file D4RQueue.cc.
References DEBUG, D4R::QueueBase::reader, D4R::QueueBase::readtagchanged, D4R::QueueBase::Signal(), and D4R::QueueBase::writer.
Referenced by CPN::RemoteQueue::D4RTagPacket(), D4R::QueueBase::SignalReaderTagChanged(), and CPN::RemoteQueue::UnlockedSignalReaderTagChanged().
{
         DEBUG("%s: (%llu -> %llu)\n", __PRETTY_FUNCTION__, (writer ? writer->GetPrivateTag().Key() : 0), (reader ? reader->GetPrivateTag().Key() : 0));
         readtagchanged = true;
         Signal();
     }
void D4R::QueueBase::UnlockedSignalWriterTagChanged () protected virtual inherited
Reimplemented in CPN::RemoteQueue.
Definition at line 155 of file D4RQueue.cc.
References DEBUG, D4R::QueueBase::reader, D4R::QueueBase::Signal(), D4R::QueueBase::writer, and D4R::QueueBase::writetagchanged.
Referenced by CPN::RemoteQueue::D4RTagPacket(), D4R::QueueBase::SignalWriterTagChanged(), and CPN::RemoteQueue::UnlockedSignalWriterTagChanged().
{
         DEBUG("%s: (%llu -> %llu)\n", __PRETTY_FUNCTION__, (writer ? writer->GetPrivateTag().Key() : 0), (reader ? reader->GetPrivateTag().Key() : 0));
         writetagchanged = true;
         Signal();
     }
virtual void CPN::QueueBase::Wait () inline protected virtual
Wait untill Signal is called. Must be holding the lock to call.
Implements D4R::QueueBase.
Definition at line 246 of file QueueBase.h.
References lock.
Referenced by CPN::RemoteQueue::ActionThreadEntryPoint(), GetRawEnqueuePtr(), CPN::RemoteQueue::WaitForData(), and CPN::RemoteQueue::WaitForFreespace().
 { cond.Wait(lock); }
void CPN::QueueBase::WaitForData () protected virtual
Reimplemented in CPN::RemoteQueue.
Definition at line 326 of file QueueBase.cc.
References cond, lock, D4R::QueueBase::ReadBlock(), ReadBlocked(), useD4R, and PthreadCondition::Wait().
Referenced by GetRawDequeuePtr(), and CPN::RemoteQueue::WaitForData().
{
         if (useD4R) {
             ReadBlock();
         } else {
             while (ReadBlocked()) {
                 cond.Wait(lock);
             }
         }
     }
void CPN::QueueBase::WaitForFreespace () protected virtual
Reimplemented in CPN::RemoteQueue.
Definition at line 347 of file QueueBase.cc.
References cond, lock, UnlockedQueueLength(), useD4R, PthreadCondition::Wait(), D4R::QueueBase::WriteBlock(), and WriteBlocked().
Referenced by GetRawEnqueuePtr(), InternalFlush(), and CPN::RemoteQueue::WaitForFreespace().
{
         if (useD4R) {
             WriteBlock(UnlockedQueueLength());
         } else {
             while (WriteBlocked()) {
                 cond.Wait(lock);
             }
         }
     }
void D4R::QueueBase::WriteBlock (unsigned qsize) protected inherited
writer ===> reader WriteBlock requires that you already hold the lock and if it is reentrant then a single unlock will release the lock.
Definition at line 106 of file D4RQueue.cc.
References D4R::QueueBase::Detect(), D4R::QueueBase::incomm, D4R::QueueBase::reader, D4R::QueueBase::readtagchanged, D4R::QueueBase::Signal(), D4R::QueueBase::Wait(), D4R::QueueBase::WriteBlocked(), and D4R::QueueBase::writer.
Referenced by GetRawEnqueuePtr(), and WaitForFreespace().
{
         if (!reader) {
             while (WriteBlocked() && !reader) {
                 Wait();
             }
         }
         if (!WriteBlocked()) { return; }
         readtagchanged = false;
         try {
             while (incomm) { Wait(); }
             ScopeSetter<bool> ss(incomm, true);
             AutoUnlock<QueueBase> au(*this);
             writer->Block(reader->GetPublicTag(), qsize);
         } catch (...) { Signal(); throw; }
         Signal();
         while (WriteBlocked()) {
             if (readtagchanged) {
                 readtagchanged = false;
                 bool detect;
                 try {
                     while (incomm) { Wait(); }
                     ScopeSetter<bool> ss(incomm, true);
                     AutoUnlock<QueueBase> au(*this);
                     detect = writer->Transmit(reader->GetPublicTag());
                 } catch (...) { Signal(); throw; }
                 Signal();
                 if (detect) { Detect(); }
             } else {
                 Wait();
             }
         }
     }
bool CPN::QueueBase::WriteBlocked () protected virtual
Returns
true if we are blocked.
Implements D4R::QueueBase.
Definition at line 357 of file QueueBase.cc.
References CPN::KernelBase::CheckTerminated(), flushed, kernel, readshutdown, UnlockedFreespace(), writerequest, and writeshutdown.
Referenced by GetRawDequeuePtr(), CPN::RemoteQueue::WaitForFreespace(), and WaitForFreespace().
{
         kernel->CheckTerminated();
         return (UnlockedFreespace() < writerequest || flushed) && !(readshutdown || writeshutdown);
     }
unsigned CPN::QueueBase::WriteRequest ()
For unit tests.
Definition at line 385 of file QueueBase.cc.
References writerequest.
{
         AutoLock<QueueBase> al(*this);
         return writerequest;
     }
Member Data Documentation
PthreadCondition CPN::QueueBase::cond protected
Definition at line 290 of file QueueBase.h.
Referenced by InternalFlush(), InternalReset(), NotifyData(), NotifyFreespace(), NotifyTerminate(), WaitForData(), and WaitForFreespace().
std::string CPN::QueueBase::datatype protected
Definition at line 291 of file QueueBase.h.
unsigned CPN::QueueBase::dequeuethresh protected
Definition at line 282 of file QueueBase.h.
Referenced by Dequeue(), GetRawDequeuePtr(), InternalReset(), LogState(), and CPN::RemoteQueue::ResetPacket().
unsigned CPN::QueueBase::enqueuethresh protected
Definition at line 281 of file QueueBase.h.
Referenced by Enqueue(), GetRawEnqueuePtr(), InternalReset(), LogState(), and CPN::RemoteQueue::ResetPacket().
bool CPN::QueueBase::flushed protected
Definition at line 285 of file QueueBase.h.
Referenced by Flushed(), CPN::RemoteQueue::FlushPacket(), GetRawDequeuePtr(), GetRawEnqueuePtr(), InternalFlush(), InternalReset(), LogState(), ReadBlocked(), CPN::RemoteQueue::ResetPacket(), and WriteBlocked().
bool D4R::QueueBase::incomm protected inherited
Definition at line 126 of file D4RQueue.h.
Referenced by D4R::QueueBase::ReadBlock(), and D4R::QueueBase::WriteBlock().
bool CPN::QueueBase::indequeue protected
Definition at line 283 of file QueueBase.h.
Referenced by Dequeue(), GetRawDequeuePtr(), CPN::ThresholdQueue::InternalGetRawDequeuePtr(), InternalReset(), LogState(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendEnqueuePacket(), and CPN::ThresholdQueue::UnlockedGrow().
bool CPN::QueueBase::inenqueue protected
Definition at line 284 of file QueueBase.h.
Referenced by Enqueue(), CPN::RemoteQueue::EnqueuePacket(), GetRawEnqueuePtr(), CPN::ThresholdQueue::InternalGetRawEnqueuePtr(), InternalReset(), LogState(), CPN::RemoteQueue::ResetPacket(), and CPN::ThresholdQueue::UnlockedGrow().
KernelBase* CPN::QueueBase::kernel protected
Definition at line 286 of file QueueBase.h.
Referenced by Detect(), CPN::RemoteQueue::FileThreadEntryPoint(), GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::RemoteQueue::InternalCheckStatus(), ReadBlocked(), and WriteBlocked().
PthreadMutex CPN::QueueBase::lock mutable protected
Definition at line 289 of file QueueBase.h.
Referenced by CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::UnlockedGrow(), WaitForData(), and WaitForFreespace().
Logger CPN::QueueBase::logger protected
Definition at line 288 of file QueueBase.h.
Referenced by CPN::RemoteQueue::D4RTagPacket(), CPN::RemoteQueue::DequeuePacket(), Detect(), CPN::RemoteQueue::EndOfReadPacket(), CPN::RemoteQueue::EndOfWritePacket(), CPN::RemoteQueue::EnqueuePacket(), CPN::RemoteQueue::FileThreadEntryPoint(), CPN::RemoteQueue::FlushPacket(), CPN::RemoteQueue::GrowPacket(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), CPN::RemoteQueue::InternalDequeue(), CPN::RemoteQueue::InternalEnqueue(), CPN::RemoteQueue::LogState(), LogState(), QueueBase(), CPN::RemoteQueue::Read(), CPN::RemoteQueue::ReadBlockPacket(), CPN::RemoteQueue::RemoteQueue(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendD4RTagPacket(), CPN::RemoteQueue::SendDequeuePacket(), CPN::RemoteQueue::SendEndOfReadPacket(), CPN::RemoteQueue::SendEndOfWritePacket(), CPN::RemoteQueue::SendEnqueuePacket(), CPN::RemoteQueue::SendFlushPacket(), CPN::RemoteQueue::SendGrowPacket(), CPN::RemoteQueue::SendReadBlockPacket(), CPN::RemoteQueue::SendResetPacket(), CPN::RemoteQueue::SendWriteBlockPacket(), CPN::RemoteQueue::UnlockedGrow(), CPN::RemoteQueue::UnlockedShutdown(), CPN::RemoteQueue::UnlockedSignalReaderTagChanged(), CPN::RemoteQueue::UnlockedSignalWriterTagChanged(), CPN::RemoteQueue::WaitForData(), CPN::RemoteQueue::WaitForFreespace(), CPN::RemoteQueue::WriteBlockPacket(), and CPN::RemoteQueue::~RemoteQueue().
unsigned CPN::QueueBase::postpad protected
Definition at line 278 of file QueueBase.h.
Referenced by InternalFlush().
unsigned CPN::QueueBase::prepad protected
Definition at line 277 of file QueueBase.h.
Referenced by InternalReset().
shared_ptr<Node> D4R::QueueBase::reader protected inherited
Definition at line 122 of file D4RQueue.h.
Referenced by CPN::RemoteQueue::InternalCheckStatus(), D4R::QueueBase::ReadBlock(), CPN::RemoteQueue::SendD4RTagPacket(), D4R::QueueBase::SetReaderNode(), D4R::QueueBase::UnlockedSignalReaderTagChanged(), D4R::QueueBase::UnlockedSignalWriterTagChanged(), and D4R::QueueBase::WriteBlock().
const Key_t CPN::QueueBase::readerkey protected
Definition at line 273 of file QueueBase.h.
Referenced by Dequeue(), CPN::RemoteQueue::GetKey(), GetRawDequeuePtr(), LogState(), QueueBase(), and CPN::RemoteQueue::RemoteQueue().
unsigned CPN::QueueBase::readrequest protected
Definition at line 279 of file QueueBase.h.
Referenced by CPN::RemoteQueue::DequeuePacket(), GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::InternalCheckStatus(), InternalReset(), LogState(), NotifyData(), ReadBlocked(), CPN::RemoteQueue::ReadBlockPacket(), ReadRequest(), CPN::RemoteQueue::ResetPacket(), and CPN::RemoteQueue::SendReadBlockPacket().
bool CPN::QueueBase::readshutdown protected
Definition at line 275 of file QueueBase.h.
Referenced by Dequeue(), CPN::RemoteQueue::DequeuePacket(), CPN::RemoteQueue::EndOfReadPacket(), GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), InternalFlush(), IsReaderShutdown(), LogState(), ReadBlocked(), CPN::RemoteQueue::ReadBlockPacket(), UnlockedShutdownReader(), and WriteBlocked().
bool D4R::QueueBase::readtagchanged protected inherited
Definition at line 124 of file D4RQueue.h.
Referenced by D4R::QueueBase::UnlockedSignalReaderTagChanged(), and D4R::QueueBase::WriteBlock().
bool CPN::QueueBase::useD4R protected
Definition at line 287 of file QueueBase.h.
Referenced by GetRawEnqueuePtr(), CPN::RemoteQueue::ReadBlockPacket(), WaitForData(), WaitForFreespace(), and CPN::RemoteQueue::WriteBlockPacket().
shared_ptr<Node> D4R::QueueBase::writer protected inherited
Definition at line 123 of file D4RQueue.h.
Referenced by CPN::RemoteQueue::InternalCheckStatus(), D4R::QueueBase::ReadBlock(), CPN::RemoteQueue::SendD4RTagPacket(), D4R::QueueBase::SetWriterNode(), D4R::QueueBase::UnlockedSignalReaderTagChanged(), D4R::QueueBase::UnlockedSignalWriterTagChanged(), and D4R::QueueBase::WriteBlock().
unsigned CPN::QueueBase::writerequest protected
Definition at line 280 of file QueueBase.h.
Referenced by Detect(), CPN::RemoteQueue::EnqueuePacket(), GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::InternalCheckStatus(), InternalFlush(), InternalReset(), LogState(), NotifyFreespace(), CPN::RemoteQueue::ResetPacket(), CPN::RemoteQueue::SendWriteBlockPacket(), WriteBlocked(), CPN::RemoteQueue::WriteBlockPacket(), and WriteRequest().
const Key_t CPN::QueueBase::writerkey protected
Definition at line 274 of file QueueBase.h.
Referenced by Enqueue(), CPN::RemoteQueue::GetKey(), GetRawEnqueuePtr(), InternalFlush(), LogState(), QueueBase(), and CPN::RemoteQueue::RemoteQueue().
bool CPN::QueueBase::writeshutdown protected
Definition at line 276 of file QueueBase.h.
Referenced by CPN::RemoteQueue::EndOfWritePacket(), Enqueue(), CPN::RemoteQueue::EnqueuePacket(), GetRawDequeuePtr(), GetRawEnqueuePtr(), CPN::RemoteQueue::GetState(), CPN::RemoteQueue::HandleError(), CPN::RemoteQueue::InternalCheckStatus(), InternalFlush(), IsWriterShutdown(), LogState(), ReadBlocked(), UnlockedShutdownWriter(), WriteBlocked(), and CPN::RemoteQueue::WriteBlockPacket().
bool D4R::QueueBase::writetagchanged protected inherited
Definition at line 125 of file D4RQueue.h.
Referenced by D4R::QueueBase::ReadBlock(), and D4R::QueueBase::UnlockedSignalWriterTagChanged().
The documentation for this class was generated from the following files:
lib/QueueBase.h
lib/QueueBase.cc