CPN: CPN::QueueAttr Class Reference
CPN::QueueAttr Class Reference
The attributes for a queue.
#include <QueueAttr.h>
Public Member Functions
QueueAttr ()
QueueAttr (const unsigned queueLength_, const unsigned maxThreshold_)
QueueAttr & SetAlpha (double a)
alpha is used by the remote queue to decide how much of the queue should go on the read side and how much should go on the write side.
QueueAttr & SetMaxWriteThreshold (unsigned mwt)
QueueAttr & SetName (const std::string &qname)
QueueAttr & SetEndpoints (const std::string &readernode, const std::string &readerport, const std::string &writernode, const std::string &writerport)
QueueAttr & SetExternalReader (const std::string &readername)
QueueAttr & SetExternalWriter (const std::string &writername)
QueueAttr & SetReader (const std::string &nodename, const std::string &portname)
QueueAttr & SetReader (Key_t nodekey, const std::string &portname)
QueueAttr & SetWriter (const std::string &nodename, const std::string &portname)
QueueAttr & SetWriter (Key_t nodekey, const std::string &portname)
QueueAttr & SetHint (std::string hint)
QueueAttr & SetDatatype (const std::string &type)
template<typename type >
QueueAttr & SetDatatype ()
QueueAttr & SetLength (unsigned length)
QueueAttr & SetMaxThreshold (unsigned maxthresh)
QueueAttr & SetNumChannels (unsigned channels)
QueueAttr & SetReaderNodeKey (Key_t k)
QueueAttr & SetWriterNodeKey (Key_t k)
QueueAttr & SetReaderKey (Key_t k)
QueueAttr & SetWriterKey (Key_t k)
const std::string & GetWriterNode () const
const std::string & GetWriterPort () const
const std::string & GetReaderNode () const
const std::string & GetReaderPort () const
Key_t GetWriterNodeKey () const
Key_t GetReaderNodeKey () const
Key_t GetWriterKey () const
Key_t GetReaderKey () const
unsigned GetLength () const
unsigned GetMaxThreshold () const
unsigned GetNumChannels () const
std::string GetHint () const
const std::string & GetDatatype () const
double GetAlpha () const
const std::string & GetName () const
unsigned GetMaxWriteThreshold () const
Private Attributes
std::string queuehint
std::string datatype
std::string queuename
unsigned queueLength
unsigned maxThreshold
unsigned numChannels
double alpha
std::string readernodename
std::string readerportname
std::string writernodename
std::string writerportname
Key_t readerkey
Key_t writerkey
Key_t readernodekey
Key_t writernodekey
unsigned maxwritethreshold
Detailed Description
The attributes for a queue.
The QueueAttr is used to encapsulate the information needed by the Kernel to create a new connection between endpoints.
The QueueAttr must have a writer and reader endpoint defined or an exception will be thrown by the Kernel when attempting to create the queue.
There are three ways to set the reader and writer endpoints. The first is to ask the context for the key for the endpoints and set them directly. The second is if you know the node keys then you can set the node keys and endpoint names. The third is to set the endpoints using both the node name and the endpoint names. The keys are always used over the name, but the name is used if the key is not set.
The default queue length and max threshold is zero.
The default number of channels is one.
The default queue hint is to not use the ThresholdQueue see SetHint
Definition at line 55 of file QueueAttr.h.
Constructor & Destructor Documentation
CPN::QueueAttr::QueueAttr () inline
Definition at line 57 of file QueueAttr.h.
             : queuehint(), datatype(TypeName<void>()),
             queueLength(0), maxThreshold(0),
             numChannels(1), alpha(0.5),
             readerkey(0), writerkey(0), readernodekey(0), writernodekey(0),
             maxwritethreshold(0)
         {}
CPN::QueueAttr::QueueAttr (const unsigned queueLength_, const unsigned maxThreshold_) inline
Definition at line 65 of file QueueAttr.h.
             : queuehint(), datatype(TypeName<void>()),
             queueLength(queueLength_), maxThreshold(maxThreshold_),
             numChannels(1), alpha(0.5),
             readerkey(0), writerkey(0), readernodekey(0), writernodekey(0),
             maxwritethreshold(0)
             {}
Member Function Documentation
double CPN::QueueAttr::GetAlpha () const inline
Definition at line 210 of file QueueAttr.h.
 { return alpha; }
const std::string& CPN::QueueAttr::GetDatatype () const inline
Definition at line 209 of file QueueAttr.h.
 { return datatype; }
std::string CPN::QueueAttr::GetHint () const inline
Definition at line 208 of file QueueAttr.h.
 { return queuehint; }
unsigned CPN::QueueAttr::GetLength () const inline
Definition at line 205 of file QueueAttr.h.
 { return queueLength; }
unsigned CPN::QueueAttr::GetMaxThreshold () const inline
Definition at line 206 of file QueueAttr.h.
 { return maxThreshold; }
unsigned CPN::QueueAttr::GetMaxWriteThreshold () const inline
Definition at line 212 of file QueueAttr.h.
 { return maxwritethreshold; }
const std::string& CPN::QueueAttr::GetName (void) const inline
Definition at line 211 of file QueueAttr.h.
Referenced by CPN::Kernel::CreateQueue().
 { return queuename; }
unsigned CPN::QueueAttr::GetNumChannels () const inline
Definition at line 207 of file QueueAttr.h.
 { return numChannels; }
Key_t CPN::QueueAttr::GetReaderKey () const inline
Definition at line 204 of file QueueAttr.h.
 { return readerkey; }
const std::string& CPN::QueueAttr::GetReaderNode () const inline
Definition at line 199 of file QueueAttr.h.
Referenced by CPN::Kernel::CreateQueue().
 { return readernodename; }
Key_t CPN::QueueAttr::GetReaderNodeKey () const inline
Definition at line 202 of file QueueAttr.h.
 { return readernodekey; }
const std::string& CPN::QueueAttr::GetReaderPort () const inline
Definition at line 200 of file QueueAttr.h.
Referenced by CPN::Kernel::CreateQueue().
 { return readerportname; }
Key_t CPN::QueueAttr::GetWriterKey () const inline
Definition at line 203 of file QueueAttr.h.
 { return writerkey; }
const std::string& CPN::QueueAttr::GetWriterNode () const inline
Definition at line 197 of file QueueAttr.h.
Referenced by CPN::Kernel::CreateQueue().
 { return writernodename; }
Key_t CPN::QueueAttr::GetWriterNodeKey () const inline
Definition at line 201 of file QueueAttr.h.
 { return writernodekey; }
const std::string& CPN::QueueAttr::GetWriterPort () const inline
Definition at line 198 of file QueueAttr.h.
Referenced by CPN::Kernel::CreateQueue().
 { return writerportname; }
QueueAttr& CPN::QueueAttr::SetAlpha (double a) inline
alpha is used by the remote queue to decide how much of the queue should go on the read side and how much should go on the write side.
Parameters
a 0 means all on read 1 means all on write
Returns
this
Definition at line 80 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             if (a < 0) { a = 0; }
             else if (a > 1) { a = 1; }
             alpha = a;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetDatatype (const std::string & type) inline
Definition at line 151 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             datatype = type;
             return *this;
         }
template<typename type > QueueAttr& CPN::QueueAttr::SetDatatype () inline
Definition at line 157 of file QueueAttr.h.
{
             datatype = TypeName<type>();
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetEndpoints (const std::string & readernode, const std::string & readerport, const std::string & writernode, const std::string & writerport) inline
Definition at line 97 of file QueueAttr.h.
{
             SetReader(readernode, readerport);
             SetWriter(writernode, writerport);
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetExternalReader (const std::string & readername) inline
Definition at line 104 of file QueueAttr.h.
{
             return SetReader(readername, readername);
         }
QueueAttr& CPN::QueueAttr::SetExternalWriter (const std::string & writername) inline
Definition at line 108 of file QueueAttr.h.
{
             return SetWriter(writername, writername);
         }
QueueAttr& CPN::QueueAttr::SetHint (std::string hint) inline
Parameters
hint the hint to give to the kernel for what kind of queue to create. Empty string or "default" will create a non threshold queue. "threshold will create a threshold queue. "rdma*" will create an rdma queue if it is available.
Definition at line 146 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             queuehint = hint;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetLength (unsigned length) inline
Definition at line 162 of file QueueAttr.h.
{
             queueLength = length;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetMaxThreshold (unsigned maxthresh) inline
Definition at line 167 of file QueueAttr.h.
{
             maxThreshold = maxthresh;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetMaxWriteThreshold (unsigned mwt) inline
Definition at line 87 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             maxwritethreshold = mwt;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetName (const std::string & qname) inline
Definition at line 92 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             queuename = qname;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetNumChannels (unsigned channels) inline
Definition at line 172 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             numChannels = channels;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetReader (const std::string & nodename, const std::string & portname) inline
Definition at line 112 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             readernodename = nodename;
             readerportname = portname;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetReader (Key_t nodekey, const std::string & portname) inline
Definition at line 119 of file QueueAttr.h.
{
             readernodekey = nodekey;
             readerportname = portname;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetReaderKey (Key_t k) inline
Definition at line 187 of file QueueAttr.h.
{
             readerkey = k;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetReaderNodeKey (Key_t k) inline
Definition at line 177 of file QueueAttr.h.
{
             readernodekey = k;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetWriter (const std::string & nodename, const std::string & portname) inline
Definition at line 126 of file QueueAttr.h.
Referenced by CPN::VariantCPNLoader::LoadQueue().
{
             writernodename = nodename;
             writerportname = portname;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetWriter (Key_t nodekey, const std::string & portname) inline
Definition at line 133 of file QueueAttr.h.
{
             writernodekey = nodekey;
             writerportname = portname;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetWriterKey (Key_t k) inline
Definition at line 192 of file QueueAttr.h.
{
             writerkey = k;
             return *this;
         }
QueueAttr& CPN::QueueAttr::SetWriterNodeKey (Key_t k) inline
Definition at line 182 of file QueueAttr.h.
{
             writernodekey = k;
             return *this;
         }
Member Data Documentation
double CPN::QueueAttr::alpha private
Definition at line 221 of file QueueAttr.h.
std::string CPN::QueueAttr::datatype private
Definition at line 216 of file QueueAttr.h.
unsigned CPN::QueueAttr::maxThreshold private
Definition at line 219 of file QueueAttr.h.
unsigned CPN::QueueAttr::maxwritethreshold private
Definition at line 230 of file QueueAttr.h.
unsigned CPN::QueueAttr::numChannels private
Definition at line 220 of file QueueAttr.h.
std::string CPN::QueueAttr::queuehint private
Definition at line 215 of file QueueAttr.h.
unsigned CPN::QueueAttr::queueLength private
Definition at line 218 of file QueueAttr.h.
std::string CPN::QueueAttr::queuename private
Definition at line 217 of file QueueAttr.h.
Key_t CPN::QueueAttr::readerkey private
Definition at line 226 of file QueueAttr.h.
Key_t CPN::QueueAttr::readernodekey private
Definition at line 228 of file QueueAttr.h.
std::string CPN::QueueAttr::readernodename private
Definition at line 222 of file QueueAttr.h.
std::string CPN::QueueAttr::readerportname private
Definition at line 223 of file QueueAttr.h.
Key_t CPN::QueueAttr::writerkey private
Definition at line 227 of file QueueAttr.h.
Key_t CPN::QueueAttr::writernodekey private
Definition at line 229 of file QueueAttr.h.
std::string CPN::QueueAttr::writernodename private
Definition at line 224 of file QueueAttr.h.
std::string CPN::QueueAttr::writerportname private
Definition at line 225 of file QueueAttr.h.
The documentation for this class was generated from the following file:
include/cpn/QueueAttr.h