CPN: Directory Class Reference
Directory Class Reference
#include <Directory.h>
Public Member Functions
Directory (const std::string &dirname_)
~Directory ()
void Rewind ()
bool End () const
std::string BaseName () const
std::string FullName () const
std::string DirName () const
void Next ()
bool IsDirectory () const
bool IsRegularFile () const
std::size_t Size () const
Private Member Functions
void Stat () const
Private Attributes
DIR * dir
std::string dirname
dirent * entry
struct stat status
bool stated
Detailed Description
Definition at line 33 of file Directory.h.
Constructor & Destructor Documentation
Directory::Directory (const std::string & dirname_)
Definition at line 27 of file Directory.cc.
References dir, dirname, and Next().
     : dir(0),dirname(dirname_), entry(0), stated(false)
 {
     dir = opendir(dirname.c_str());
     if (!dir) {
         throw ErrnoException();
     }
     Next();
 }
Directory::~Directory ()
Definition at line 37 of file Directory.cc.
References dir.
                       {
     closedir(dir);
 }
Member Function Documentation
std::string Directory::BaseName () const
Get the name of the current file in the directory
Definition at line 50 of file Directory.cc.
References entry.
Referenced by FullName().
{
     return std::string(entry->d_name);
 }
std::string Directory::DirName () const inline
Definition at line 55 of file Directory.h.
References dirname.
Referenced by FullName().
 { return dirname; }
bool Directory::End () const inline
Returns
true if we are at the end of the directory.
Definition at line 48 of file Directory.h.
References entry.
Referenced by CPN::NodeLoader::SearchDirectory().
 { return entry == 0; }
std::string Directory::FullName () const inline
Definition at line 54 of file Directory.h.
References BaseName(), and DirName().
 { return DirName() + "/" + BaseName(); }
bool Directory::IsDirectory () const
Definition at line 54 of file Directory.cc.
References Stat(), and status.
{
     Stat();
     return S_ISDIR(status.st_mode);
 }
bool Directory::IsRegularFile () const
Definition at line 59 of file Directory.cc.
References Stat(), and status.
{
     Stat();
     return S_ISREG(status.st_mode);
 }
void Directory::Next ()
Move to the next file in the directory.
Definition at line 45 of file Directory.cc.
References dir, entry, and stated.
Referenced by Directory().
                      {
     entry = readdir(dir);
     stated = false;
 }
void Directory::Rewind ()
Rewind to the beginning of the directory.
Definition at line 41 of file Directory.cc.
References dir.
{
     rewinddir(dir);
 }
std::size_t Directory::Size () const
Definition at line 64 of file Directory.cc.
References Stat(), and status.
{
     Stat();
     return status.st_size;
 }
void Directory::Stat () const private
Definition at line 69 of file Directory.cc.
References dirname, entry, stated, and status.
Referenced by IsDirectory(), IsRegularFile(), and Size().
{
     if (!stated) {
         std::string fpath = dirname + "/" + entry->d_name;
         if (stat(fpath.c_str(), &status) != 0) {
             throw ErrnoException();
         }
         stated = true;
     }
 }
Member Data Documentation
DIR* Directory::dir private
Definition at line 67 of file Directory.h.
Referenced by Directory(), Next(), Rewind(), and ~Directory().
std::string Directory::dirname private
Definition at line 68 of file Directory.h.
Referenced by Directory(), DirName(), and Stat().
dirent* Directory::entry private
Definition at line 69 of file Directory.h.
Referenced by BaseName(), End(), Next(), and Stat().
bool Directory::stated mutable private
Definition at line 71 of file Directory.h.
Referenced by Next(), and Stat().
struct stat Directory::status private
Definition at line 70 of file Directory.h.
Referenced by IsDirectory(), IsRegularFile(), Size(), and Stat().
The documentation for this class was generated from the following files:
include/cpn/utils/Directory.h
lib/utils/Directory.cc