CPN: PthreadMutex Class Reference
PthreadMutex Class Reference
#include <PthreadMutex.h>
Public Member Functions
PthreadMutex (void)
PthreadMutex (const PthreadMutexAttr &attr)
~PthreadMutex (void)
operator pthread_mutex_t * ()
operator const pthread_mutex_t * () const
PthreadMutex & Lock (void)
PthreadMutex & Unlock (void)
PthreadMutex & Take (void)
PthreadMutex & Give (void)
bool Poll (void)
int Error (void)
void Clear (void)
Protected Member Functions
void TrapError (int result)
Protected Attributes
int error
Private Attributes
pthread_mutex_t theMutex
Detailed Description
Definition at line 40 of file PthreadMutex.h.
Constructor & Destructor Documentation
PthreadMutex::PthreadMutex (void)
Definition at line 33 of file PthreadMutex.cc.
References theMutex, and PthreadErrorHandler::TrapError().
 {
     TrapError(pthread_mutex_init(&theMutex, 0));
 }
PthreadMutex::PthreadMutex (const PthreadMutexAttr & attr)
Definition at line 42 of file PthreadMutex.cc.
References theMutex, and PthreadErrorHandler::TrapError().
 {
     //  It should simply be:
 //  TrapError(pthread_mutex_init(&theMutex, mAttr));
     //  This is necessary because
     //      SGI's pthread_mutex_init is not const correct!!!
     pthread_mutexattr_t* myAttr = (PthreadMutexAttr&)mAttr;
     TrapError(pthread_mutex_init(&theMutex, myAttr));
 }
PthreadMutex::~PthreadMutex (void)
Definition at line 57 of file PthreadMutex.cc.
References theMutex, and PthreadErrorHandler::TrapError().
 {
     try {
         TrapError(pthread_mutex_destroy(&theMutex));
     } catch (...) {
         std::terminate();
     }
 }
Member Function Documentation
void PthreadErrorHandler::Clear (void) inline inherited
Definition at line 40 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { error = 0; }
int PthreadErrorHandler::Error (void) inline inherited
Definition at line 39 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
 { return error; }
PthreadMutex& PthreadMutex::Give (void) inline
Definition at line 52 of file PthreadMutex.h.
References Unlock().
Referenced by PthreadMutexProtected::~PthreadMutexProtected().
 { return Unlock(); }
PthreadMutex& PthreadMutex::Lock (void) inline
Definition at line 49 of file PthreadMutex.h.
References theMutex, and PthreadErrorHandler::TrapError().
Referenced by CPN::QueueBase::Lock(), and Take().
 { TrapError(pthread_mutex_lock(&theMutex)); return *this; }
PthreadMutex::operator const pthread_mutex_t * () const inline
Definition at line 47 of file PthreadMutex.h.
References theMutex.
 { return &theMutex; }
PthreadMutex::operator pthread_mutex_t * () inline
Definition at line 46 of file PthreadMutex.h.
References theMutex.
 { return &theMutex; }
bool PthreadMutex::Poll (void)
Definition at line 69 of file PthreadMutex.cc.
References theMutex, and PthreadErrorHandler::TrapError().
 {   int err = pthread_mutex_trylock(&theMutex);
     if(err == EBUSY)
         return false;
     TrapError(err);
     return true;
 }
PthreadMutex& PthreadMutex::Take (void) inline
Definition at line 51 of file PthreadMutex.h.
References Lock().
Referenced by PthreadMutexProtected::PthreadMutexProtected().
 { return Lock(); }
void PthreadErrorHandler::TrapError (int result) inline protected inherited
Definition at line 48 of file PthreadErrorHandler.h.
References PthreadErrorHandler::error.
Referenced by PthreadCondition::Broadcast(), PthreadAttr::DetachState(), PthreadBase::Join(), Pthread::Join(), Lock(), Poll(), Pthread::Pthread(), PthreadAttr::PthreadAttr(), PthreadBase::PthreadBase(), PthreadCondition::PthreadCondition(), PthreadConditionAttr::PthreadConditionAttr(), PthreadKey< T >::PthreadKey(), PthreadMutex(), PthreadMutexAttr::PthreadMutexAttr(), PthreadReadWriteLock::ReadUnlock(), PthreadAttr::ScheduleScope(), PthreadKey< T >::Set(), PthreadCondition::Signal(), PthreadCondition::TimedWait(), Unlock(), PthreadCondition::Wait(), PthreadReadWriteLock::WriteUnlock(), PthreadAttr::~PthreadAttr(), PthreadCondition::~PthreadCondition(), PthreadConditionAttr::~PthreadConditionAttr(), PthreadKey< T >::~PthreadKey(), ~PthreadMutex(), and PthreadMutexAttr::~PthreadMutexAttr().
 {
     if (err) {
         error = err;
         throw ErrnoException(err);
     }
 }
PthreadMutex& PthreadMutex::Unlock (void) inline
Definition at line 50 of file PthreadMutex.h.
References theMutex, and PthreadErrorHandler::TrapError().
Referenced by Give(), and CPN::QueueBase::Unlock().
 { TrapError(pthread_mutex_unlock(&theMutex)); return *this; }
Member Data Documentation
int PthreadErrorHandler::error protected inherited
Definition at line 43 of file PthreadErrorHandler.h.
Referenced by PthreadErrorHandler::Clear(), PthreadErrorHandler::Error(), PthreadErrorHandler::PthreadErrorHandler(), and PthreadErrorHandler::TrapError().
pthread_mutex_t PthreadMutex::theMutex private
Definition at line 57 of file PthreadMutex.h.
Referenced by Lock(), operator const pthread_mutex_t *(), operator pthread_mutex_t *(), Poll(), PthreadMutex(), Unlock(), and ~PthreadMutex().
The documentation for this class was generated from the following files:
include/cpn/threading/PthreadMutex.h
lib/threading/PthreadMutex.cc