CPN: Sync::Future< void > Class Template Reference
Sync::Future< void > Class Template Reference
#include <Future.h>
Public Member Functions
Future ()
virtual ~Future ()
bool Done ()
void Cancel ()
void Wait ()
bool IsCanceled ()
virtual void Set ()
virtual void Get ()
Protected Member Functions
void InternalWait ()
void InternalSet ()
Protected Attributes
PthreadMutex future_lock
PthreadCondition future_cond
bool done
bool canceled
Detailed Description
template<>
class Sync::Future< void >
Definition at line 93 of file Future.h.
Constructor & Destructor Documentation
Sync::Future< void >::Future () inline
Definition at line 95 of file Future.h.
 : done(false), canceled(false) {}
virtual Sync::Future< void >::~Future () inline virtual
Definition at line 96 of file Future.h.
 {}
Member Function Documentation
void Sync::Future< void >::Cancel () inline
Definition at line 103 of file Future.h.
References PthreadCondition::Broadcast(), Sync::Future< T >::canceled, Sync::Future< T >::future_cond, and Sync::Future< T >::future_lock.
                       {
             AutoLock<PthreadMutex> al(future_lock);
             canceled = true;
             future_cond.Broadcast();
         }
bool Sync::Future< void >::Done () inline
Definition at line 98 of file Future.h.
References Sync::Future< T >::canceled, Sync::Future< T >::done, and Sync::Future< T >::future_lock.
                     {
             AutoLock<PthreadMutex> al(future_lock);
             return done || canceled;
         }
virtual void Sync::Future< void >::Get () inline virtual
Definition at line 124 of file Future.h.
References Sync::Future< T >::future_lock, and Sync::Future< T >::InternalWait().
{
             AutoLock<PthreadMutex> al(future_lock);
             InternalWait();
         }
void Sync::Future< void >::InternalSet () inline protected
Definition at line 134 of file Future.h.
References PthreadCondition::Broadcast(), Sync::Future< T >::done, and Sync::Future< T >::future_cond.
{
             done = true;
             future_cond.Broadcast();
         }
void Sync::Future< void >::InternalWait () inline protected
Definition at line 130 of file Future.h.
References Sync::Future< T >::canceled, Sync::Future< T >::done, Sync::Future< T >::future_cond, Sync::Future< T >::future_lock, and PthreadCondition::Wait().
{
             while (!canceled && !done) { future_cond.Wait(future_lock); }
         }
bool Sync::Future< void >::IsCanceled () inline
Definition at line 114 of file Future.h.
References Sync::Future< T >::canceled, and Sync::Future< T >::future_lock.
{
             AutoLock<PthreadMutex> al(future_lock);
             return canceled;
         }
virtual void Sync::Future< void >::Set () inline virtual
Definition at line 119 of file Future.h.
References Sync::Future< T >::future_lock, and Sync::Future< T >::InternalSet().
{
             AutoLock<PthreadMutex> al(future_lock);
             InternalSet();
         }
void Sync::Future< void >::Wait () inline
Definition at line 109 of file Future.h.
References Sync::Future< T >::future_lock, and Sync::Future< T >::InternalWait().
                     {
             AutoLock<PthreadMutex> al(future_lock);
             InternalWait();
         }
Member Data Documentation
bool Sync::Future< void >::canceled protected
Definition at line 142 of file Future.h.
bool Sync::Future< void >::done protected
Definition at line 141 of file Future.h.
PthreadCondition Sync::Future< void >::future_cond protected
Definition at line 140 of file Future.h.
PthreadMutex Sync::Future< void >::future_lock protected
Definition at line 139 of file Future.h.
The documentation for this class was generated from the following file:
include/cpn/threading/Future.h