CPN: D4R Namespace Reference
D4R Namespace Reference
D4R algorithm as described in "A Distributed Deadlock Detection And Resolution Algorithm For Process Networks" by Allen, Zucknick and Evans.
Classes
class DeadlockException
The exception thrown when true deadlock is detected.
class Node
class QueueBase
class Tag
Typedefs
typedef std::list< weak_ptr
< QueueBase > > QueueList
Functions
void SignalReader (shared_ptr< QueueBase > q)
void SignalWriter (shared_ptr< QueueBase > q)
void GetQueues (QueueList &qlist, std::list< shared_ptr< QueueBase > > &out)
Detailed Description
D4R algorithm as described in "A Distributed Deadlock Detection And Resolution Algorithm For Process Networks" by Allen, Zucknick and Evans.
Typedef Documentation
typedef std::list<weak_ptr<QueueBase> > D4R::QueueList
Definition at line 124 of file D4RNode.cc.
Function Documentation
void D4R::GetQueues (QueueList & qlist, std::list< shared_ptr< QueueBase > > & out)
Definition at line 125 of file D4RNode.cc.
References FunctionNode::out.
Referenced by D4R::Node::SignalTagChanged().
{
         QueueList::iterator itr, end;
         itr = qlist.begin();
         end = qlist.end();
         while (itr != end) {
             shared_ptr<QueueBase> q = itr->lock();
             if (q) {
                 out.push_back(q);
                 ++itr;
             } else {
                 itr = qlist.erase(itr);
             }
         }
     }
void D4R::SignalReader (shared_ptr< QueueBase > q)
Definition at line 116 of file D4RNode.cc.
Referenced by D4R::Node::SignalTagChanged().
{
         q->SignalReaderTagChanged();
     }
void D4R::SignalWriter (shared_ptr< QueueBase > q)
Definition at line 120 of file D4RNode.cc.
Referenced by D4R::Node::SignalTagChanged().
{
         q->SignalWriterTagChanged();
     }