CPN: include/cpn/utils/PathUtils.h File Reference
PathUtils.h File Reference
#include <cpn/common.h>
#include <string>
Functions
std::string RealPath (const std::string &path)
std::string DirName (const std::string &path)
std::string BaseName (const std::string &path)
std::string PathConcat (const std::string &dir, const std::string &file)
bool IsAbsPath (const std::string &path)
Detailed Description
Author
John Bridgman
Definition in file PathUtils.h.
Function Documentation
std::string BaseName (const std::string & path)
Essentially the same as basename from libgen but this one is reentrant.
Definition at line 64 of file PathUtils.cc.
References PATH_SEP.
{
     std::string ret;
     if (!path.empty()) {
         std::string::const_iterator end = path.end();
         std::string::const_iterator start;
         --end;
         while (end != path.begin() && *end == PATH_SEP) { --end; }
         if (end == path.begin()) {
             if (*end == PATH_SEP) {
                 ret = std::string(end, end + 1);
             }
         } else {
             start = end;
             while (start != path.begin() && *start != PATH_SEP) { --start; }
             if (*start == PATH_SEP) { ++start; }
             ret = std::string(start, end + 1);
         }
     }
     return ret;
 }
std::string DirName (const std::string & path)
Returns
the directory name of path. Trailing / are not considered part of the path. If no / is contained inside path then . is returned.
This was written to provide a reentrant version of dirname. Should work the same as dirname in the POSIX 1003.1-2008 specification. Note that giving '..' returns '.' which is what the POSIX standard says but man basename does '..' gives '..' on most systems.
Definition at line 39 of file PathUtils.cc.
References PATH_SEP.
Referenced by Loader().
{
     std::string ret = ".";
     if (!path.empty()) {
         std::string::const_iterator cur = path.end();
         --cur;
         while (cur != path.begin() && *cur == PATH_SEP) { --cur; }
         if (cur == path.begin()) {
             if (*cur == PATH_SEP) {
                 ret = std::string(cur, cur + 1);
             }
         } else {
             while (cur != path.begin() && *cur != PATH_SEP) { --cur; }
             if (cur == path.begin()) {
                 if (*cur == PATH_SEP) {
                     ret = std::string(cur, cur + 1);
                 }
             } else {
                 while (cur != path.begin() && *cur == PATH_SEP) { --cur; }
                 ret = std::string(path.begin(), cur + 1);
             }
         }
     }
     return ret;
 }
bool IsAbsPath (const std::string & path)
Returns
true if path is an absolute path.
Definition at line 89 of file PathUtils.cc.
References PATH_SEP.
Referenced by ProcessLine().
{
     bool ret = false;
     if (!path.empty()) {
         if (path[0] == PATH_SEP) {
             ret = true;
         }
     }
     return ret;
 }
std::string PathConcat (const std::string & dir, const std::string & file)
Convinience function to concatinate a filename to a directory in a platform dependent way.
Definition at line 85 of file PathUtils.cc.
References PATH_SEP.
Referenced by ProcessLine().
{
     return dir + PATH_SEP + file;
 }
std::string RealPath (const std::string & path)
Fully resolve path to its absolute path. path must exist. Follows symlinks.
Definition at line 29 of file PathUtils.cc.
Referenced by Loader(), and ProcessLine().
{
     std::string ret;
     char *str = realpath(path.c_str(), 0);
     if (str != 0) {
         ret = str;
         free(str);
     }
     return ret;
 }