CPN: include/cpn/threading/PthreadFunctional.h File Reference
PthreadFunctional.h File Reference
#include <cpn/common.h>
#include <cpn/threading/PthreadDefs.h>
#include <cpn/threading/PthreadLib.h>
Classes
class PthreadFunctional
class PthreadFunctionalTemplate< T >
Functions
template<class T >
PthreadFunctional * CreatePthreadFunctional (T *obj, void *(T::*meth)(void))
template<class T >
PthreadFunctional * CreatePthreadFunctional (T *obj, void *(T::*meth)(void), const PthreadAttr &attr)
Function Documentation
template<class T > PthreadFunctional* CreatePthreadFunctional (T * obj, void *(T::*)(void) meth)
Definition at line 65 of file PthreadFunctional.h.
Referenced by CPN::RemoteContextClient::InternalTerminate(), CPN::Kernel::Kernel(), CPN::NodeBase::NodeBase(), CPN::RemoteContext::RemoteContext(), and CPN::RemoteQueue::RemoteQueue().
 {   return new PthreadFunctionalTemplate<T>(*obj, meth);    }
template<class T > PthreadFunctional* CreatePthreadFunctional (T * obj, void *(T::*)(void) meth, const PthreadAttr & attr)
Definition at line 69 of file PthreadFunctional.h.
 {   return new PthreadFunctionalTemplate<T>(*obj, meth, attr);  }