CPN: lib/utils/ThrowingAssert.cc File Reference
ThrowingAssert.cc File Reference
Some implementation for assert.
#include "common_priv.h"
#include <cpn/utils/ThrowingAssert.h>
#include <cpn/utils/StackTrace.h>
#include <sstream>
#include <vector>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
Functions
std::string CreateMessage (const char *exp, const char *file, int line, const char *func, const char *msg)
bool __ASSERT (const char *exp, const char *file, int line, const char *func, bool die)
bool __ASSERT (const char *exp, const char *file, int line, const char *func, bool die, const std::string &msg)
bool __ASSERT (const char *exp, const char *file, int line, const char *func, bool die, const char *fmt,...)
Detailed Description
Some implementation for assert.
Author
John Bridgman
Definition in file ThrowingAssert.cc.
Function Documentation
bool __ASSERT (const char * exp, const char * file, int line, const char * func, bool die)
Definition at line 59 of file ThrowingAssert.cc.
References CreateMessage(), and GetStack().
{
     if (die) {
         fprintf(stderr, "%s\nBacktrace:\n%s\n",
                 CreateMessage(exp, file, line, func, "").c_str(), GetStack(2).c_str());
         abort();
     } else {
         throw AssertException(CreateMessage(exp, file, line, func, ""));
     }
 }
bool __ASSERT (const char * exp, const char * file, int line, const char * func, bool die, const std::string & msg)
Definition at line 69 of file ThrowingAssert.cc.
References CreateMessage(), and GetStack().
{
     if (die) {
         fprintf(stderr, "%s\nBacktrace:\n%s\n",
                 CreateMessage(exp, file, line, func, "").c_str(), GetStack(2).c_str());
         abort();
     } else {
         throw AssertException(CreateMessage(exp, file, line, func, msg.c_str()));
     }
 }
bool __ASSERT (const char * exp, const char * file, int line, const char * func, bool die, const char * fmt, ...)
Definition at line 79 of file ThrowingAssert.cc.
References CreateMessage(), and GetStack().
{
     std::vector<char> buff(128, '\0');
     // Note this is based on the exmaple in the man page for vsnprintf.
     while (1) {
         /* Try to print in the allocated space. */
         va_list ap;
         va_start(ap, fmt);
         int n = vsnprintf(&buff[0], buff.size(), fmt, ap);
         va_end(ap);
         /* If that worked, return the string. */
         if (n > -1 && unsigned(n) < buff.size()) {
             break;
         }
         /* Else try again with more space. */
         if (n > -1) { /* glibc 2.1 */ /* precisely what is needed */
             buff.resize(n+1, '\0');
         }
         else { /* glibc 2.0 */ /* twice the old size */
             buff.resize(buff.size()*2, '\0');
         }
     }
     std::string msg = CreateMessage(exp, file, line, func, &buff[0]);
     if (die) {
         fprintf(stderr, "%s\nBacktrace:\n%s\n", msg.c_str(), GetStack(2).c_str());
         abort();
     } else {
         throw AssertException(msg);
     }
 }
std::string CreateMessage (const char * exp, const char * file, int line, const char * func, const char * msg)
Definition at line 34 of file ThrowingAssert.cc.
Referenced by __ASSERT().
{
     std::ostringstream oss;
     oss << "Assert failed in " << file << ":" << line;
     oss << " in " << func;
     oss << " : " << exp << '\n' << msg << '\n';
     return oss.str();
 }